### ISSUE TITLE
Allow installation of custom packages on provisioning

### ISSUE THREAD

**Issue by fionera** [kubermatic/kubeone#1045]
**What feature would you like to be added?**
A way to be able to install packages on worker deployment. 

**What are use cases of the feature?**
As example when running https://longhorn.io/ on the workers, some additional packages like `open-iscsi` have to be installed.

**Comment by kron4eg** [comment]
@fionera at the moment this is handled by using custom image with everything you need preinstalled. Being a cross distribution package manager is out of scope of KubeOne and MachineController.

**Comment by kron4eg** [comment]
On the other hand, we could install ’open-iscsi’ specifically.
