### ISSUE TITLE
Add variable to disable HA control plane in terraform examples

### ISSUE THREAD

**Issue by anon6789** [kubermatic/kubeone#1071]
**What feature would you like to be added?**
I would like to have a variable like `control_plane_ha` to configure the redundancy in the control plane.
If set to `true` (which could be default) the number of nodes would be 3 and if set to `false`, the control plane would have 1 node.

**What are use cases of the feature?**
For some use cases a highly available control plane is not necessary. Especially when using cheap cloud providers like Hetzner for development purpose this could reduce the costs even more.

What do you think about this feature?
Would you like me to create a PR for all the examples?

**Comment by kron4eg** [comment]
Our terraform examples was always intended only as __examples__, and never as "fixed" must-use configs. It's up to the end users to take them, copy, and customize to their needs and whatever shape people feel like. The only requirement is to respect "outputs" format which is documented here https://docs.kubermatic.com/kubeone/v1.0/infrastructure/terraform_integration/

**Comment by kron4eg** [comment]
Another purpose our example terraform configs are for is to be used for e2e testing.
