### ISSUE TITLE
Kubelets on Control Plane hosts serve a invalid certificate with configuration defaults

### ISSUE THREAD

**Issue by cpuspellcaster** [kubermatic/kubeone#1093]
**What happened**:
The Kubelet endpoint (port 10250) on Control Plane nodes serve a certificate on https that results in `x509: certificate signed by unknown authority` errors. (This error is not occurring on worker nodes provisioned by the MachineController.)

**What is the expected behavior**:
The Kubelet endpoint should serve a valid certificate.

**How to reproduce the issue**:
Provision a new cluster with KubeOne, and then create a Pod running on one of the Control Plane nodes with curl. In the Pod spec, set an environment variable `DD_KUBERNETES_KUBELET_HOST` to use a valueFrom set to the fieldRef `spec.nodeName`. Gain a shell inside the pod and run:
```bash
curl https://$DD_KUBERNETES_KUBELET_HOST:10250/pods -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(</var/run/secrets/kubernetes.io/serviceaccount/token)"
```

curl should report a `SSL certificate problem: self signed certificate in certificate chain` error message 

**Anything else we need to know?**
We asked about the issue in the #kubeone channel on the K8s Slack, and a engineer suggested setting the following value in the `/var/lib/kubelet/config.yaml` file on our Control Plane host:
```yaml
serverTLSBootstrap: true
```

After adding that value and restarting the kubelet on the affected host, a CSR was made in the Kubernetes API. We approved the CSR, and the kubelet endpoint started served a valid certificate without the self-signed errors.

Link to the suggestion: [Slack](https://kubernetes.slack.com/archives/CNEV2UMT7/p1599050012052500)

**Information about the environment**:
KubeOne version (`kubeone version`): 1.0.1
Operating system: macOS
Provider you're deploying cluster on: AWS
Operating system you're deploying on: Ubuntu 18.04

**Comment by kron4eg** [comment]
This is the default way kubeadm is working. It's different in machine-controller nodes because it configures kubelet differently and has automatic CSR approval controller.

**Comment by kron4eg** [comment]
Some context:

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#certificate-rotation

> Note: The CSR approving controllers implemented in core Kubernetes do not approve node serving certificates for security reasons. To use RotateKubeletServerCertificate operators need to run a custom approving controller, or manually approve the serving certificate requests.

We have custom approving controller in the machine-controller but it needs to be adapted for KubeOne purposes.
