### ISSUE TITLE
Add csi-hetzner driver for persistent storage

### ISSUE THREAD

**Issue by anon6789** [kubermatic/kubeone#1097]
**What feature would you like to be added?**
I would like to use PersistentVolumes on a Hetzner cluster.
Hetzner has a official [csi-driver](https://github.com/hetznercloud/csi-driver).

Without the driver the PersistentVolumeClaim stays pending.

**What are use cases of the feature?**
Running stateful workloads on hetzner with persistent data out of the box.

Would you like to have a PR adding this feature?
If yes, do you have a recommendation where to put this functionality in the code? Inside the Hetzner externalccm code or some dedicated code for csi/storage?

**Comment by kron4eg** [comment]
CSI Driver doesn't require any specific changes to control plane and can be installed as normal user-defined-workload, so what's preventing this?

**Comment by anon6789** [comment]
Yes you are right, csi driver as a user-defined-workload is feasible. My idea was to have volume support out of the box for a better user experience. But bloating the default installation with a maybe unused csi driver sounds also out of scope. So I would agree to have the CSI driver as a user-defined-workload.

**Comment by kron4eg** [comment]
CSI driver could be an addon (so no new code).
