### ISSUE TITLE
Add validation of cluster_name early in the installation process

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/kubeone#1115]
**What feature would you like to be added?**

Due to a rather suboptimal cluster_name `run.vsphere` the etcd ring could not established.

In the static etcd manifest of node 1 the following is configured:
    - --initial-cluster=run=https://10.2.35.200:2380
and in the second node the following:
    - --initial-cluster=run=https://10.2.35.200:2380,run=https://10.2.10.127:2380
and both have the same name
    - --name=run

As it looks the dot in the cluster_name caused that all nodes got the same hostname `run` which was an issue for etcd.

---

We should add some checks upfront and make the user of kubeone aware of not using dots in the cluster_name.

Kubeone should validate that:
* hostnames are uniq
* clustername has no dots

**What are use cases of the feature?**

Using KubeOne to create a cluster.

**Comment by moelsayed** [comment]
I tried to reproduce this using master 7080c2b1a8. I used `run.hetzner` as a cluster name in both tfvars and kubeone manifest. The cluster was provisioned successfully:
```
NAME                                 STATUS   ROLES    AGE     VERSION
run.hetzner-control-plane-1          Ready    master   5m44s   v1.18.6
run.hetzner-control-plane-2          Ready    master   4m55s   v1.18.6
run.hetzner-control-plane-3          Ready    master   3m48s   v1.18.6
run.hetzner-pool1-59cb945f46-47w25   Ready    <none>   44s     v1.18.6
```

```
kube-system   etcd-run.hetzner-control-plane-1                      1/1     Running   0          6m4s
kube-system   etcd-run.hetzner-control-plane-2                      1/1     Running   0          5m12s
kube-system   etcd-run.hetzner-control-plane-3                      1/1     Running   0          4m6s
```
Can you please provide more details on how to reproduce this?

**Comment by moelsayed** [comment]
This issue was fixed as a side effect on another PR. Closing.
