### ISSUE TITLE
Kubelet needs to be started manually while updateing the control planes

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubeone#1137]
**What happened**:
While running kubeone apply to update the K8S version i needed to start the kubelet manually on all control nodes to let the updates run through

**What is the expected behavior**:
kubeone will issue the kubelet start (as it do the stop some time before)

**How to reproduce the issue**:
Take a running cluster and change the K8S version and run kubeone apply

**Anything else we need to know?**
We Updated K8S 1.16.7 to 1.16.15 (but same had append wen updating to 1.16.13)
We did not touch the worker wit kubeone

**Information about the environment**:
KubeOne version (`kubeone version`):  1.0.2
Operating system: Arch
Provider you're deploying cluster on: Openstack
Operating system you're deploying on:  CoreOS (i know)

**Comment by qeqar** [comment]
https://gist.github.com/qeqar/b39b6a14de0f15a2300aed35938c4c45

some log lines with --verbose: 
[Here](https://gist.github.com/qeqar/b39b6a14de0f15a2300aed35938c4c45#file-gistfile1-txt-L39) it get stopped.
and from [here](https://gist.github.com/qeqar/b39b6a14de0f15a2300aed35938c4c45#file-gistfile1-txt-L88) i need to start the kubelet manually

**Comment by kron4eg** [comment]
This has been fixed in master, in https://github.com/kubermatic/kubeone/pull/1099, please try building kubeone from the git.

**Comment by qeqar** [comment]
Nice, did not see this. will test it wen i have time. bit we can close this here.

thanks

**Comment by xmudrii** [comment]
@qeqar We've released KubeOne v1.0.4 today, which includes a fix for this problem. If you encounter this problem again, please reopen this issue or create a new one.
