### ISSUE TITLE
Packet to Equinix Metal Rebrand Request

### ISSUE THREAD

**Issue by rainleander** [kubermatic/kubeone#1160]
**What feature would you like to be added?**

Packet was acquired by Equinix in March. To help make our vision for global, interconnected bare metal a reality, we've rebranded Packet as Equinix Metal™ and introduced new locations and features. Login, sign up, and say hello at metal.equinix.com. Example rebrands:

Packet --> Equinix Metal
support@packethost.com --> support@equinixmetal.com
https://slack.packet.com/ --> https://slack.equinixmetal.com/
Freenode IRC #packethost --> Freenode IRC #equinixmetal
packet.com --> metal.equinix.com
https://app.packet.net/ --> https://console.equinix.com/

**What are use cases of the feature?**

This is partially a documentation request, but also partially a coding rewrite, so I'll nudge our Equinix Metal engineers to help resolve this one. Thanks, everyone!

**Comment by moelsayed** [comment]
@rainleander Hi there, 
We would like to move forward with this. You mentioned you would have someone from your side contribute some code?

**Comment by rainleander** [comment]
Yes, would you like to set up a call or would you prefer PRs or ...?

**Comment by moelsayed** [comment]
We always love PRs :), but if you like to have a call to kick things of, that's very doable. Please reach out in the #kubeone channel on kubernetes slack.

**Comment by xmudrii** [comment]
xref #1539
