### ISSUE TITLE
Add support to deploy static pod manifests

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubeone#1210]
**What feature would you like to be added?**

Static pods manifests should be installable similar to KubeOne add-ons.

**What are use cases of the feature?**

[Kube-VIP](https://kube-vip.io/) uses static pods to deploy a virtual (HA) IP address for the Kubernetes API.

To allow API access, Kube-VIP has to run before nodes can join the cluster. `Kubeadm` fails if a node already has static manifests when running `kubeadm join` (pre-flight check). This requires the following steps to bootstrap a KubeOne cluster with a Kube-VIP API load balancer:

1. Deploy kube-vip to the first CP node
2. Run `kubeone install`
3. Deploy kube-vip to the second and third CP node

(See https://kube-vip.io/hybrid/static/)

I suggest to allow installing static manifests by KubeOne with an add-on like mechanism to streamline the bootstrapping process.

**Comment by kron4eg** [comment]
This has need achieved the other way around: https://github.com/kubermatic/kubeone/pull/1217
