### ISSUE TITLE
Support setting AdmissionConfiguration in the KubeOne manifest

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubeone#1211]
**What feature would you like to be added?**

Some admission controllers allow or require a AdmissionConfiguration that is presented to the API server using the `--admission-control-config-file` flag. This config file should be modifiable for a KubeOne cluster.

**What are use cases of the feature?**

E.g., the ResourceQuota admission controller allows to limit the use of PriorityClasses in certain namespaces (https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default). This can be used to avoid that essential pods are evicted.

**Comment by shaase-ctrl** [comment]
We are not planning on implementation any time soon.
