### ISSUE TITLE
Add ability to set Eviction and resource reservation kubelet policies

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubeone#1216]
Hi,
Is it possible to set specific options mentioned here: https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

I've found a kubelet-18.0 configmap in the kube-system namespace, but I have been unsure if I can just adjust it. It would be nice to set such arguments via kubeone.

**Comment by kron4eg** [comment]
Unfortunately not. Not at the moment at least.

**Comment by shibumi** [comment]
Not sure if it's possible to transform this issue into a feature request, but I think setting reservations or eviction limits would be a neat feature. Would be cool if it would be possible to set/add kubelet/kubeadm flags. Changing a kubelet configuration on a live cluster is not that easy (although it's possible..)

**Comment by xmudrii** [comment]
@shibumi I've updated the issue to convert it to a feature request.

**Comment by shibumi** [comment]
@xmudrii  Thanks a lot! What does the "Epic" label mean? :D

**Comment by kron4eg** [comment]
@shibumi it's coming from the zenhub, we use it for planning.

**Comment by shibumi** [comment]
@xmudrii  or @kron4eg  can one of you summarize what would need to be done for having this feature in kubeone? We really need this and I would like to work on this, if possible.

**Comment by kron4eg** [comment]
In a very high-level description, as usual in such cases we need to:
* make machine-controller understand such case and be able to produce VMs with user-provided flags
* do the same for kubeone (control plane machines) + machine-controller integration of those change, sounds like API changes.
* update machine-controller in kubeone

**Comment by xmudrii** [comment]
xref #1539
