### ISSUE TITLE
Investigate the issue with the kube-apiserver not serving all resource on Kubernetes 1.20 clusters

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1222]

**Comment by slamdev** [comment]
@xmudrii does it affect 1.21 as well? from release notes of v1.2.0-beta.0 it is unclear if it's safe to use 1.21 or not...

**Comment by xmudrii** [comment]
@slamdev Kubernetes 1.21 is currently in development, so it's not possible to provision 1.21 clusters with KubeOne. This appears to be an upstream issue and we're currently investigating what might cause it and how to fix it. We'll report back here once we have some additional details.
