### ISSUE TITLE
Containerd support (umbrela)

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#1223]

**Comment by shibumi** [comment]
Really looking forward to this. I asked myself already how difficult this would be for flatcar instances and kubeOne.
If you need anyone for testing, ping me.

**Comment by kron4eg** [comment]
@shibumi technically containerd support is already merged, we only want to add some more checks in the light of upcoming dockershim removal.

**Comment by kron4eg** [comment]
@shibumi re flatcar: https://github.com/kinvolk/lokomotive/issues/1058

**Comment by shibumi** [comment]
@kron4eg  I understand. Thanks for the hint to the lokomotive issue.
