### ISSUE TITLE
Use the machine-controller templates for docker installation

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubeone#125]
Currently we have our own code to install Docker here. Instead we use import the respective templates from the machine-controller in order to be able to profit from the lessons learned there, like forcing the correct storage driver, limiting log size and being able to deploy any docker version we want on CoreOS.

*Acceptance criteria*

* The code to install Docker is completely imported from the machine-controller

**Comment by kron4eg** [comment]
So after reevaluating this issue, me and @xmudrii decided that "A little copying is better than a little dependency", and that allowing KubeOne to move independently from machine-controller without hard dependencies it a way to go.
