### ISSUE TITLE
Bad zone fixed setting at GCE Terraform output.tf causes failure in the deployment of workers pool 

### ISSUE THREAD

**Issue by JoaquimFreitas** [kubermatic/kubeone#1263]
**What happened**:
Using the Terraform project for GCE with `terraform.tfvars` with:
```
project             = "kubeone-demo-1"
cluster_name        = "kubeone-cluster-1"
region              = "us-east1"
```

And the `kubeone.yaml` file with:
```
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
versions:
  kubernetes: '1.19.3'
cloudProvider:
  gce: {}
  cloudConfig: |
    [global]
    regional = true
```

The `terraform apply` command executes without problems.
The `terraform output -json > tf.json` command generates the JSON file.
The `kubeone apply -m kubeone.yaml -t tf.json` does all the magic without any errors, terminating with:
```
....
INFO[19:21:35 GMT] Installing machine-controller...
INFO[19:21:48 GMT] Installing machine-controller webhooks...
INFO[19:21:51 GMT] Waiting for machine-controller to come up...
INFO[19:22:21 GMT] Creating worker machines...
```

BUT the **initial worker node is never created**, and the `machine-controller` also fails any scale up/down attempt of the `machinedeployment`.

**What is the expected behavior**:

The initial worker node to be created, and the `machine-controller` to be able to scale up/down the `machinedeployment`.

**How to reproduce the issue**:

Just use the Terraform project for GCE with `terraform.tfvars` with:
```
project             = "kubeone-demo-1"
cluster_name        = "kubeone-cluster-1"
region              = "us-east1"
```

**Anything else we need to know?**

The problem seems to be located on the `output.tf` file of the GCE Terraform project, line **66**, due to the fact that is hardcoding the zone with the "`-a`" sufiix, and not all Google Cloud Regions have a "`-a`" zone:

`66:       zone                  = "${var.region}-a" `

which is the case of the Region `us-east1` ( which only have zones from "`-b`" to "`-d`" ).

**Information about the environment**:
KubeOne version (`kubeone version`):  `1.2.0-beta.1`
Operating system:  Ubuntu `20.04`
Provider you're deploying cluster on: Google Cloud
Operating system you're deploying on:  Ubuntu `18.04.5 LTS`

**Comment by shaase-ctrl** [comment]
We will document this in our Example section in documentation and explain a little more about the provided examples in our github directory.
