### ISSUE TITLE
vSphere Permission terraform

### ISSUE THREAD

**Issue by yonkeurichi1993** [kubermatic/kubeone#1269]
Hello Community
Since then I've been trying to install Kubernetes clusters on my vSphere vmware. But apparently I'm facing some permission issues. However the created user has all the rights. Can someone give me some types?

**Comment by toschneck** [comment]
@youssefazrak unfortunately the permissions for the vSphere terraform are not document for kubeone right now. But for me you worked to use the `user cluster` permissions of KKP: https://docs.kubermatic.com/kubermatic/v2.16/requirements/cloud_provider/vsphere/#user-cluster

**Comment by xmudrii** [comment]
The permissions are now documented here: https://docs.kubermatic.com/kubeone/master/architecture/requirements/machine_controller/vsphere/vsphere/

/close
