### ISSUE TITLE
CA bundle for all components

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#1298]
**What feature would you like to be added?**
Add new CABundle API field, and in case it's present, save as ConfigMap. Use it to mount to one of standard locations where workloads will look up for system CA.

Workloads like:
* CCM
* machine-controller

**What are use cases of the feature?**
To have similar https://github.com/kubermatic/kubermatic/pull/6538 mechanism.

**Comment by toschneck** [comment]
@kron4eg one question to the feature. At recent projects we get the requirement to use a private registry behind a custom CA, to pull some images inside of the kubeone cluster. Would this be handled by the feature as well?

cc @dharapvj

**Comment by kron4eg** [comment]
@toschneck no, not at the moment.

P.S.
I think this is also not implemented in the machine-controller.
