### ISSUE TITLE
Cluster-autoscaler addon missing `machinedeployments/scale` ClusterRole resource

### ISSUE THREAD

**Issue by pozsi** [kubermatic/kubeone#1299]
**What happened**:
Autoscaling doesn't work when creating a cluster using the cluster-autoscaler addon. The problem is [described here in detail](https://github.com/kubernetes/autoscaler/issues/3804) in the kubernetes autoscaler repository, and [fixed in this pull request](https://github.com/kubernetes/autoscaler/pull/3805).

**What is the expected behavior**:
ClusterRole should have sufficient privileges to work.

**How to reproduce the issue**:
Follow the [instructions](https://docs.kubermatic.com/kubeone/v1.2/advanced/addons/) to set up a cluster with the cluster-autoscaler addon, and tail the autoscaler log to see the missing permission error when trying to scale.

**Information about the environment**:
KubeOne version:  1.2
Operating system: Ubuntu 20.04
Provider you're deploying cluster on: Hetzner
Operating system you're deploying on: Ubuntu 20.04

**Comment by kron4eg** [comment]
Thank you for the report, #1331 will fix the issue.
