### ISSUE TITLE
Guide on how to setup an on-prem or a local cluster

### ISSUE THREAD

**Issue by ivanovaleksandar** [kubermatic/kubeone#1303]
Looking into the documentation, I was unable to find any useful info on how to create a KubeOne cluster in an on-prem environment, or a VM / vagrant setup that will help with trying out and evaluating the product. 

Can someone point me to some useful info?

Thanks.

**Comment by xmudrii** [comment]
The following ticket should cover documenting how to create clusters on bare-metal setups and providers that are not officially supported: https://github.com/kubermatic/docs/issues/569

Regarding the useful info:

1) You can define the instances to be used for a Kubernetes control plane in the KubeOne configuration manifest. You would have to create them manually and ensure that you can access them over SSH.
    - You can run `kubeone config print --full` for the configuration manifest reference. Search for the `controlPlane` key/structure and there you can see how to define instances to be used.
    - Regarding SSH requirements, you can check out the following document: https://docs.kubermatic.com/kubeone/v1.2/prerequisites/ssh/
2) You will have to create one instance to be used as a Load Balancer to the Kubernetes API server.
   - The information about that instance/LoadBalancer is provided using the `apiEndpoint` structure in the configuration manifest (you can find details about it in the config manifest reference)
   - We have an example with the GoBetween load balancer. It's not ideal for production setups, but it's good enough for testing: https://github.com/kubermatic/kubeone/blob/master/examples/terraform/openstack/gobetween.sh
3) You'll have set `cloudProvider` to `none` in the configuration manifest, such as:
    ```
    ...
    cloudProvider:
      none: {}
    ```
4) For worker nodes, check out the static worker nodes feature: https://docs.kubermatic.com/kubeone/v1.2/workers/static_workers/

**Comment by xmudrii** [comment]
We've recently added a new tutorial describing how to set up a Kubernetes cluster on providers that are not natively supported (e.g. bare-metal...). The tutorial can be found on [our documentation website](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters_baremetal/).

Since the tutorial has been added, I'll go ahead and close this ticket. If you have any follow-up questions, please feel free to reopen the issue or create a new one.

/close
