### ISSUE TITLE
CSIMigration failed due to missing  csi flags

### ISSUE THREAD

**Issue by syjabri** [kubermatic/kubeone#1317]
**What happened**:
I want to migrate from the openstack in-tree to the external cloud provider using kubeone, the migration part is not done and the volumes still point to the old in-tree cloud provider.

**What is the expected behavior**:
After enabling csimigration, an additional feature-gates field should be added to the controller-manager and apiserver "CSIMigration=true,CSIMigrationOpenStack=true,ExpandCSIVolumes=true". 
And after the migration is done, an annotation should be automatically  added to the persistent volume `pv.kubernetes.io/migrated-to: cinder.csi.openstack.org`, also the `--cloud-provider=external and --cloud-config` fields should be removed from the kubeadm flag file. 
**How to reproduce the issue**:
1. Add the external field in the kubeone.yaml configuration file as mentioned [here](https://docs.kubermatic.com/kubeone/v1.2/api_reference/v1beta1/)  
```
cloudProvider:
    openstack: {}
    external: true
```
2. Then run kubeone upgrade --force 
3. An openstack-cloud-controller-manager is deployed in the kube-system namespace 
4. After that deploy the Cinder CSI Plugin manually. 
5. Added `csiMigration: true` in the kubeone configuration file .
6. Re-Run kubeone upgrade --force

**Information about the environment**:
KubeOne version (`kubeone version`):  v1.2.1
Operating system: Flatcar
Provider you're deploying cluster on: Openstack

**Comment by kron4eg** [comment]
Unfortunately the feature you are looking for (you can track it here #616) was never implemented in the first place, so it can't be a bug. Closing as "duplicate".
