### ISSUE TITLE
Support containerd on Flatcar Linux

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1333]
**What feature would you like to be added?**

Flatcar now enables the CRI plugin by default, which means that we can use containerd for Kubernetes clusters. More details about this can be found in the [Flatcar docs](https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/).

**Comment by toschneck** [comment]
@mfahlandt FYI
