### ISSUE TITLE
Install-script fails because of missing unzip

### ISSUE THREAD

**Issue by okin** [kubermatic/kubeone#1337]
**What happened**:

I wanted to install KubeOne through the oneliner from the documentation.
It failed because my system was missing unzip.

```
ubuntu@kubeone:~$ curl -sfL get.kubeone.io | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   637  100   637    0     0   2757      0 --:--:-- --:--:-- --:--:--  2757
100 10.4M  100 10.4M    0     0  9279k      0  0:00:01  0:00:01 --:--:-- 15.1M
Copying kubeone binary into /usr/local/bin
sh: 36: unzip: not found
```

**What is the expected behavior**:

It installs fine.
If unzip is missing i'd expect me to notify of it and maybe tell me how to make it work (i.e. by a message like "you are missing unzip. Please install and run the command again")

**How to reproduce the issue**:

Installed on a basic Ubuntu 20.04 image - nothing installed but bare necessities.

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): -
Operating system: Ubuntu 20.04
Provider you're deploying cluster on: -
Operating system you're deploying on: -

**Comment by kron4eg** [comment]
@okin thank you for the report. BTW, we accept contributions.
