### ISSUE TITLE
Cloud Firewalls for worker nodes

### ISSUE THREAD

**Issue by npajkovsky** [kubermatic/kubeone#1345]
Hey,

I wanted to secure worker nodes on Hetzner. Adding firewall for control plane nodes is very easy, but there's no good way to add worker nodes into cloud firewall.

The best would be, that terraform will create a cloud firewall and machine-controlled will attach a node to that firewall.

Is there any plan for this feature? What's the best way to secure worker nodes?

**Comment by kron4eg** [comment]
>The best would be, that terraform will create a cloud firewall and machine-controlled will attach a node to that firewall.

Unfortunately that's not supported, and is not planned. 

>What's the best way to secure worker nodes?

Please see calico hostEndpoints feature: https://docs.projectcalico.org/security/kubernetes-nodes

**Comment by npajkovsky** [comment]
Ok, thanks. Closing.
