### ISSUE TITLE
Upgrade CustomResourceDefinition to v1

### ISSUE THREAD

**Issue by etenzy** [kubermatic/kubeone#1359]
**What feature would you like to be added?**
Upgrading the usage of CustomResourceDefinition from v1beta1 to v1

**What are use cases of the feature?**
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+

**Comment by kron4eg** [comment]
Fixed by https://github.com/kubermatic/kubeone/pull/1405

**Comment by kron4eg** [comment]
oh no, not entirely fixes.
