### ISSUE TITLE
Invalid provider configuration on vSphere with newer terraform version

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/kubeone#1395]
**What happened**:

On `terraform plan` I get the following exception

> Provider "registry.terraform.io/hashicorp/vsphere" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.

Adding the required arguments (with the variables properly set) in main.tf also did not work:

```
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server
  allow_unverified_ssl = true
}
```

After downgrading terraform towards 0.13.7 this error message dissapears.

**What is the expected behavior**:

terraform plan does not throw an error message

**How to reproduce the issue**:

Try to run a vSphere installation with the manifests provided in the examples folder.

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 1.2.1
Operating system: Ubuntu 18.04.5 LTS
Provider you're deploying cluster on: vSphere
Operating system you're deploying on:

**Comment by xmudrii** [comment]
@stroebitzer Are you using manifests from the master branch or the manifests that come with the KubeOne v1.2.1 release? Currently, only manifests on the master branch are compatible with Terraform v1.0.0. You can check #1376 as a reference for what you need to do if you use older manifests.

**Comment by stroebitzer** [comment]
I was taking mangifests from the master branch and adjusted them. But I remember having this issue already ~ 1 year ago on some vSphere installation.

**Comment by xmudrii** [comment]
@stroebitzer Have you tried to run `terraform init -upgrade` or to remove `.terraform` directory and run `terraform init` again?

**Comment by stroebitzer** [comment]
I removed the .terraform directory before running terraform init again.

**Comment by kron4eg** [comment]
Now since we moved to require terraform 1.0, this is not valid anymore.
