### ISSUE TITLE
Addons do not wait for namespace generation

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubeone#1434]
Hi,

For installing Argo on my new cluster I have put two files in an `addon` directory and I have enabled addons via the configuration flag in the kubeone manifest. However, it seems like kubeone does not wait for the argocd namespace creation. The namespace got created, but I had to run the argo.yaml manually.

In which order are the files applied? I named my namespace yaml: `00-argocd-namespace.yaml` and the argo deployment has the name `argo.yaml`.

Also: Does the addons feature support multiple sub folders? Right now I have one addons directory with many YAML files. I would like to create a few directories and put YAMLs in each.

**Comment by kron4eg** [comment]
> For installing Argo on my new cluster I have put two files in an `addon` directory and I have enabled addons via the configuration flag in the kubeone manifest. However, it seems like kubeone does not wait for the argocd namespace creation. 

Yes, that's true, kubeone doesn't wait for anything since it doesn't know what's inside. Contents of the addons are being `kubectl apply`-ed after render.


> In which order are the files applied? I named my namespace yaml: `00-argocd-namespace.yaml` and the argo deployment has the name `argo.yaml`.

Kubeone render whole addon into the single manifest that's `kubectl apply`-ed.

> Also: Does the addons feature support multiple sub folders? Right now I have one addons directory with many YAML files. I would like to create a few directories and put YAMLs in each.

No, only 1 level of subdir is supported.

**Comment by shibumi** [comment]
> Kubeone render whole addon into the single manifest that's kubectl apply-ed.
is there a specific order for this single manifest that gets created? because normally `kubectl apply -f single.yaml` should work if I create the namespace in this yaml first and then the rest of the resources. I would really like to know why applying the argo.yaml failed.

**Comment by kron4eg** [comment]
The order is whatever [fs.ReadDir](https://pkg.go.dev/io/fs?#ReadDir) has. See https://github.com/kubermatic/kubeone/blob/06c8f8c5fefc2bd39516e97b3d140adb1199472b/pkg/addons/manifest.go#L68

**Comment by shibumi** [comment]
@kron4eg thanks
