### ISSUE TITLE
Support for Openstack

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubeone#146]
In order to allow using KubeOne in Openstack-Based environments it would be nice to have Openstack support.

*AC:*

* Kubeone can be used to spin up a control plane on Openstack
* Kubeone can be used to create workers nodes for the Openstack control plane
* The Openstack cloud-provider functionality has been verified (PV+LBs)

**Comment by xmudrii** [comment]
For v0.6.0 we want to do testing and for v0.7.0 we want to do E2E tests, so we're sure it always works.
