### ISSUE TITLE
containerd Image Registry customization

### ISSUE THREAD

**Issue by slamdev** [kubermatic/kubeone#1470]
**What feature would you like to be added?**

I would like to have an ability to customize containerd registry plugin to control the list of registries it uses. Like it is done in kubespray: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/containerd.md#containerd-config

According to the https://github.com/kubermatic/kubeone/blob/master/pkg/scripts/funcs.go#L171 it is not possible at the moment.

**What are use cases of the feature?**

With the docker hub rate limits (and to reduce the pulling latency) it is common to have a caching proxy in front of the docker hub, like https://hub.docker.com/r/rpardini/docker-registry-proxy

**Comment by kron4eg** [comment]
I think you are looking for https://docs.kubermatic.com/kubeone/master/references/kubeone_cluster_v1beta1/#registryconfiguration

**Comment by slamdev** [comment]
that option is for **replacing** the registry for some particular images, but I am looking for a way to configure containerd registry mirrors. **machine-controller** has it as a flag: https://github.com/kubermatic/machine-controller/blob/v1.35.2/cmd/machine-controller/main.go#L150

**Comment by kron4eg** [comment]
Oh that one... yeah, you are right.
