### ISSUE TITLE
Test cluster provisioning and upgrading on all supported providers

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1477]
This issue assumes:

* Make sure to allow NodePorts in firewall/SecurityGroup if supported
  * For example, AWS has [`open_nodeports` variable](https://github.com/kubermatic/kubeone/blob/d5733ef5efccd05ca598db8c8562f88088565d8e/examples/terraform/aws/variables.tf#L180-L184) which is used to allow NodePorts
* Create a Kubernetes cluster running latest-1 release
  * Keep default settings
  * Enable `.cloudProvider.external` if we support the external CCM for the provider
* Ensure that all nodes are ready by running `kubectl get nodes`
* Ensure that basic operations work
  * Create a Deployment, try exposing it using NodePort Service, make sure you can reach it out
  * If external CCM is deployed, ensure that:
    * Node object has proper IP addresses (`kubectl get nodes -o wide`)
    * Each node has `providerID` set (`kubectl describe node <node-name> | grep -i providerid`)
    * If supported, create a LoadBalancer Service and make sure it's reachable
    * If supported, create a PersistentVolume and mount it in a pod
* Upgrade the cluster to the latest Kubernetes release
  * Make sure to also upgrade MachineDeployments by passing the `--upgrade-machine-deployments` flag to `kubeone apply`
* Wait for all Machines to get rolled out
* Ensure that all nodes are ready by running `kubectl get nodes`
* Ensure that all resources are created earlier are still functioning
* Try recreating some of resources created earlier
* Run Kubernetes conformance tests using Sonobuoy

**Acceptance criteria:**

* All manual tests are passing
* All Kubernetes conformance tests are passing

**Supported providers:**

* AWS
* Azure
* DigitalOcean
* GCP
* Hetzner Cloud
* OpenStack
* Packet (Equinix Metal)
* VMware vSphere

Source: https://docs.kubermatic.com/kubeone/master/architecture/compatibility/

**Comment by xrstf** [comment]
Part of #1476
