### ISSUE TITLE
Test cluster provisioning and upgrading on all supported operating systems

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1478]
This issue assumes following all the steps from #1477, but this time choose a single provider (for example AWS) and test all supported operating systems.

**Acceptance criteria:**

* All manual tests are passing
* All Kubernetes conformance tests are passing

**Supported operating systems:**

* Ubuntu 18.04 (Bionic)
* Ubuntu 20.04 (Focal)
* Debian 10 (Buster)
* CentOS 7
* CentOS 8
* RHEL 7
* RHEL 8
* Flatcar
* Amazon Linux 2

Source: https://docs.kubermatic.com/kubeone/master/architecture/compatibility/

**Comment by xrstf** [comment]
Part of #1476

**Comment by kron4eg** [comment]
Ubuntu 20.04 ✅

**Comment by kron4eg** [comment]
All the subtasks are closed, so closing this too.
