### ISSUE TITLE
Test Docker to containerd migration

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1479]
This issue assumes:

* Create a Kubernetes cluster running 1.21 on cloud provider of choice
* Ensure that all nodes are running Docker
  * This can be checked by running `kubectl get nodes -o wide` or SSH-ing to nodes and checking is there `docker` systemd unit
* Create some workload, e.g a bunch of Deplyoments
* Try upgrading the cluster to Kubernetes 1.22
  * **This should fail with the error that we don't support Kubernetes 1.22 clusters running Docker**
* Migrate the cluster to containerd
  * Follow this guide to migrate the cluster: https://docs.kubermatic.com/kubeone/master/guides/containerd_migration/
* Make sure that all pods are still running as expected
* Try upgrading the cluster to Kubernetes 1.22

**Acceptance criteria:**

* Migrating to containerd is successful
* Migration guide is up to date and works as expected
* Upgrading the cluster is successful after migrating it

**Comment by xrstf** [comment]
Part of #1476

**Comment by aborilov** [comment]
passed! 

minors:
* I had the same issue https://github.com/kubermatic/kubeone/issues/1458
* my private key was missing in `tf.json`, had to add it manually(maybe it's the expected behavior)
