### ISSUE TITLE
Test CCM/CSI migration

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1480]
This issue assumes:

* Create a Kubernetes cluster running 1.21 with `.cloudProvider.external` set to `false`
* Make sure that all nodes are ready (`kubectl get nodes`)
* Create the following resources (not all providers support all resources):
  * Deployment that uses PV provisioned by in-tree volume provider
  * LoadBalancer Service that points to the Deployment
* Set `.cloudProvider.external` to `true`
* Run the `kubeone migrate to-ccm-csi` command to trigger the first phase of the migration
* Ensure that:
  * `kube-apiserver` and `kube-controller-manager` still have the `--cloud-provider` and `--cloud-config` flags
  * `kube-controller-manager` has the `--controllers` flag that disable in-tree CCM controllers (`*,bootstrapsigner,tokencleaner,-cloud-node-lifecycle,-route,-service`)
  * external CCM and CSI are deployed and healthy (`kubectl get pods -n kube-system`)
  * `machine-controller-webhook` has `-node-external-cloud-provider` and `-node-kubelet-feature-gates` flags
* Roll out the MachineDeployment
* Wait for the new node to join the cluster and become ready
* Ensure that previously created Deployment and LoadBalancer Service are still working
* Upgrade the cluster to Kubernetes 1.22 and ensure that all components still have the proper flags (as described earlier)
* Finish the CCM migration by running `kubeone migrate to-ccm-csi --complete`
* Ensure that:
  * `kube-apiserver` and `kube-controller-manager` does **not** have the `--cloud-provider` and `--cloud-config` flags
  * `kube-controller-manager` has the following `--controllers` flag: `*,bootstrapsigner,tokencleaner`
  * external CCM and CSI are deployed and healthy (`kubectl get pods -n kube-system`)
  * `machine-controller-webhook` has `-node-external-cloud-provider` and `-node-kubelet-feature-gates` flags

**Supported providers:**

* OpenStack
* vSphere

**Comment by xrstf** [comment]
Part of #1476
