### ISSUE TITLE
Test upgrading cluster created using previous stable release

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1481]
This issue assumes following all the steps from #1477, but this time:

* Create the cluster using the KubeOne 1.2.3
* Choose a single provider and a single operating system (for example AWS and Ubuntu)
* Upgrade the cluster using the KubeOne 1.3.0-rc.0

**Acceptance criteria:**

* All manual tests are passing
* All Kubernetes conformance tests are passing

**Comment by xrstf** [comment]
Part of #1476

**Comment by kron4eg** [comment]
✅
