### ISSUE TITLE
Promote the KubeOneCluster API to v1beta2

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1539]
The KubeOneCluster v1beta1 API has been introduced in [August 2020 with the v1.0.0 release](https://github.com/kubermatic/kubeone/blob/master/CHANGELOG.md#v100---2020-08-18). Since then, it appears to work very well and satisfy all requirements.

Considering that we didn't need to change anything for over a year, I think we should consider declaring it stable and promoting it to v1.

Of course, we should take this opportunity for the final adjustments and improvements, so if you have any feedback and suggestions, please leave them in this issue.

**Comment by xmudrii** [comment]
We should make sure to fix #1496 and improve support for the embedded addons.

Besides that, we should decide do we want to proceed with `kubeone.io` as the API group or switch to the `kubeone.k8c.io` API group to match the KKP.

**Comment by kron4eg** [comment]
it's done!
