### ISSUE TITLE
Error when determine operating system

### ISSUE THREAD

**Issue by Eptiiix** [kubermatic/kubeone#1563]
**What happened**: 
the kubeone installer fails when trying to determine the operating system and returns Process exited with status 1

root@host:~$ kubeone apply -m kubeone.yaml 
INFO[20:54:48 CEST] Determine hostname...                        
INFO[20:54:48 CEST] Determine operating system...                
ERRO[20:54:48 CEST] Process exited with status 1                  node=XXX
WARN[20:54:48 CEST] Task failed, error was: at least one of the tasks has encountered an error 
WARN[20:54:53 CEST] Retrying task...                             
INFO[20:54:53 CEST] Determine operating system...                
ERRO[20:54:53 CEST] Process exited with status 1                  node=XXX
WARN[20:54:53 CEST] Task failed, error was: at least one of the tasks has encountered an error 

**What is the expected behavior**:
That Kubeone works without any errors.

**How to reproduce the issue**:
just set it up in normal way on a kvm server.
But im not sure if the problem is "kvm server".

**Anything else we need to know?**
there are different provider where kubeone is not working, in my case they was all kvm virtualized.
Tested Providers: php-friends.de (KVM) (kubeone does not work)
                           ovhcloud.com (KVM) (kubeone does not work)
                           hetzner.com (Cloud) (kubeone does work)

**Information about the environment**:
KubeOne version (`kubeone version`): 
{
  "kubeone": {
    "major": "1",
    "minor": "3",
    "gitVersion": "1.3.0",
    "gitCommit": "bfe6683334acdbb1a1d9cbbb2d5d5095f6f0111e",
    "gitTreeState": "",
    "buildDate": "2021-09-15T06:03:30Z",
    "goVersion": "go1.16.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "35",
    "gitVersion": "v1.35.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}

Operating system: 
(Hetzner.com and PHP-Friends.de has the same output of 'cat /etc/os-release')
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Provider you're deploying cluster on: php-friends.de (kvm virtualization)

Operating system you're deploying on: Debian GNU/Linux 11 (bullseye)

**Comment by xmudrii** [comment]
@Eptiiix Debian is not supported by KubeOne. Please check our [compatibility guide](https://docs.kubermatic.com/kubeone/v1.3/architecture/compatibility/) for information about our support policy.

I'll close this ticket, but if you have any further questions please feel free to reopen it or create a new ticket.
/close

**Comment by Eptiiix** [comment]
i have the same problem when using ubuntu or centos.
