### ISSUE TITLE
terraform error for eks-d

### ISSUE THREAD

**Issue by nicohouillon** [kubermatic/kubeone#1580]
**What happened**:  terraform plan fails to prepare EKS-D plan and return errors regarding the os variable

Error: Invalid index
│
│   on main.tf line 52, in data "aws_ami" "ami":
│   52:     values = var.ami_filters[var.os].image_name
│     ├────────────────
│     │ var.ami_filters is map of object with 5 elements
│     │ var.os is "amazon_linux2"
│
│ The given key does not identify an element in this collection value.

**What is the expected behavior**:
plan to be successfully build

**How to reproduce the issue**: 
follow tutorial https://docs.kubermatic.com/kubeone/v1.3/tutorials/creating_clusters_eks_d/#prerequisites
run terraform plan

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 1.3.0-rc.0
Operating system:  ubuntu 20.04
Provider you're deploying cluster on: AWS
Operating system you're deploying on: n/a

**Comment by nicohouillon** [comment]
replacing  `amazon_linux2 ` with `amzn2` in terraform.tfvars made it work

**Comment by kron4eg** [comment]
@nicohouillon it's not about vpc not found, it's about not having an internet gateway attache to your VPC.

```
data "aws_internet_gateway" "default" {
  filter {
    name   = "attachment.vpc-id"
    values = [data.aws_vpc.selected.id]
  }
}
```

our _example_ terraform configuration of course doesn't suppose such thing, you will need to take our _example_ and adjust it to your needs.
