### ISSUE TITLE
Changing worker type on Hetzner

### ISSUE THREAD

**Issue by jorgepsmatos** [kubermatic/kubeone#1581]
Hi, I'm trying to change the worker type of my Kubernetes cluster on Hetzner. 

Does anyone know if that is possible and how to proceed?

I did try the following steps:

```
# Scalding down to 0 replicas
kubectl scale -n kube-system machinedeployment <machinedeployment-name> --replicas=0

# Updating worker_type on terraform.tfvars to a different value (from cpx11 to cpx21)

# Apply changes
terraform apply

# Create new output file
terraform output -json > tf.json

# Run kubeone
kubeone apply -m kubeone.yaml -t tf.json

# Scale replicas up
kubectl scale -n kube-system machinedeployment <machinedeployment-name> --replicas=2
```

But after doing that the nodes are still cpx11, not cpx21

**Comment by kron4eg** [comment]
Hey 👋

Kubeone creates Machinedeployment only once, at cluster creation time. After that it’s up to you to manage your machinedeployments.

**Comment by kron4eg** [comment]
I meant to say: what you did will not lead anywhere. You have to manage machinedeployment yourself, like you’d do with all other kubernetes worloads (e.g. Deployments)

**Comment by jorgepsmatos** [comment]
Thank you. I edited the machine deployment and was able to get it to work.

Thanks for the help
