### ISSUE TITLE
KubeOne and KubeVIP

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubeone#1604]
Hello Kubermatic,

I would like to use KubeVIP instead of an external KubeAPI loadbalancer. Right now, I use an external Haproxy VM as loadbalancer for my KubeAPI Controlplane. I could add an additional keepalived service for high-availability, but I thought about giving KubeVIP a chance first.

With KubeVIP it should be possible to loadbalance between the control plane nodes via the control plane nodes instead of an external load balancer.

KubeVIP supports two deployments:

* A static pod on every node
* A daemonset on all control nodes

How do I bootstrap KubeOne with KubeVIP? Do you have any idea? I thought about putting the Daemonset configuration in the addons folder, but I think that the addons folder will be executed AFTER cluster creation not after bootstrapping the first node, am I right?

**Comment by pczerkas** [comment]
Hi @shibumi , can you elaborate on:
> 3. provision the k8s cluster with kube-vip as addon
