### ISSUE TITLE
registry override removes path from coredns image

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubeone#1612]
Wen using the registryOverride option, the path part in the coredns image get lost.

k8s.gcr.io/coredns/coredns:v1.8.4 -> override.domain/coredns:v1.8.4
So the path coredns was striped and the image therefore not found.

**Information about the environment**:
KubeOne version 1.3.: 
Provider you're deploying cluster on: openstack
Operating system you're deploying on: flatcar

**Comment by qeqar** [comment]
Missing Kubeone config:

-----
kind: KubeOneCluster
name: %CLUSTER_NAME%
versions:
  kubernetes: '%CLUSTER_VERSION%'
clusterNetwork:
  cni:
    canal:
      mtu: 1450
cloudProvider:
  openstack: {}
  external: true
  cloudConfig: |
    [Global]
    region=%OS_REGION_NAME%
    username="%OS_USERNAME%"
    password="%OS_PASSWORD%"
    auth-url=%OS_AUTH_URL%
    tenant-id=%OS_PROJECT_ID%
    domain-id=%OS_PROJECT_DOMAIN_ID%

    [LoadBalancer]
    subnet-id=%SUBNET_ID%
    floating-network-id=ID
    create-monitor=true
    monitor-delay=10s
    monitor-max-retries=3
    monitor-timeout=3s
    use-octavia=true

    [Metadata]
    search-order=metadataService,configDrive
containerRuntime:
  containerd: {}
features:
  openidConnect:
    enable: true
    config:
      issuerUrl: xxx
      clientId: xxx
      usernamePrefix: xxx
  metricsServer:
    enable: true
registryConfiguration:
  overwriteRegistry: registry.domain
-----

**Comment by qeqar** [comment]
using the assetConfiguration helps as a workaround.

```
assetConfiguration:                                                             
       coreDNS:                                                                      
         imageRepository: registry.domain/coredns     
```

But this is deprecated stuff and will removed in kubeone 1.4

**Comment by embik** [comment]
I looked into this and it seems to be something that it is intentional in `kubeadm`. See https://github.com/kubernetes/kubeadm/issues/2513 and https://github.com/kubernetes/kubernetes/pull/102502.

Since a repository that mirrors/caches upstream is likely placing the image in `coredns/coredns`, we probably need to adjust the passed kubeadm config to include it. Let me check on this.
