### ISSUE TITLE
Cluster Name not Configured in Openstack OCCM

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubeone#1613]
Wen creating multiple kubeone cluster in one openstack tenant. We could run i a load balancer issue, if we use the same namespace/service name combination in both.

Then both LB have the same name and will be grabbed by both cloud provider

There is a option int the openstack controller `--cluster-name` which would solve that problem, as cluster name is part of the lb name.

This is already implemented for azure, aws and the cinder provider.

So we would need this for the cloud provider too.

**Comment by xmudrii** [comment]
/reopen
We still need to cherry-pick this to the `release/v1.3` branch.
