### ISSUE TITLE
Use Ginkgo directly in E2E tests

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubeone#162]
Currently we use kubetest in the e2e tests, however this has the drawback that it limits the config options we can pass into Ginkgo, which is the Framework that executes the actual tests.

*Acceptance criteria*

* We use Ginkgo instead of Kubetest for the E2E tests

**Comment by xmudrii** [comment]
After discussion, we decided that `kubetest` is working very well for us, so there is no need to migrate to Ginkgo.

/close
