### ISSUE TITLE
Run E2E tests on Hetzner

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#165]
After issue we encountered yesterday (see #160 for more details), we concluded that it is important to test KubeOne on all cloud providers we support to ensure it really works as intended and not just on AWS.

As we provide example Terraform script for Hetzner, we need to decide do we want to run E2E tests on Hetzner as well. We can run E2E tests on each PR or even run them periodically.

Depends on #163

**Acceptance criteria**
* [ ] It is decided do we want to run E2E tests on Hetzner
* [ ] If we decide to do so, a Prow Presubmit/Periodic job is created to run tests

**Comment by xmudrii** [comment]
I'll take care of this.

/assign

**Comment by kron4eg** [comment]
FYI: prow job for hetzner has been reverted as it's constantly give us

```
hcloud_server.control_plane.2: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)
```
