### ISSUE TITLE
Update vSphere CSI addon

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1652]
The latest version of the vSphere CSI driver supports Kubernetes 1.22 clusters. We should update to reintroduce 1.22 support for vSphere clusters.

https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.4.0

**Comment by WeirdMachine** [comment]
I also updated the CCM to the latest version and now support Kubernetes 1.22
