### ISSUE TITLE
chore: s/AddonCSIHetnzer/AddonCSIHetzner/g

### ISSUE THREAD

**Issue by almereyda** [kubermatic/kubeone#1653]
In quickly reviewing #1560 after its merge I have spotted `AddonCSIHetnzer` and found three occurrences in this repository:

https://github.com/kubermatic/kubeone/search?q=AddonCSIHetnzer

One could rename that to `AddonCSIHetzner` everywhere.

```diff
- AddonCSIHetnzer
+ AddonCSIHetzner
```

**Comment by kron4eg** [comment]
will be fixed in #1642
