### ISSUE TITLE
Support Nutanix as a new Cloud Provider

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubeone#1697]
As a user,  I want to enable my (on premise) Nutanix environment so that  I can setup KubeOne clusters on top of my Nutanix stack.

**Acceptance Criteria**
- Evaluate if there are any specific features we should make use of
- Implement specific on-premise and edge (single node) configurations
- Document the new cloud provider

**Comment by xmudrii** [comment]
Support for Nutanix has been implemented in KubeOne. The only remaining task is E2E tests, but we're tracking that as part of #1727.
/close
