### ISSUE TITLE
After upgrade to latest kubeone/examples/terraform/hetzner/ workers do not get deployed and no kubeconfig

### ISSUE THREAD

**Issue by stevek-pro** [kubermatic/kubeone#1711]
**What happened**:

After upgrade to latest kubeone/examples/terraform/hetzner/ workers do not get deployed and no kubeconfig

**What is the expected behavior**:

Worker Nodes to be deployed (on Hetzner API via Terraform) and have kubeconfig downloaded

**How to reproduce the issue**:

`terraform init && terraform  plan && terraform apply`

See my gist:
https://gist.github.com/stevek-pro/171ebd67addebd16ae127a7cea964218

**Anything else we need to know?**
It worked with the version from kubeone/examples/terraform/hetzner/ from 3 months ago. Maybe the new Firewall feature has not been tested thoroughly enough?

**Information about the environment**:
KubeOne version (`kubeone version`):  "1.3.0"
Operating system: Ubuntu WSL2
Provider you're deploying cluster on: Hetzner
Operating system you're deploying on: Ubuntu 20

**Comment by kron4eg** [comment]
@stevek-pro just checked using latest master, works perfectly well...

In your "How to reproduce the issue", for some reason I don't see `kubeone apply` invocation, did you by any chance forgot about it?

**Comment by stevek-pro** [comment]
I learned that the Kubermatic docs are not completely covering this and are faulty in this regard. I went to a Blog Post Tutorial to fill in the blanks.

**Comment by xmudrii** [comment]
@stevek-pro Thank you for the feedback! Can you please post the link to the Kubermatic docs that you used, as well as, link to the blog post?

**Comment by stevek-pro** [comment]
Hi xmudrii, Can't find it anymore unfortunately. I will do a write-up of the entire procedure in my [blog](blog.shiftcloud.de) at a later date and post it around. Basically you need to init, plan, output, apply, output into json, and apply with kubeone manifest in the end.
