### ISSUE TITLE
Migration script is hardcoded to flatcar

### ISSUE THREAD

**Issue by alam0rt** [kubermatic/kubeone#1742]
https://github.com/kubermatic/kubeone/blob/97d438bdc1ffcc7986c85aacfef996b7037a1ffb/pkg/scripts/os.go#L36

The above causes `containerd` on Ubuntu hosts to fail as it is configured to use flatcar specific utilities like torcx.

**Comment by kron4eg** [comment]
@alam0rt thanks for the report!
