### ISSUE TITLE
Test cluster provisioning on DigitalOcean - Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1771]
For more details see instructions posted in #1768.

**All tests should be done with `.cloudProvider.external` enabled. Make sure to enable the default-storage-class addon (see the Epic for more details).**

Operating Systems to be tested:

* [x] Ubuntu 20.04
* [x] CentOS 7

Supported Kubernetes versions (choose only one operating system -- for example, you can test 1.23.3 on all operating systems, and then test other versions only on Ubuntu):

* [x] 1.23.3
* [x] 1.22.6
* [x] 1.21.9
* [x] 1.20.15

Upgrades:

* [x] 1.22.6 -> 1.23.3
* [x] 1.21.9 -> 1.22.6
* [x] 1.20.15 -> 1.21.9

For each test, you should:

* Create a LoadBalancer Service and point to some test pod (e.g. Nginx pod). The LB should be reachable and serve the content as expected
* Create a DigitalOcean PV and attach it to the pod

**Comment by ahmedwaleedmalik** [comment]
Works as expected
