### ISSUE TITLE
Test cluster provisioning on Equinix Metal - Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1772]
For more details see instructions posted in #1768.

**All tests should be done with `.cloudProvider.external` enabled.**

Operating Systems to be tested:

* [x] Ubuntu 20.04
* [x] CentOS 7

Supported Kubernetes versions (choose only one operating system -- for example, you can test 1.23.3 on all operating systems, and then test other versions only on Ubuntu):

* [x] 1.23.3
* [x] 1.22.6
* [x] 1.21.9
* [x] 1.20.15

Upgrades:

* [x] 1.22.6 -> 1.23.3
* [x] 1.21.9 -> 1.22.6
* [x] 1.20.15 -> 1.21.9

**Comment by ahmedwaleedmalik** [comment]
Works as expected.

**NOTE:** Didn't test PV provisioning since it wasn't mentioned in the instructions.

**Comment by xmudrii** [comment]
> NOTE: Didn't test PV provisioning since it wasn't mentioned in the instructions.

That's fine. Equinix Metal doesn't have a CSI driver.
