### ISSUE TITLE
Test Docker to containerd migration -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1778]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * Make sure to explicitly enable Docker by adding this to your KubeOneCluster manifest
    ```yaml
    containerRuntime:
      docker: {}
    ```
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Ensure the Container Runtime is Docker by running `kubectl get nodes -o wide` and checking the Container Runtime column
* Follow the [Migrating to containerd tutorial](https://docs.kubermatic.com/kubeone/master/guides/containerd_migration/) to migrate your cluster
* Make sure to rotate your MachineDeployments afterward
* Wait for rotated nodes to join the cluster
* Ensure the Container Runtime is containerd by running `kubectl get nodes -o wide` and checking the Container Runtime column
* Try to run some test pod to make sure it's going to be scheduled properly

This test can be done on a single provider with a single Kubernetes version, but each operating system should be tested:

* [x] Ubuntu 20.04
* [x] CentOS 7
* [x] Flatcar
* [x] RHEL 8.5

It's recommended to run tests on AWS because AWS supports all 4 operating systems. You can use Kubernetes 1.23.3.

**Comment by dermorz** [comment]
> You can use Kubernetes 1.23.3
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.23.3'
cloudProvider:
  aws: {}
containerRuntime:
  docker: {}
```
is greeted with:
```
$ ./kubeone apply -m kubeone.yaml -t examples/terraform/aws/tf.json
Error: failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: unable to validate the given KubeOneCluster object: containerRuntime: Invalid value: kubeone.ContainerRuntimeDocker{RegistryMirrors:[]string(nil)}: kubernetes v1.22+ require containerd container runtime
failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: unable to validate the given KubeOneCluster object: containerRuntime: Invalid value: kubeone.ContainerRuntimeDocker{RegistryMirrors:[]string(nil)}: kubernetes v1.22+ require containerd container ContainerRuntimeDocker
```

1. This error is correct and tells me what's wrong. But maybe `kubeone` can handle this more gracefully and not put it out twice in this raw wrapped go error format.
2. I will continue testing with Kubernetes 1.21.9

**Comment by dermorz** [comment]
The warning in the end of the installer references the docs of the previous release.
```
WARN[12:05:48 CET] For more info about MachineDeployments see: https://docs.kubermatic.com/kubeone/v1.3/guides/machine_controller/
$ ./kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.0-rc.0",
    "gitCommit": "a42407f815ceb762457738b4041823fbb5e1f5a9",
    "gitTreeState": "",
    "buildDate": "2022-02-03T15:28:27Z",
    "goVersion": "go1.17.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
...
```

**Comment by dermorz** [comment]
Newly created nodes (when rolling MachineDeployments according to https://docs.kubermatic.com/kubeone/v1.3/cheat_sheets/rollout_machinedeployment/) get created with container-runtime `docker`.

```
STATUS   ROLES                  AGE     VERSION   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
Ready    <none>                 3m51s   v1.21.9   Ubuntu 20.04.3 LTS   5.11.0-1028-aws   docker://19.3.15
Ready    control-plane,master   44m     v1.21.9   Ubuntu 20.04.3 LTS   5.11.0-1028-aws   containerd://1.4.12
Ready    <none>                 4m4s    v1.21.9   Ubuntu 20.04.3 LTS   5.11.0-1028-aws   docker://19.3.15
Ready    control-plane,master   43m     v1.21.9   Ubuntu 20.04.3 LTS   5.11.0-1028-aws   containerd://1.4.12
Ready    <none>                 4m1s    v1.21.9   Ubuntu 20.04.3 LTS   5.11.0-1028-aws   docker://19.3.15
Ready    control-plane,master   42m     v1.21.9   Ubuntu 20.04.3 LTS   5.11.0-1028-aws   containerd://1.4.12
```

**Comment by dermorz** [comment]
Retesting after fix…
