### ISSUE TITLE
Test CCM/CSI migration with static worker nodes -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1780]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * Make sure to have `.cloudProvider.external` disabled:
    ```yaml
    cloudProvider:
      external: false
    ```
  * Make sure to use static worker nodes instead of machine-controller-managed nodes. You should set initial replicas to 0, and then extend the Terraform configs to create machines to be used for static worker nodes. See Terraform configs for AWS as an example of how to handle this
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Create a LoadBalancer Service and point to some test pod (e.g. Nginx pod). The LB should be reachable and serve the content as expected
* Create a GCE PV and attach it to the pod
* Follow the [CCM/CSI migration tutorial](https://docs.kubermatic.com/kubeone/master/guides/ccm_csi_migration/) to migrate your cluster
* Wait for rotated nodes to join the cluster
* Ensure that the LoadBalancer service is still reachable
* Recreate the LoadBalancer service and ensure it's reachable
* Recreate the pod with the volume attached and make sure the new pod is Running

This test can be done on a single operating system with a single Kubernetes version, but each supported provider should be tested:

* [x] Azure
* [x] OpenStack

It's recommended to run tests on Ubuntu with Kubernetes 1.23.3.

**Comment by ahmedwaleedmalik** [comment]
Works as expected.

**NOTE:** Only Azure and OpenStack have been tested for this, as mentioned in the ticket.
