### ISSUE TITLE
Test using different credentials for machine-controller and CCM -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1784]
Instructions:

* Prepare two different set of credentials (one to be used for MC, another for CCM)
* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * Before creating the cluster, when setting credentials, make sure to set only prefixed credentials. For example, if you’re instructed to set `AWS_ACCESS_KEY_ID`, set `MC_AWS_ACCESS_KEY_ID` and `CCM_AWS_ACCESS_KEY_ID` instead. Do that for all environment variables needed for the cloud provider.
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Ensure that `kubeone-machine-controller-credentials`, `kubeone-operating-system-manager-credentials`, and `kubeone-ccm-credentials` Secrets have correct credentials
  * `kubeone-machine-controller-credentials` and `kubeone-operating-system-manager-credentials` should have the same credentials

**Comment by ahmedwaleedmalik** [comment]
Works as expected
