### ISSUE TITLE
Test propagating cluster name to OpenStack CCM -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1788]
Instructions — Phase 1:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster on OpenStack
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Check the CCM pod to ensure that the `—cluster-name` flag is set to the name of the KubeOne cluster

Instructions — Phase 2:

* Once the test is done, reset the cluster using the `kubeone reset` command
* Download the KubeOne 1.3.0 or 1.3.1 release and provision the cluster again
* Ensure that the CCM pod does **not** have the `—cluster-name` flag
* Reconcile the cluster by running `kubeone apply` with the latest KubeOne 1.4.0 release candidate
* Ensure that the CCM pod does **not** have the `—cluster-name` flag
* Edit the CCM daemonset to add the `—cluster-name` flag and set it to the name of the KubeOne cluster
* Reconcile the cluster by running `kubeone apply` with the latest KubeOne 1.4.0 release candidate
* Check the CCM pod to ensure that the `—cluster-name` flag is set to the name of the KubeOne cluster

The Kubernetes version and the operating system don’t matter for this test.

**Comment by ahmedwaleedmalik** [comment]
Works as expected.
