### ISSUE TITLE
Test the cluster-autoscaler addon -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1789]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * Create a cluster on AWS
  * Edit the `output.tf` file **before running `terraform apply`** to add the following annotations to [the `annotations` block](https://github.com/kubermatic/kubeone/blob/a42407f815ceb762457738b4041823fbb5e1f5a9/examples/terraform/aws/output.tf#L77-L79) (for simplicity, do that for only one MachineDeployment)
    * `”cluster.k8s.io/cluster-api-autoscaler-node-group-min-size” = “1”`
    * `”cluster.k8s.io/cluster-api-autoscaler-node-group-max-size” = “5”`
  * Enable the `cluster-autoscaler` embedded addon by adding the following stanza to your KubeOneCluster manifest before running `kubeone apply` for the first time:
    ```yaml
    …
    addons:
      enable: true
      addons:
      - name: cluster-autoscaler
    ```
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Create deployment with 3 replicas (you can use any image, e.g. Nginx), and set resource requests and limits so that you can only one pod per node (e.g. if node has 4 GB RAM, set memory request to 3 GB)
* Ensure that all 3 replicas are scheduled as expected
* Scale up the deployment to 5 replicas
* Describe the newly-created pods. Scaling up the deployment should have triggered the cluster scale up
* After new nodes join the cluster and pods get scheduled, scale the deployment to 2 replicas
* After some time (e.g. 10 minutes), the cluster should be scaled down

**Comment by ahmedwaleedmalik** [comment]
Works as expected.
