### ISSUE TITLE
Test overwrite registry feature and image loader script -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1793]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster on AWS
  * Before running `kubeone apply`, set up the registry mirror on the bastion node:
    * SSH to the bastion node
    * Install Docker or containerd (you can follow the official Docker/containerd tutorial)
    * Run Docker Registry as described in [the Docker Registry document](https://docs.docker.com/registry/)
      * For simplicity, use the host network by adding `—network=host` to the `dcoker run` command
    * Run the image loader script provided in the KubeOne release archive
      * Example: `KUBERNETES_VERSION=1.23.3 TARGET_REGISTRY=127.0.0.1:5000 ./image-loader.sh`
      * Before running the script, make sure to replace the Kubernetes version with the appropriate version
    * After the script is done, edit the KubeOneCluster manifest to add the following stanza:
      ```yaml
      …
      registryConfiguration:
        overwriteRegistry: “<bastion-private-ip>:5000”
        insecureRegistry: true
      ```
   * Run `kubeone apply` as described in the tutorial
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Ensure that all pods deployed by KubeOne are using images from the registry mirror
  * All images should use `<bastion-private-ip>:5000` as the registry instead of original registries

**Comment by ahmedwaleedmalik** [comment]
Works as expected.
