### ISSUE TITLE
Release v1.4.0-rc.0 missing

### ISSUE THREAD

**Issue by exolab** [kubermatic/kubeone#1799]
It looks like there is supposed to be a release for the 1.4.0 rc, but there isn't.

https://github.com/kubermatic/kubeone/releases/tag/v1.4.0-rc.0

**Comment by kron4eg** [comment]
That's because it wasn't released yet. The tracking issue is #1763.

**Comment by xmudrii** [comment]
The v1.4.0-rc.0 release has just been released: https://github.com/kubermatic/kubeone/releases/tag/v1.4.0-rc.0
