### ISSUE TITLE
Test upgrading cluster created by KubeOne 1.3 - RHEL 8.5 -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1805]
This is a subtask of #1796 for testing upgrading RHEL 8.5 clusters created by KubeOne 1.3. The cloud provider doesn't matter for this issue.

Check #1796 for instructions.

The following upgrade paths should be tested:

* [x] 1.22.6 -> 1.23.3
* [x] 1.21.9 -> 1.22.6
* [x] 1.20.15 -> 1.21.9
* [x] 1.19.16 -> 1.20.15

**Comment by vgramer** [comment]
work as expected
