### ISSUE TITLE
Addons: function "required" not defined

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubeone#1806]
**What happened**:

The addons use a function called `required` to check whether required parameters/credentials are provided. However, this function doesn't seemto be working as intended:

```
time="09:48:41 UTC" level=warning msg="Task failed, error was: failed to load and apply the addon \"backups-restic\": failed to load and apply embedded addon: failed to template addons manifest backups-restic.yaml: template: addons-base:8: function \"required\" not defined"
```

**What is the expected behavior**:

I should see the string provided to the `required` function rather than the error above.

**How to reproduce the issue**:
Specify an embedded addon that requires some parameter or credential without providing them. For example try to install the `backups-restic` addon without specifying any parameters.

**Anything else we need to know?**

The `required` function was added in #1618 as a fix for #1555.

**Information about the environment**:
KubeOne version (`kubeone version`): 1.3.3
Operating system: alpine:3.15.0
Provider you're deploying cluster on: OpenStack
Operating system you're deploying on: Flatcar

**Comment by kron4eg** [comment]
@judge-red it was fixed in #1737
