### ISSUE TITLE
Upgrading HA cluster without API server LB is failing because Docker is restarted

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1847]
**What happened**:

Upgrading an HA cluster that doesn't use LB as an API endpoint is failing because we restart Docker which causes all containers to get terminated. In case the first node is used as an API endpoint, the cluster will be inaccessible until Kubelet detects that containers are terminated. However, that can take several minutes, which is quite long, and will also cause the upgrade process to fail/timeout.

**What is the expected behavior**:

The upgrade process works on HA clusters without an API server LB.

**How to reproduce the issue**:

* Create a cluster on some cloud provider without creating an LB
* Try to upgrade the cluster

**Information about the environment**:
KubeOne version (`kubeone version`): 1.4.0
Provider you're deploying cluster on: Azure
Operating system you're deploying on: Ubuntu

**Comment by kron4eg** [comment]
@xmudrii but can we consider a cluster "an HA cluster" if it doesn't use kubeapi loadbalancing? I think such setup violates any assumptions as we should "void a warranty".

**Comment by xmudrii** [comment]
@kron4eg This is correct, however, there are valid use cases when you might have an HA cluster without an LB (e.g. bare metal setups). I think fixing this should be relatively as easy, e.g. we can just restart kubelet after restarting Docker. containerd is not affected, since restarting containerd doesn't restart containers.
