### ISSUE TITLE
Investigate failing conformance tests (sonobuoy) on Nutanix

### ISSUE THREAD

**Issue by dermorz** [kubermatic/kubeone#1857]
**What happened**:
[During release testing for 1.4 on Nutanix](https://github.com/kubermatic/kubeone/issues/1775) some `sonobuoy` conformance tests fail for different Kubernetes versions:

1.22 and 1.23
```
Failed tests:
[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
```

1.21
```
Failed tests:
[sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Conformance]
[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
[sig-scheduling] SchedulerPreemption [Serial] validates lower priority pod preemption by critical pod [Conformance]
```

**What is the expected behavior**:
Passing all conformance tests.

**How to reproduce the issue**:
Install Kubernetes with kubeone 1.4 on Nutanix and run sonobuoy conformance tests.

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 
```
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "v1.4.0-rc.1-3-ge99b7206",
    "gitCommit": "e99b72062723d0431b0b8097964bf95d7b308021",
    "gitTreeState": "",
    "buildDate": "2022-02-14T15:05:19+01:00",
    "goVersion": "go1.17",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "43",
    "gitVersion": "v1.43.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```
Operating system: Linux
Provider you're deploying cluster on: Nutanix
Operating system you're deploying on: Ubuntu/CentOS (same test results)

**Comment by xmudrii** [comment]
We don't have access to Nutanix any longer.
/close
