### ISSUE TITLE
kubernetes version upgrade failed

### ISSUE THREAD

**Issue by dbagarozza** [kubermatic/kubeone#1865]
Hi together,

we have upgraded our kubermatic kubernetes cluster from version 1.19.3 to 1.20.14. The controlplane was updated successful to version 1.20.14, but we cant update the machine control deployment. We get this error:

time="13:23:52 UTC" level=warning msg="Task failed, error was: failed to update MachineDeployment prod-kubermatic-worker: Internal error occurred: failed calling webhook \"machine-controller.kubermatic.io-machinedeployments\": converting (v1.AdmissionReview) to (v1beta1.AdmissionReview): unknown conversion"
time="13:23:57 UTC" level=warning msg="Retrying task..."
time="13:23:57 UTC" level=info msg="Upgrade MachineDeployments..."

our worker nodes are on kubernetes version 1.19.13 and the master controlplane on 1.20.14. Kubermatic works, but we cant create new kubernetes cluster. 

Could it be that kubernetes API allows only v1 API Version and not v1beta1 ? But we have tested this on our dev stage and their works the upgrade and after that we did the update on prod stage.

**Comment by xmudrii** [comment]
@dbagarozza What KubeOne version are you using?

**Comment by dbagarozza** [comment]
@xmudrii  version 1.3.3. We updated kubeone to version 1.1.0 to 1.3.3. 

On prod stage we have now two MutatingWebhookConfiguration :

machine-controller.kubermatic.io and machinedeployments.machine-controller.kubermatic.io. Can i delete one or how can i fix this :)?

**Comment by dbagarozza** [comment]
@xmudrii  ok thanks. I need to use the force (--force ) flag at kubeone to update ?

**Comment by xmudrii** [comment]
Since you already updated Kubernetes/control plane successfully, you can just update your MachineDeployment objects manually. To do that, first get all MachineDeployments (`kubectl get -n kube-system machinedeployment`), and then edit each MachineDeployment (using `kubectl edit`). You need to edit the version field and set it to the current control plane version (e.g. 1.20.14).

**Comment by dbagarozza** [comment]
@xmudrii thanks update works now. We still have the problem that the Kube client certificates have not been renewed? Shouldn't this happen with an update? For us, it's about to expire.

**Comment by dbagarozza** [comment]
@xmudrii ok just checked with kubeadm command certificates have been renewed, only prometheus still shows it as alerting. We will look at that. Thank you for your help. Ticket can be closed :)

**Comment by xmudrii** [comment]
Thank you for reporting back. I'll keep the ticket open, so we can check about that MutatingWebhookConfiguration that should be removed.

**Comment by dbagarozza** [comment]
@xmudrii ok thanks. 

we have now after the update a strange behavior that we get from time to time a connection reset from our kubernetes cluster when we run a kubectl command.

Do you have a suggestion what it can be?

Thanks.

**Comment by xmudrii** [comment]
That indeed is a little bit strange. I recommend checking the kube-apiserver and etcd logs as a starting point. This can be caused by many things. It can also be temporary due to network or general performance issues. It might also be useful to check the resource consumption on the control plane nodes (i.e. free RAM, CPU usage, etc.).

**Comment by dbagarozza** [comment]
really strange. Resources everything looks normal and before that it worked fine. I will check the logs.

**Comment by dbagarozza** [comment]
logs from apiserver k8s cluster:

E0220 13:32:43.143250       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0220 13:32:43.144280       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout

**Comment by dbagarozza** [comment]
I see very many messages at etcd log: 

I0220 14:28:36.319700       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://etcd-1.etcd.cluster-flqvxjm8p5.svc.cluster.local.:2379  <nil> 0 <nil>}] <nil> <nil>}
I0220 14:28:36.319708       1 clientconn.go:948] ClientConn switching balancer to "pick_first"

**Comment by xmudrii** [comment]
Just to clarify -- are you seeing issues with the kube-apiserver running on the KubeOne cluster or are you seeing issues with KKP user clusters? The etcd logs you shared look like logs from one of the KKP user clusters.

**Comment by dbagarozza** [comment]
@xmudrii  Issues  with the kkp user Clusters.

**Comment by dbagarozza** [comment]
@xmudrii we have detected that the apiserver still has the old certificate and therefore alerted Prometheus. 
On the node via kubeadm is the new certificate.

**Comment by xmudrii** [comment]
@dbagarozza Can you try restarting the affected kube-apiserver pods manually (by SSH-ing to the node and using `docker stop` and `docker rm`)?

**Comment by dbagarozza** [comment]
@xmudrii We have tried that. Certificate now looks right. We get a lot timeout at user cluster:

E0221 12:15:40.951592       1 available_controller.go:508] v1beta1.metrics.k8s.io failed with: failing or missing response from https://metrics-server.cluster-9n8b6vdqfl.svc.cluster.local:443/apis/metrics.k8s.io/v1beta1: Get "https://metrics-server.cluster-9n8b6vdqfl.svc.cluster.local:443/apis/metrics.k8s.io/v1beta1": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0221 12:15:45.950402       1 available_controller.go:508] v1beta1.metrics.k8s.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io": the object has been modified; please apply your changes to the latest version and try again

**Comment by dbagarozza** [comment]
@xmudrii somehow the communication to the apiserver is very slow, as soon as we restart the apiserver it runs fast for a short time.

Maybe the apiserver or etcd has problem, but we nothing at the logs.

**Comment by dbagarozza** [comment]
@xmudrii  We see at apiserver from all customer user a lot of logs:

I0223 08:25:54.073168 1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://etcd-0.etcd.cluster-j7hj7dd9n7.svc.cluster.local.:2379 0 }] }
I0223 08:25:54.073177 1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0223 08:25:59.810019 1 client.go:360] parsed scheme: "passthrough"
I0223 08:25:59.810115 1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://etcd-1.etcd.cluster-j7hj7dd9n7.svc.cluster.local.:2379 0 }] }
I0223 08:25:59.810131 1 clientconn.go:948] ClientConn switching balancer to "pick_first"

We think that the apiserver /etcd are overloaded from this and they responds very slowly.. . We see this issue:

https://github.com/kubernetes/kubernetes/issues/98720

Do we need to update Kubermatic to use etcd version 3.5? We use kubermatic version 2.17.2.
