### ISSUE TITLE
creating a HA k8s cluster without using terraform output

### ISSUE THREAD

**Issue by jaskeerat789** [kubermatic/kubeone#1866]
I am trying to bootstrap a HA k8s cluster using kubeone. I have my control plane loadbalancer configured with the public endpoint. How do i pass this endpoint to kubeone? the examples that i have seen uses terraform and the `tf.json` from `terraform output` is passed using the `-t` flag. is there any other way?

**Comment by xmudrii** [comment]
I recommend checking out [the Creating a Kubernetes Cluster on Baremetal](https://docs.kubermatic.com/kubeone/v1.4/tutorials/creating_clusters_baremetal/). It describes how to create a cluster without using the Terraform integration.
