### ISSUE TITLE
Refactor the error handling

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1869]
**What feature would you like to be added?**

The errors returned by KubeOne don't tell where's the issue exactly and how to fix it. We need to ensure that errors are descriptive enough, so users know what failed and how to fix it. Also, we should ensure that external tools integrating with KubeOne can more easily parse the errors.

**What are use cases of the feature?**

* https://github.com/kubermatic/kubermatic/issues/8950

**Comment by kron4eg** [comment]
Sorry, there is more to commit so the issue should stay open for a while.
