### ISSUE TITLE
overwriteRegistry not working for kubeadm pod

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubeone#1886]
With the update to kubeone 1.4 on Openstack and vsphere, the registry override with 

registryConfiguration:
  overwriteRegistry: registry.example.com

is not working for all kubeadm related pods.

registry.example.com/cloud-provider-vsphere/cpi/release/manager:v1.21.1
registry.example.com/cloud-provider-vsphere/csi/ci/driver:latest
registry.example.com/cloud-provider-vsphere/csi/ci/syncer:latest
registry.example.com/flatcar-linux/flatcar-linux-update-operator:v0.8.0
registry.example.com/k8s-dns-node-cache:1.15.13
registry.example.com/kubermatic/machine-controller:v1.43.0
registry.example.com/metrics-server/metrics-server:v0.5.0
registry.example.com/sig-storage/csi-attacher:v3.3.0
registry.example.com/sig-storage/csi-node-driver-registrar:v2.3.0
registry.example.com/sig-storage/csi-provisioner:v3.0.0
registry.example.com/sig-storage/csi-resizer:v1.3.0
registry.example.com/sig-storage/livenessprobe:v2.4.0
k8s.gcr.io/coredns/coredns:v1.8.0
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/kube-apiserver:v1.21.7
k8s.gcr.io/kube-controller-manager:v1.21.7
k8s.gcr.io/kube-proxy:v1.21.7
k8s.gcr.io/kube-scheduler:v1.21.7

the same cluster with config with kubeone 1.3 is working fine.

i am already useing the new api in 1.4 (but had the same effect with the old non migrated file)
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

**Comment by xmudrii** [comment]
Already fixed by #1884.
/close
