### ISSUE TITLE
Replace github.com/pkg/errors with the Go-native error handling

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1899]
`github.com/pkg/errors` is deprecated and archived, so we should replace it with the Go-native error handling.

**Acceptance criteria:**

* Implement support for the stack frame capturing
* `github.com/pkg/errors` is replaced with the Go-native error handling

**Comment by kron4eg** [comment]
Done.

P.S.
github.com/pkg/errors are still used to capture the stacktrace for optional backtrace prints.
