### ISSUE TITLE
install.sh does not always download the latest version

### ISSUE THREAD

**Issue by kaans** [kubermatic/kubeone#1936]
**What happened**:

The script `install.sh` downloaded an older version and not the newest version (1.3.4 instead of currently 1.4.1) because the releases page lists 1.3.4 as the "latest". The version cannot be changed using the script (e.g. pass a certain version directly via parameter). This leads to non working deployments due to incompatibilities of the used kubeone.yaml with older versions.

**What is the expected behavior**:

The script `install.sh` should download the latest version, or even better accept a parameter to download a specific version.

**How to reproduce the issue**:

Execute `curl -sfL get.kubeone.io | sh` when the latest release on the github page is not the most current version.

**Anything else we need to know?**

There is a recommendation to use the same code as in the install.sh script to get the latest release in the documentation [in the documentation](https://docs.kubermatic.com/kubeone/v1.4/getting_kubeone/) inside the code snippet under "For a quick way to install the latest version of KubeOne, use the following commands:".

This might also be missleading in the (probably rare) occasions that the latest release on github is actually not the most current version.

**Information about the environment**:
KubeOne version (`kubeone version`): Desired: 1.4.1 Actual: 1.3.4
Operating system: Ubuntu
Provider you're deploying cluster on: Hetzner
Operating system you're deploying on: Ubuntu

**Comment by kron4eg** [comment]
Technically 1.3.4 is the latest release, at least on a timeline and that's what github is returning.

**Comment by kaans** [comment]
That is correct, 1.3.4 is currently the latest release. The script is created to use this version for installation. From the view point of the user of that script, I assumed that the latest version is the most current version. The script is technically fine, I guess it is rather semantics of what the "latest" release actually is. As a user, I am rather interessted in the most current version when executing that script than in any previous version which just got a minor bugfix and is now the "latest".

**Comment by kron4eg** [comment]
yeah, I understand your concern very good.

**Comment by paulwollgast** [comment]
+1 to this as this is the root cause for api compatibility issues:

Error: failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: provided apiVersion "kubeone.k8c.io/v1beta2" is not supported
