### ISSUE TITLE
OIDC groupsPrefix can't be set to an empty string

### ISSUE THREAD

**Issue by Schluggi** [kubermatic/kubeone#1940]
**What happened**:
If I set `features.openidConnect.config.groupsPrefix` to an empty string or delete the key. The default value (`oidc:`) will be used. 

**What is the expected behavior**:
I would expect that an empty string in the KubeOne config would result in an empty string in the manifest. But this is not the case. Maybe you could offer a dash (`-`) for an empty value like as for `usernamePrefix`. 

Also, I would interpret the doc string to mean that if I omit the key, it should not set a prefix.
```
# **If provided**, all groups will be prefixed with this value to prevent
# conflicts with other authentication strategies.
```

**How to reproduce the issue**:
Look at >**What happened**<

**Anything else we need to know?**
`null` does not work as well -> default used.

**Information about the environment**:
KubeOne version (`kubeone version`): 1.4.1
Operating system: Rocky Linux 8.5
Provider you're deploying cluster on: on prem
Operating system you're deploying on: Rocky Linux 8.5

**Comment by kron4eg** [comment]
@Schluggi do you want to have the setup where oidc group have no prefix?

**Comment by Schluggi** [comment]
> @Schluggi do you want to have the setup where oidc group have no prefix?

Yes. Exactly.

**Comment by kron4eg** [comment]
@Schluggi 
* What about `usernamePrefix`?
  does it also need the ability to be set empty? Asking because currently it's also defaulted as "oidc:".
* What's the use-case for having no prefix at all?

**Comment by Schluggi** [comment]
> @Schluggi
> 
>     * What about `usernamePrefix`?
>       does it also need the ability to be set empty? Asking because currently it's also defaulted as "oidc:".
> 
>     * What's the use-case for having no prefix at all?

- `usernamePrefix` already has the ability. A dash (`-`) will do this. KubeOne will write the dash into the manifest and k8s will handle this. As the [doc](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server) say "The value `-` can be used to disable all prefixing".

- We only use OIDC so we have no prefix at all.

The point is k8s allow us to set an empty string. But KubeOne doesn't. That's an issue for us. Using a prefix would work but feels more like a workaround.
