### ISSUE TITLE
Reduce number of worker nodes from 3 to 1

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1972]
Reducing the number of worker nodes doesn't affect coverage, but will allow us to save some resources.

**Comment by xmudrii** [comment]
Considering that we decided to keep the NodeConformance tests (#1956), reducing the number of worker nodes would make tests slower. On providers where we use one worker node by default, the NodeConformance tests are taking 9-10 minutes, instead of ~5 minutes on AWS where we use three worker nodes by default.

Therefore, I propose that we abandon this idea. Instead, we might even want to increase the number of worker nodes for other providers as well.

cc @kron4eg for feedback

**Comment by kron4eg** [comment]
Are we sure that this effect is not due to AWS instances being more powerful, compared to other testing instances?

**Comment by xmudrii** [comment]
This can be confirmed. I believe three nodes are giving some performance improvements since more pods can be run at the same time.
