### ISSUE TITLE
Upgrade machine-controller to 1.46 or 1.47 for the 1.4 release series

### ISSUE THREAD

**Issue by thefirstofthe300** [kubermatic/kubeone#1997]
### Description of the feature you would like to add / User story

As a cluster admin, I would like to have a version of machine-controller deployed that disables locksmithd for Flatcar instances on AWS on first boot. My team is using Flatcar Linux and have experienced issues due to locksmithd not being disabled properly. We implemented the changes needed to get locksmithd disabled but locksmithd is still enabled on first boot due to cloud-init not stopping the service after masking the service.

Would it be possible to get [this commit](https://github.com/kubermatic/kubeone/commit/fc0ed4b5e56b55b301c1235a342e7b1b14eb8a07) merged into a 1.4 release of Kubeone?

### Solution details

The above has already been implemented in machine-controller >=v1.46.

https://github.com/kubermatic/machine-controller/pull/1219

**Comment by kron4eg** [comment]
@thefirstofthe300 thank you for the contribution and letting us know such important thing is awaited. Instead of pulling the latest and greatest release in the patch-level bug-fix release of 1.4 series, we decided to resort to backporting of your machine-controller contribution (see #2001).

**Comment by ahmedwaleedmalik** [comment]
@thefirstofthe300 kubeone v1.4.2 has been released which will have the updated machine-controller. 🚀 

https://github.com/kubermatic/kubeone/releases/tag/v1.4.2

I'm closing this issue since this will be resolved by the new release. Cheers :)
