### ISSUE TITLE
Docker images are always prepulled

### ISSUE THREAD

**Issue by WeirdMachine** [kubermatic/kubeone#2014]
KubeOne always pulls docker images although containerd is defined and registryOverride option is set.

  kubeone: v1.4.1
  platform: openstack
  image: flatcar

  container-runtime: containerd
  registryOverride: "some-registry"

when creating a new cluster with "kubeone apply" we can see that the images are prepulled by kubeadm from their original (not-overridden) location.

**Comment by kron4eg** [comment]
It's not a bug it's a feature!

**Comment by holgers66** [comment]
This is a show-stopper for SVA. They need to installed KubeOne completely offline, overriding the normal registry.
