### ISSUE TITLE
kubeone v1.4.2 missing RBAC-rules for the machine-controller to list volumeattachments

### ISSUE THREAD

**Issue by kllex** [kubermatic/kubeone#2030]
### What happened?
We are running KubeONE clusters on vsphere and updated to kubeONE v1.4.2 recently. Our operating-system image is flatcar and we use it's auto-updater to keep our control-plane and worker nodes up-to-date. Yesterday a new release of flatcar was published and the updater started to update and reboot machines. After reboot the machine-controller started spewing the following errors in the log:

```bash
E0510 13:44:45.963558       1 machine_controller.go:380] Failed to reconcile machine "my-cluster-5b546677c6-7hn7n": failed to delete pods bound to volumes running on node my-cluster-5b546677c6-7hn7n: failed to check volumeAttachments deletion: error while listing volumeAttachments: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:machine-controller" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
```

Additionally the machine-controller began to spawn new nodes every few minutes filling up the cluster with machines.

After adding the missing permissions the cluster "healed itself" and removed all the excess nodes and the logs did not show errors any more. Added permissions are listed here:

```bash
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:machine-controller:read-volumeattachments
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
```

and

```bash
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-controller-read-volumeattachments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:machine-controller:read-volumeattachments
subjects:
- kind: ServiceAccount
  name: machine-controller
  namespace: kube-system
```

### Expected behavior
I expect that kubeONE v1.4.2 ships the necessary RBAC rules for the machine-controller to function properly.

### How to reproduce the issue?
1. install a kubeONE cluster with:
  * KubeOne v1.4.2
  * on provider vsphere
  * with an flatcar-linux image that is not the latest (for the flatcar-update-operator to do at least one update)
  * have at least one pod running in the cluster which has a persistent volume mounted
2. install the flatcar-linux-update-operator
3. wait for an update

### What KubeOne version are you using?

kubeONE v1.4.2

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.2",
    "gitCommit": "e1ef6466e56fb543b011239faa42e32cd712101c",
    "gitTreeState": "",
    "buildDate": "2022-04-26T11:05:53Z",
    "goVersion": "go1.17.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "43",
    "gitVersion": "v1.43.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```
</details>

### What cloud provider are you running on?

VMware vSphere

### What operating system are you running in your cluster?

Flatcar Linux

### Additional information

We have **not** witnessed this behavior on our Openstack platform so the machine-controller seems to behave differently when running on vsphere and on Openstack.

**Comment by kron4eg** [comment]
@kllex thanks for the report and solution right away!

**Comment by qeqar** [comment]
And corresponding Machine controller change https://github.com/kubermatic/machine-controller/pull/1256
