### ISSUE TITLE
Upgrade cinder-csi-plugin to >= v1.23.2

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubeone#2150]
Request from support

> we tried to activate volume-snapshots on our kubeone-installed kubernetes clusters on our Openstack provider. As the csi-snapshotter is already deployed in a sidecar with the csi-cinder-controllerplugin we just needed to install the snapshot-controller and a VolumeSnapshotClass and were ready to roll.
> This works but:
> the provided version of the cinder-csi-plugin (v1.23.0) has a bug that makes it impossible to create volume-snapshots of volumes that are "in-use" ... which renders the whole mechanism pretty useless. There is a fix for this released with v1.23.2 (see this issue for the fix: https://github.com/kubernetes/cloud-provider-openstack/pull/1832).
> 
> Could you please upgrade the cinder-csi-plugin to something >= v1.23.2 so that volume-snapshotting works with "in-use" volumes again?

This affects both KKP and Kubeone

**Comment by xmudrii** [comment]
The original PR is about to be reverted, so this issue is still relevant. See #2187 for more details.
