### ISSUE TITLE
Installer fails to download zip file on macOS

### ISSUE THREAD

**Issue by patricks** [kubermatic/kubeone#2160]
### What happened?

Since the last change of the `install.sh` the download on macOS isn't working anymore. I checked the install script and figured out that there is a new way to figure out the current kubeone version.

Old way (which works on macOS):

`curl -w '%{url_effective}' -I -L -s -S https://github.com/kubermatic/kubeone/releases/latest -o /dev/null | sed -e 's|.*/v||'`

New way (doesn't work on macOS):

`curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/kubermatic/kubeone/releases | sed -n 's/^\s*"tag_name": "v\([^"]*\)",$/\1/p'`

The new way doesn't output anything on macOS (works fine on Linux/Debian). 

I expect the different curl versions are the problem.

macOS curl:

```
curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

Linux/Debian curl:

```
curl 7.74.0 (arm-unknown-linux-gnueabihf) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

I am using the latest stable macOS version 12.4

### Expected behavior

The install.sh should install kubeone to /usr/local/bin

### How to reproduce the issue?

Run `curl -sfL get.kubeone.io | sh` on macOS.

**Comment by embik** [comment]
Looks like it's not `curl`, but `sed`. If you replace `sed` with `gsed` (assuming you have GNU versions of coreutils installed), it seems to work.

The script probably needs to be adjusted for that.

**Comment by embik** [comment]
cc @dermorz @ahmedwaleedmalik you discussed mac compatibility on the PR (#1949).
