### ISSUE TITLE
Support Ubuntu 22.04 in KubeOne

### ISSUE THREAD

**Issue by mfahlandt** [kubermatic/kubeone#2223]
Description of the feature you would like to add / User story
As Ubuntu 22.04 is the new LTS Version of Ubuntu we should also support this as an OS.

Solution details
Support Ubuntu 22.04 as OS in KubeOne

**Comment by xmudrii** [comment]
The prerequisite for this (and for KKP) is Ubuntu 22.04 support for MC and OSM. Once we have Ubuntu supported in MC and OSM, supporting it KubeOne or KKP should be simple.

**Comment by mfahlandt** [comment]
Shall i create a ticket there accordingly?

**Comment by xmudrii** [comment]
Yes, please.

**Comment by wszychta** [comment]
I also would like to see support for Ubuntu 22.04
