### ISSUE TITLE
Test cluster provisioning on Equinix Metal - Test Release KubeOne 1.5

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2239]
This is a ticket for tracking the progress of testing cluster provisioning on Equinix Metal.

Follow instructions in #2232. Equinix Metal **has** automated E2E tests.

### v1.24.3

* Containerd + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-install-containerd-external-v1.24.3`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-install-containerd-external-v1.24.3`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-install-containerd-external-v1.24.3`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-install-containerd-external-v1.24.3`
* Containerd + External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-legacy-machine-controller-containerd-external-v1.24.3`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-legacy-machine-controller-containerd-external-v1.24.3`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-legacy-machine-controller-containerd-external-v1.24.3`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-legacy-machine-controller-containerd-external-v1.24.3`

### v1.23.9

* Containerd + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-install-containerd-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-install-containerd-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-install-containerd-external-v1.23.9`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-install-containerd-external-v1.23.9`
* Containerd + External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-legacy-machine-controller-containerd-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-legacy-machine-controller-containerd-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-legacy-machine-controller-containerd-external-v1.23.9`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-legacy-machine-controller-containerd-external-v1.23.9`
* Docker + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-install-docker-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-install-docker-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-install-docker-external-v1.23.9`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-install-docker-external-v1.23.9`
* Docker + External CCM (non OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-legacy-machine-controller-docker-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-legacy-machine-controller-docker-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-legacy-machine-controller-docker-external-v1.23.9`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-legacy-machine-controller-docker-external-v1.23.9`

### v1.22.12

* Containerd + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-install-containerd-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-install-containerd-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-install-containerd-external-v1.22.12`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-install-containerd-external-v1.22.12`
* Containerd + External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-legacy-machine-controller-containerd-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-legacy-machine-controller-containerd-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-legacy-machine-controller-containerd-external-v1.22.12`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-legacy-machine-controller-containerd-external-v1.22.12`
* Docker + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-install-docker-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-install-docker-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-install-docker-external-v1.22.12`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-install-docker-external-v1.22.12`
* Docker + External CCM (non OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-equinixmetal-default-legacy-machine-controller-docker-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-equinixmetal-centos-legacy-machine-controller-docker-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-equinixmetal-rockylinux-legacy-machine-controller-docker-external-v1.22.12`
  * [x] Flatcar: `/test pull-kubeone-e2e-equinixmetal-flatcar-legacy-machine-controller-docker-external-v1.22.12`

**Comment by embik** [comment]
Equinix Metal + Flatcar + Kubernetes 1.22 (with default settings, so OSM enabled and containerd) worked fine in manual testing. The reboots caused by flatcar version updates can fail the initial `kubeone apply` though, because it takes forever on Equinix for instances to reboot.

**Comment by embik** [comment]
@xmudrii testing for Flatcar completed.
