### ISSUE TITLE
Test cluster provisioning on Hetzner - Test Release KubeOne 1.5

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2240]
This is a ticket for tracking the progress of testing cluster provisioning on Hetzner.

Follow instructions in #2232. Hetzner **has** automated E2E tests.

### v1.24.3

* Containerd + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.24.3`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-install-containerd-external-v1.24.3`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-install-containerd-external-v1.24.3`
* Containerd + External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-legacy-machine-controller-containerd-external-v1.24.3`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-legacy-machine-controller-containerd-external-v1.24.3`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-legacy-machine-controller-containerd-external-v1.24.3`

### v1.23.9

* Containerd + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-install-containerd-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-install-containerd-external-v1.23.9`
* Containerd + External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-legacy-machine-controller-containerd-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-legacy-machine-controller-containerd-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-legacy-machine-controller-containerd-external-v1.23.9`
* Docker + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-install-docker-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-install-docker-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-install-docker-external-v1.23.9`
* Docker + External CCM (non OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-legacy-machine-controller-docker-external-v1.23.9`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-legacy-machine-controller-docker-external-v1.23.9`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-legacy-machine-controller-docker-external-v1.23.9`

### v1.22.12

* Containerd + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-install-containerd-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-install-containerd-external-v1.22.12`
* Containerd + External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-legacy-machine-controller-containerd-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-legacy-machine-controller-containerd-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-legacy-machine-controller-containerd-external-v1.22.12`
* Docker + External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-install-docker-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-install-docker-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-install-docker-external-v1.22.12`
* Docker + External CCM (non OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-hetzner-default-legacy-machine-controller-docker-external-v1.22.12`
  * [x] CentOS: `/test pull-kubeone-e2e-hetzner-centos-legacy-machine-controller-docker-external-v1.22.12`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-hetzner-rockylinux-legacy-machine-controller-docker-external-v1.22.12`

**Comment by kron4eg** [comment]
Everything except rockylinux has failed.

Rockylinux worked with the change applied in the #2265 PR.
