### ISSUE TITLE
Test cluster provisioning on GCE - Test Release KubeOne 1.5

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2241]
This is a ticket for tracking the progress of testing cluster provisioning on GCE.

Follow instructions in #2232. GCE **has** automated E2E tests.

### v1.24.3

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-install-containerd-v1.24.3`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-legacy-machine-controller-containerd-v1.24.3`

### v1.23.9

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-install-containerd-v1.23.9`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-legacy-machine-controller-containerd-v1.23.9`
* Docker (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-install-docker-v1.23.9`
* Docker (non OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-legacy-machine-controller-docker-v1.23.9`

### v1.22.12

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-install-containerd-v1.22.12`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-legacy-machine-controller-containerd-v1.22.12`
* Docker (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-install-docker-v1.22.12`
* Docker (non OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-gce-default-legacy-machine-controller-docker-v1.22.12`

**Comment by kron4eg** [comment]
:heavy_check_mark:
