### ISSUE TITLE
aws-iam-authenticator

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#225]
Support new `Cluster.Features.AWSIAMAuthenticator`

* add flag `--authentication-token-webhook-config-file` to apiserver
* mount `/etc/kubernetes/aws-iam-authenticator` into apiserver

docs: https://github.com/kubernetes-sigs/aws-iam-authenticator#3-configure-your-api-server-to-talk-to-the-server

**Comment by xmudrii** [comment]
This is out of the scope
/close
