### ISSUE TITLE
Test cluster upgrading on VCD - Test Release KubeOne 1.5

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2256]
This is a ticket for tracking the progress of testing cluster upgrading on VMware Cloud Director (VCD).

Follow instructions in #2247. VCD **DOES NOT** have automated E2E tests.

Operating Systems to be tested:

* [x] Ubuntu 20.04

Upgrades (you don't need to run conformance tests for upgrade tests, only verify that pods can be scheduled):

* [x] 1.23.9 -> 1.24.3
* [x] 1.22.12 -> 1.23.9

**Comment by ahmedwaleedmalik** [comment]
Works as expected
