### ISSUE TITLE
Make KubeOne works on Windows

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#228]
related #224

**Comment by xmudrii** [comment]
I've just tested KubeOne on Windows, built on https://github.com/kubermatic/kubeone/commit/e60529df055ac34e9bf5a8e1285f443f90cdcedc and here are the results.

* Terraform was able to create the infrastructure without a problem
* KubeOne was able to read the configuration file and get Terraform state (I was using `-t .`)
  * It is not possible to use `env:SSH_AUTH_SOCKET` as it doesn't exist on Windows
  * I had to put the following in the `terraform.tfvars` file
```
ssh_public_key_file = "./key_pub"

ssh_private_key_file = "./key"

ssh_agent_socket = ""
```
* KubeOne was able to do the install steps until the `Deploying configuration files…` step

Here are the logs:
```
INFO[13:01:43 CEST] Installing prerequisites…
INFO[13:01:43 CEST] Determine operating system…                   node=142.93.110.67
INFO[13:01:43 CEST] Determine operating system…                   node=138.197.184.100
INFO[13:01:44 CEST] Determine operating system…                   node=165.227.151.215
INFO[13:01:45 CEST] Determine hostname…                           node=138.197.184.100
INFO[13:01:45 CEST] Determine hostname…                           node=142.93.110.67
INFO[13:01:45 CEST] Creating environment file…                    node=138.197.184.100
INFO[13:01:45 CEST] Creating environment file…                    node=142.93.110.67
INFO[13:01:45 CEST] Determine hostname…                           node=165.227.151.215
INFO[13:01:45 CEST] Creating environment file…                    node=165.227.151.215
INFO[13:01:45 CEST] Installing kubeadm…                           node=138.197.184.100 os=ubuntu
INFO[13:01:45 CEST] Installing kubeadm…                           node=142.93.110.67 os=ubuntu
INFO[13:01:45 CEST] Installing kubeadm…                           node=165.227.151.215 os=ubuntu
INFO[13:02:26 CEST] Deploying configuration files…                node=165.227.151.215 os=ubuntu
ERRO[13:02:27 CEST] failed to upload configuration files: + sudo mkdir -p /etc/systemd/system/kubelet.service.d/ /etc/kubernetes
+ sudo mv ./kubeone/cfg/cloud-config /etc/kubernetes/cloud-config
mv: cannot stat './kubeone/cfg/cloud-config': No such file or directory: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


sudo mkdir -p /etc/systemd/system/kubelet.service.d/ /etc/kubernetes
sudo mv ./kubeone/cfg/cloud-config /etc/kubernetes/cloud-config
sudo chown root:root /etc/kubernetes/cloud-config
sudo chmod 600 /etc/kubernetes/cloud-config
: Process exited with status 1  node=165.227.151.215
INFO[13:02:39 CEST] Deploying configuration files…                node=142.93.110.67 os=ubuntu
ERRO[13:02:40 CEST] failed to upload configuration files: + sudo mkdir -p /etc/systemd/system/kubelet.service.d/ /etc/kubernetes
+ sudo mv ./kubeone/cfg/cloud-config /etc/kubernetes/cloud-config
mv: cannot stat './kubeone/cfg/cloud-config': No such file or directory: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


sudo mkdir -p /etc/systemd/system/kubelet.service.d/ /etc/kubernetes
sudo mv ./kubeone/cfg/cloud-config /etc/kubernetes/cloud-config
sudo chown root:root /etc/kubernetes/cloud-config
sudo chmod 600 /etc/kubernetes/cloud-config
: Process exited with status 1  node=142.93.110.67
```

I used DigitalOcean for this test run.

**Comment by kron4eg** [comment]
Somehow `kubeone/cfg/cloud-config` didn't get uploaded.

**Comment by norkhairi** [comment]
Not sure if this is related or not, but what about support for adding windows nodes for scheduling windows container?

**Comment by kron4eg** [comment]
@norkhairi you're right, that's unrelated. Originally it was about launching kubeone on windows machines :)

To be honest, I don't think we can support windows worker nodes. machine-controller can do only linux machines.

**Comment by norkhairi** [comment]
> @norkhairi you're right, that's unrelated. Originally it was about launching kubeone on windows machines :)
> 
> To be honest, I don't think we can support windows worker nodes. machine-controller can do only linux machines.

@kron4eg noted, sorry and thanks for replying and correcting me. Hopefully I'm not dragging it too much further out of context, but I'm currently looking for similar tools like kubeone that supports windows nodes for cloud (without the need to utilise cloud service for permissions such as AWS IAM Roles which most of the tools out there requires).  Thanks again! :)
