### ISSUE TITLE
Installing kubeadm is failing on ubuntu 20.04

### ISSUE THREAD

**Issue by wszychta** [kubermatic/kubeone#2297]
### What happened?

When I was trying to add new control-plane to my cluster I saw this error:
```console
+ sudo DEBIAN_FRONTEND=noninteractive apt-get install --option Dpkg::Options::=--force-confold --no-install-recommends -y 'containerd.io=1.5.*'
E: Packages were downgraded and -y was used without --allow-downgrades.
```

### Expected behavior

`Installing kubeadm...` process should succeed 

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.6",
    "gitCommit": "f8f5dbc73a7b53180cc48087164828c39973f854",
    "gitTreeState": "",
    "buildDate": "2022-08-03T16:20:22Z",
    "goVersion": "go1.18.4",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "43",
    "gitVersion": "v1.43.6",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### What cloud provider are you running on?
Hetzner

### What operating system are you running in your cluster?

Ubuntu 20.04

### Additional information

After checking via SSH I can see that containerd.io package is installed, but there is upgrade avaliable for it also:
```console
apt list --upgradable
Listing... Done
containerd.io/focal 1.6.7-1 amd64 [upgradable from: 1.5.11-1]
kubeadm/kubernetes-xenial 1.24.4-00 amd64 [upgradable from: 1.22.4-00]
kubectl/kubernetes-xenial 1.24.4-00 amd64 [upgradable from: 1.22.4-00]
kubelet/kubernetes-xenial 1.24.4-00 amd64 [upgradable from: 1.22.4-00]
python3-dnspython/focal-updates 1.16.0-1ubuntu1 all [upgradable from: 1.16.0-1build1]
```
I believe that this is just a matter of adding `--allow-downgrades` to the failed command. This should fix this issue.

**Comment by xmudrii** [comment]
@wszychta The issue is that you have some packages that should be managed by KubeOne, but that aren't installed by KubeOne. Even if you get containerd working, you mostly like wouldn't be able to proceed because there are Kubernetes packages preinstalled.

KubeOne doesn't support/use containerd 1.6 currently. Since this package is preinstalled, KubeOne cannot downgrade it. `--allow-downgrades` missing is sort of expected because then we can catch such issues.

I recommend that you try to find out where those packages are coming from and if possible get rid of them. Those packages should be managed by KubeOne, otherwise, you'll run into various conflicts and errors that might affect the stability of your cluster.

**Comment by wszychta** [comment]
@xmudrii Thanks you for your answer. This host was previously used by my kubeone cluster. I needed to remove it from cluster (etcd issues) and I wanted to add it again.

Before running `kubeone apply` there are no packages related to kubernetes or containerd.io as you can see on below logs:
```console
sudo apt list --installed | grep "containerd"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

sudo apt list --installed | grep "kubernetes"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

after running `kubeone apply` I can see that packages are installed on the host:
```console
sudo apt list --installed | grep "containerd"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

containerd.io/focal,now 1.5.11-1 amd64 [installed,upgradable to: 1.6.7-1]

sudo apt list --installed | grep "kubernetes"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

cri-tools/kubernetes-xenial,now 1.24.2-00 amd64 [installed,automatic]
kubeadm/kubernetes-xenial,now 1.22.4-00 amd64 [installed,upgradable to: 1.24.4-00]
kubectl/kubernetes-xenial,now 1.22.4-00 amd64 [installed,upgradable to: 1.24.4-00]
kubelet/kubernetes-xenial,now 1.22.4-00 amd64 [installed,upgradable to: 1.24.4-00]
kubernetes-cni/kubernetes-xenial,now 0.8.7-00 amd64 [installed]
```

If you have any advice in such case please let me know. I would like to avoid recreating the host.

**Comment by wszychta** [comment]
ok, I found the reason. My other instance had 1.6.7 containerd.io and that was a reason why process was failing.
