### ISSUE TITLE
Snapshots not working w/ csi-cinder-plugin:v1.22.0 on Open Telekom Cloud

### ISSUE THREAD

**Issue by sphr2k** [kubermatic/kubeone#2412]
### What happened?

On Open Telekom Cloud (OpenStack), CSI snapshots do not work due to the `force-create` flag not being implemented in `csi-cinder-plugin:v1.22.0` . Thex bugfix was [backported](https://github.com/kubernetes/cloud-provider-openstack/pull/1813) to 1.22. It's included in `v1.22.2`.

### How to reproduce the issue?

Try to create a snapshot of a mounted volume on Open Telekom Cloud

### What KubeOne version are you using?

1.5.1 / K8s 1.22.11

### What cloud provider are you running on?

Open Telekom Cloud (OpenStack)

### What operating system are you running in your cluster?

Ubuntu 20.04

**Comment by xmudrii** [comment]
We fixed this on `main` with #2427 and we plan on cherry-picking it to the `release/v1.5` branch. In case the cherry-pick gets approved and merged, the fix should be in available in v1.5.3 which is planned for mid-November.

**Comment by xmudrii** [comment]
This is fixed in v1.5.3.
/close
