### ISSUE TITLE
Hetzner Cloud: Upgrade CSI driver to 2.0

### ISSUE THREAD

**Issue by sphr2k** [kubermatic/kubeone#2493]
### Description of the feature you would like to add / User story

As a user, I would like to be able to use Hetzner Cloud CSI driver [v2.0.0](https://github.com/hetznercloud/csi-driver/releases/tag/v2.0.0), since it includes a number of improvements over v1.6.0, which had not been updated for more than a year.

**Comment by madalinignisca** [comment]
I was reading on https://github.com/hetznercloud/csi-driver/pull/302 which is now in 2.0 and I was wondering, if I have only a basic kubeone cluster in a single region, this issue is not to be concerned when upgrade to Kubeone 1.6 will be possible, considering that hetzner csi 2.0 gets in?

**Comment by xmudrii** [comment]
@madalinignisca As far as I can tell, this issue only concerns multi-region clusters. I don't expect that this will have any effect on single-region clusters.

**Comment by apricote** [comment]
Quick note regarding the update. We currently do not recommend users to upgrade to `v2.0.0`, as there is a small bug with the topology requirements. See hetznercloud/csi-driver#333 for details.

**Comment by xmudrii** [comment]
@apricote Thank you so much for letting us know! We'll stay on v1.6.0 until the issue is not resolved.

**Comment by apricote** [comment]
We just released [v2.1.0](https://github.com/hetznercloud/csi-driver/releases/tag/v2.1.0) of the `hcloud-csi-driver`. You can upgrade to that version. Thanks for your patience.

**Comment by xmudrii** [comment]
KubeOne v1.6.0 will include Hetzner CSI v2.1.0 (see #2578).
/close
