### ISSUE TITLE
Allow overriding the containerd version

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2545]
### Description of the feature you would like to add / User story

As a cluster admin,
I would like to override the containerd version
in order to mitigate issues and regressions such as https://github.com/containerd/containerd/issues/7828

### Solution details

- Extend the KubeOneCluster API to allow specifying the containerd version. For example:
    ```
    ...
    versions:
      kubernetes: 1.25.5
      containerd: '1.6.*'
    ```
- Propagate the specified containerd version to machine-controller and operating-system-manager
  - Propagating the specified version to OSM might be a bit complicated due to the nature of OSPs. This is something that we still need to discuss.

### Additional information

- We should still enforce a compatibility matrix with this feature. Users shouldn't be allowed to override the containerd version to the next minor version (e.g. from 1.6 to 1.7) before we validate it.

**Comment by fbskp** [comment]
+1

Is it possible to upgrade to containerd 1.6.14 ASAP?
The aforementioned bug breaks a lot of deployments (basically all deployments which have memory resources set).

**Comment by xmudrii** [comment]
> Is it possible to upgrade to containerd 1.6.14 ASAP?

KubeOne is using the latest available containerd version by default, in this case, 1.16.14. For control plane and static worker nodes, you can upgrade containerd by forcing upgrade, i.e. by running `kubeone apply --force-upgrade`. For worker nodes managed by machine-controller, you can [rollout MachineDeployments as described in docs](https://docs.kubermatic.com/kubeone/v1.5/cheat-sheets/rollout-machinedeployment/).

**Comment by xmudrii** [comment]
It has been decided that KubeOne will continue managing the containerd version to avoid various risks
