### ISSUE TITLE
Create secret for external Cloud Controller Manager (CCM) if Provider.External is set to true

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#257]
We should create a secret with credentials for external CCM if provider.External is set. That would improve UX as user can just deploy the CCM and not worry about deploying credentials.

Relevant to #255

**Comment by kron4eg** [comment]
it looks like we can reference machine-controller secret from CCM deployment, as credentials are the same, so we don't need this task anymore.
