### ISSUE TITLE
Missing caBundle Volume Mount for Machine Controller WebHook 

### ISSUE THREAD

**Issue by archups** [kubermatic/kubeone#2585]
### What happened?

When trying to add machinedeployment, getting following SSL error for AUTH_URL on OpenStack k8s cluster created using kubeone even when `caBundle` is configured as part of KubeOneCluster
```Error from server: error when creating "md.yaml": admission webhook "machinedeployments.machine-controller.kubermatic.io" denied the request: failed to default machineSpec: failed to get a openstack client, due to Get "https://xx.xx.xx.xx/:xxxx/": x509: certificate signed by unknown authority```

### Expected behavior

MachineDeployment should get created since `caBundle` is configured as part of KubeOneCluster object. 

### How to reproduce the issue?

Once the k8s cluster is provisioned with kubeone on OpenStack with custom CA added as caBundle. Try to add machinedeployment to that cluster, you will encounter the error stated above. 

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "5",
    "gitVersion": "1.5.4",
    "gitCommit": "d814bd9007381d0eb06fefb4f7345a128b8f8666",
    "gitTreeState": "",
    "buildDate": "2022-12-12T09:37:23Z",
    "goVersion": "go1.19.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "54",
    "gitVersion": "v1.54.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your cluster?

Ubuntu-Focal-Fossa-20.04.3-LTS-V1.01

**Comment by kron4eg** [comment]
machine-controller-webhook addons manifest is missing `{{ caBundleVolumeMount }}` call in volumeMounts section.
