### ISSUE TITLE
Test cluster provisioning on AWS - Test Release KubeOne 1.6

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2610]
This is a ticket for tracking the progress of testing cluster provisioning on AWS. PR: #2620

### v1.26.1

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-install-containerd-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-install-containerd-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-install-containerd-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-install-containerd-v1.26.1`
  * [x] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-install-containerd-v1.26.1`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-install-containerd-v1.26.1`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-legacy-machine-controller-containerd-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-legacy-machine-controller-containerd-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-legacy-machine-controller-containerd-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-legacy-machine-controller-containerd-v1.26.1`
  * [ ] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-legacy-machine-controller-containerd-v1.26.1`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-legacy-machine-controller-containerd-v1.26.1`
* External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-install-containerd-external-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-install-containerd-external-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-install-containerd-external-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-install-containerd-external-v1.26.1`
  * [x] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-install-containerd-external-v1.26.1`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-install-containerd-external-v1.26.1`
* External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-legacy-machine-controller-containerd-external-v1.26.1`
  * [ ] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-legacy-machine-controller-containerd-external-v1.26.1`

### v1.25.6

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-install-containerd-v1.25.6`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-install-containerd-v1.25.6`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-install-containerd-v1.25.6`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-install-containerd-v1.25.6`
  * [x] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-install-containerd-v1.25.6`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-install-containerd-v1.25.6`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-legacy-machine-controller-containerd-v1.25.6`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-legacy-machine-controller-containerd-v1.25.6`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-legacy-machine-controller-containerd-v1.25.6`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-legacy-machine-controller-containerd-v1.25.6`
  * [ ] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-legacy-machine-controller-containerd-v1.25.6`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-legacy-machine-controller-containerd-v1.25.6`
* External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-install-containerd-external-v1.25.6`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-install-containerd-external-v1.25.6`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-install-containerd-external-v1.25.6`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-install-containerd-external-v1.25.6`
  * [x] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-install-containerd-external-v1.25.6`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-install-containerd-external-v1.25.6`
* External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-legacy-machine-controller-containerd-external-v1.25.6`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-legacy-machine-controller-containerd-external-v1.25.6`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-legacy-machine-controller-containerd-external-v1.25.6`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-legacy-machine-controller-containerd-external-v1.25.6`
  * [ ] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-cloud-init-legacy-machine-controller-containerd-external-v1.25.6`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-legacy-machine-controller-containerd-external-v1.25.6`

### v1.24.10

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-install-containerd-v1.24.10`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-install-containerd-v1.24.10`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-install-containerd-v1.24.10`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-install-containerd-v1.24.10`
  * [x] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-install-containerd-v1.24.10`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-install-containerd-v1.24.10`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-legacy-machine-controller-containerd-v1.24.10`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-legacy-machine-controller-containerd-v1.24.10`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-legacy-machine-controller-containerd-v1.24.10`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-legacy-machine-controller-containerd-v1.24.10`
  * [ ] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-cloud-init-legacy-machine-controller-containerd-v1.24.10`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-legacy-machine-controller-containerd-v1.24.10`
* External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-install-containerd-external-v1.24.10`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-install-containerd-external-v1.24.10`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-install-containerd-external-v1.24.10`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-install-containerd-external-v1.24.10`
  * [x] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-install-containerd-external-v1.24.10`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-install-containerd-external-v1.24.10`
* External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-aws-default-legacy-machine-controller-containerd-external-v1.24.10`
  * [x] CentOS: `/test pull-kubeone-e2e-aws-centos-legacy-machine-controller-containerd-external-v1.24.10`
  * [x] RHEL: `/test pull-kubeone-e2e-aws-rhel-legacy-machine-controller-containerd-external-v1.24.10`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-aws-rockylinux-legacy-machine-controller-containerd-external-v1.24.10`
  * [ ] Flatcar: `/test pull-kubeone-e2e-aws-flatcar-cloud-init-legacy-machine-controller-containerd-external-v1.24.10`
  * [x] Amazon Linux: `/test pull-kubeone-e2e-aws-amzn-legacy-machine-controller-containerd-external-v1.24.10`

**Comment by kron4eg** [comment]
All tests has passed, but flatcar legacy. Those fail due to AWS userdata size limit.
