### ISSUE TITLE
Test cluster provisioning on Azure - Test Release KubeOne 1.6

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2611]
This is a ticket for tracking the progress of testing cluster provisioning on Azure. PR: #2621

### v1.26.1

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-install-containerd-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-azure-centos-install-containerd-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-azure-rhel-install-containerd-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-azure-rockylinux-install-containerd-v1.26.1`
  * [x] Flatcar: `/test pull-kubeone-e2e-azure-flatcar-install-containerd-v1.26.1`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-azure-centos-legacy-machine-controller-containerd-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-azure-rhel-legacy-machine-controller-containerd-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-azure-rockylinux-legacy-machine-controller-containerd-v1.26.1`
  * [x] Flatcar: `/test pull-kubeone-e2e-azure-flatcar-legacy-machine-controller-containerd-v1.26.1`
* External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-azure-centos-install-containerd-external-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-azure-rhel-install-containerd-external-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-azure-rockylinux-install-containerd-external-v1.26.1`
  * [x] Flatcar: `/test pull-kubeone-e2e-azure-flatcar-install-containerd-external-v1.26.1`
* External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] CentOS: `/test pull-kubeone-e2e-azure-centos-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] RHEL: `/test pull-kubeone-e2e-azure-rhel-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] Rocky Linux: `/test pull-kubeone-e2e-azure-rockylinux-legacy-machine-controller-containerd-external-v1.26.1`
  * [x] Flatcar: `/test pull-kubeone-e2e-azure-flatcar-legacy-machine-controller-containerd-external-v1.26.1`

### v1.25.6

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-install-containerd-v1.25.6`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-v1.25.6`
* External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.25.6`
* External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-external-v1.25.6`

### v1.24.10

* Containerd (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-install-containerd-v1.24.10`
* Containerd (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-v1.24.10`
* External CCM (OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.24.10`
* External CCM (no OSM)
  * [x] Ubuntu: `/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-external-v1.24.10`

**Comment by kron4eg** [comment]
All tests passed.
