### ISSUE TITLE
Test cluster upgrading on AWS - Test Release KubeOne 1.6

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2651]
* [x] `/test pull-kubeone-e2e-aws-amzn-stable-upgrade-containerd-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-centos-stable-upgrade-containerd-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-default-stable-upgrade-containerd-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-flatcar-stable-upgrade-containerd-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-rhel-stable-upgrade-containerd-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-rockylinux-stable-upgrade-containerd-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-amzn-stable-upgrade-containerd-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-centos-stable-upgrade-containerd-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-default-stable-upgrade-containerd-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-flatcar-stable-upgrade-containerd-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-rhel-stable-upgrade-containerd-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-rockylinux-stable-upgrade-containerd-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-amzn-stable-upgrade-containerd-external-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-centos-stable-upgrade-containerd-external-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-default-stable-upgrade-containerd-external-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-flatcar-stable-upgrade-containerd-external-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-rhel-stable-upgrade-containerd-external-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-rockylinux-stable-upgrade-containerd-external-from-v1.24.10-to-v1.25.6`
* [x] `/test pull-kubeone-e2e-aws-amzn-stable-upgrade-containerd-external-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-centos-stable-upgrade-containerd-external-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-default-stable-upgrade-containerd-external-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-flatcar-stable-upgrade-containerd-external-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-rhel-stable-upgrade-containerd-external-from-v1.25.6-to-v1.26.1`
* [x] `/test pull-kubeone-e2e-aws-rockylinux-stable-upgrade-containerd-external-from-v1.25.6-to-v1.26.1`

**Comment by kron4eg** [comment]
all tests passed
