### ISSUE TITLE
Test optional addons - Test Release KubeOne 1.6

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2669]
This ticket is about testing the following optional addons:

- Unattended upgrades
- Backups
- cluster-autoscaler

The tests should be conducted on:

- [x] v1.26.1
- [x] v1.25.6
- [x] v1.24.10

The tests should be conducted on the following operating systems:

- [x] Ubuntu
- [x] CentOS/Rocky Linux
- [x] Flatcar

Note: we had a reported issue with the backups addon, so please pay additional attention to it: https://github.com/kubermatic/kubeone/discussions/2472

**Comment by ahmedwaleedmalik** [comment]
AWS was used for testing these cases. Cluster-autoscaler and Backups were just tested with Ubuntu since they don't depend on OS. Unattended upgrades was tested with Ubuntu, Rocky Linux, and Flatcar/

**Comment by ahmedwaleedmalik** [comment]
Should work as expected after https://github.com/kubermatic/kubeone/pull/2685
