### ISSUE TITLE
Equinix Metal: Initial machine deployment creation fails 

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubeone#2695]
### What happened?
When bootstrapping a new cluster with KubeOne on Equinix Metal, sometimes the initial machine deployment creation gets stuck with:

```
admission webhook "machinedeployments.machine-controller.kubermatic.io" denied the request: validation failed: failed to list metros: Get "https://api.equinix.com/metal/v1/locations/metros": remote error: tls: handshake failure 
```

We consider it a transient error since it happens randomly. We need to investigate a bit why this is happening and if there are any possible workarounds for this. 

### How to reproduce the issue?

Just create a cluster on Equinix Metal with `initial_machinedeployment_replicas` set to >0.

### What KubeOne version are you using?

<details>

Reproducible with Kubeone 1.5.x and 1.6.x.

</details>

**Comment by kron4eg** [comment]
Recent [e2e install tests](https://prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubeone/2851/pull-kubeone-e2e-equinixmetal-default-install-containerd-external-v1.27.3/1688875517832335360) worked
