### ISSUE TITLE
Kubernetes Upgrade fails because of CoreDNS esential addon timing out

### ISSUE THREAD

**Issue by teksuo** [kubermatic/kubeone#2710]
### What happened?

While trying to upgrade a cluster from Kubernetes 1.24.8 to 1.25.6 using Kubeone 1.6.0, the "kubeadm upgrade" command gets stuck while trying to POST the CoreDNS deployment through the API server.

First weird thing I found is, that according to the [Kubernetes 1.25 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md), CoreDNS has been bumped to v1.9.3, but the upgrade process still tries to deploy the 1.8.6 version, which is what I already have in my cluster.

I don't know whether this POST call should receive a 403/conflict response like I'm getting for the previous CoreDNS components, but instead the call is reaching the 10 seconds timeout and therefore making the command fail.

### Expected behavior

The upgrade runs through without a problem

### How to reproduce the issue?

I am executing a `kubeone apply -y -v -d -m <KUBEONE_MANIFEST> -t <TF_OUTPUT> --upgrade-machine-deployments` command from a Gitlab pipeline using the Gitlab Terraform integration for the state backend and I have used this same upgrade process since Kubernetes 1.22.

I don't have any special configuration or customization regarding CoreDNS or its ConfigMap

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "6",
    "gitVersion": "1.6.0",
    "gitCommit": "8b0973ca77856dca920798bbd5ff6b5c0f3f4856",
    "gitTreeState": "",
    "buildDate": "2023-02-23T19:25:26Z",
    "goVersion": "go1.19.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "56",
    "gitVersion": "v1.56.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
# nonk8s
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.25.6'
cloudProvider:
  hetzner: {}
  external: true
addons:
  enable: true
  path: ../../config/extra/addons
  addons:
    - name: cluster-autoscaler
    - name: unattended-upgrades
```

</details>

### What cloud provider are you running on?

Hetzner Cloud

### What operating system are you running in your cluster?

Ubuntu 22.04

### Additional information

In order to workaround this, I upgraded my cluster manually, but I had to delete the ConfigMap before running the "kubeadm upgrade" command and also use `--ignore-preflight-errors=CoreDNSUnsupportedPlugins,CoreDNSMigration`.

Apart from the described failing workflow, I also tried:
- Upgrading (with KubeOne 1.6.0) from Kubernetes 1.24.8 to 1.24.9 and 1.24.10 (Same failure)
- Upgrading (with KubeOne 1.6.0) to 1.25.6 after manually upgrading from 1.24.8 to 1.24.10 (Same failure)
- Upgrading (with KubeOne 1.6.0) to 1.26.2 after manually upgrading from 1.24.8 to 1.25.6 (Same failure)
- Upgrading (with KubeOne 1.6.0) to 1.26.2 after fresh install of 1.25.6 (SUCCESS)

**Comment by kron4eg** [comment]
@teksuo which version of kubeone has been used to deploy initial kubernetes v1.24.8?

**Comment by teksuo** [comment]
1.5.2. 

Worth saying, this happened to me only in one cluster, the other ones were upgraded successfully.

**Comment by kron4eg** [comment]
Then it looks like a transient error. Sometimes underlying infrastructure doesn't work as expected (Hetzner is cheap for a reason) and all we can do it to retry or give us. 

I don't know what to advice besides "please retry kubeone apply again".
