### ISSUE TITLE
Can't install on Debian, Baremetal

### ISSUE THREAD

**Issue by madalinignisca** [kubermatic/kubeone#2719]
### What happened?

Installing on bare metal, using Debian, will try to set docker repo with Ubuntu

### Expected behavior

Docker repo would be configured with Debian

### How to reproduce the issue?

Try to deploy on bare metal server with base debian 11 installed

### What KubeOne version are you using?

1.6.x

<details>

```console
sudo add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
...
E: The repository 'https://download.docker.com/linux/ubuntu bullseye Release' does not have a Release file.
```

### Provide your KubeOneCluster manifest here (if applicable)

```yaml
# paste manifest here
```

### What cloud provider are you running on?

baremetal

### What operating system are you running in your cluster?

Debian

**Comment by xmudrii** [comment]
Hello, @madalinignisca. Debian 11 is not supported by KubeOne. Please see the list of supported operating systems here: https://docs.kubermatic.com/kubeone/v1.6/architecture/compatibility/os-support-matrix/

**Comment by madalinignisca** [comment]
That could be added very easy, as there isn't much difference from Ubuntu (it is a Debian based distro).

Anyway, by manually controlling the repos, it installed and it is running with succes.

I'm happy that the option to have manual control over repos is there.
