### ISSUE TITLE
Support VMware vSphere

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubeone#277]
The machine-controller https://github.com/kubermatic/machine-controller/tree/master/pkg/cloudprovider/provider/vsphere already support vSphere. We could add support here as well

**Comment by kron4eg** [comment]
terraform config from PR #428 doesn't work

**Comment by pieterlange** [comment]
Happy to help test this :) (/subscribed)

**Comment by bkcsfi** [comment]
I also might be able to assist, vsphere essentials..

**Comment by kron4eg** [comment]
FYI: the code for vSphere is in place, it's just terraform config who is wrong :)

**Comment by bkcsfi** [comment]
is there an 'official' version of terraform that's being used?  Should I just move to 'latest'?

I have some experience with tf, having worked on a vsphere version of typhoon a year ago (in-house project)

**Comment by kron4eg** [comment]
Simple `terraform init` (which will download latest and grates released provider plugin) should be sufficient.

**Comment by kron4eg** [comment]
@bkcsfi that'd be awesome if you could confirm or disprove that config from #428 is correct.

I'm currently have doubts that our vSphere installation is good, but have no way to confirm this :)

**Comment by bkcsfi** [comment]
@kron4eg do you recall what exactly didn't work?  Does tf fail to provision the machines? Does it provision them, but then kubeadm fails?  etc..

**Comment by bkcsfi** [comment]
output.tf is not defined in vsphere. What was the plan for setting up master nodes w/o an infrastructure provided lb?

I'm comparing the main.tf in this PR vs what  I used with typhoon. My tf file has many more adjustments to control placement of nodes (by type) sizing disk and memory by type, etc.

would it be ok to use that version for a starting point? I know it works.  I've looked at the other output.tf examples, but I'm unsure what to use for kubeone_api output. For multi-master I suppose I would have a round-robin dns pointing to each master, and use a dns name here.. Except that could lead to certificate generation issues.

**Comment by bkcsfi** [comment]
I was able to use a slightly modified main.tf to clone a VM, however it failed on the customization step. I expected it to fail because I was cloning an old coreos image I had laying around. I will retry with a ubuntu image.

I made two changes to main.tf and variables.tf

```
diff --git a/examples/terraform/vsphere/main.tf b/examples/terraform/vsphere/main.tf
index 8d8de54..0c286a1 100644
--- a/examples/terraform/vsphere/main.tf
+++ b/examples/terraform/vsphere/main.tf
@@ -46,7 +46,7 @@ data "vsphere_virtual_machine" "template" {
 }
 
 data "vsphere_host" "host" {
-  name          = "10.2.50.3"
+  name          = "${var.vsphere_host}"
   datacenter_id = "${data.vsphere_datacenter.dc.id}"
 }
 
diff --git a/examples/terraform/vsphere/variables.tf b/examples/terraform/vsphere/variables.tf
index 2a240ce..7176d03 100644
--- a/examples/terraform/vsphere/variables.tf
+++ b/examples/terraform/vsphere/variables.tf
@@ -28,6 +28,10 @@ variable "cluster_name" {
   description = "common prefix for resources"
 }
 
+variable "vsphere_host" {
+  description = "host to place master on"
+}
+
 variable "network_name" {
   default     = "public"
   description = "network name"
```

I set 4 environment variables for VSPHERE_ (user, password, server and allow_unverified_ssl)

**Comment by kron4eg** [comment]
I wasn't able to even start the VMs, and in vcenter they all had network unplugged somehow. Will post a bit later more info.
