### ISSUE TITLE
Flatcar update not working

### ISSUE THREAD

**Issue by steled** [kubermatic/kubeone#2865]
Hi,

currently the update function for Flatcar is not working:

```shell
$ update_engine_client -check_for_update
I0814 09:44:19.416771  3378 update_engine_client.cc:251] Initiating update check and install.
W0814 09:44:19.419354  3378 update_engine_client.cc:60] Error getting dbus proxy for com.coreos.update1: GError(3): Could not get owner of name 'com.coreos.update1': no such name
I0814 09:44:19.419373  3378 update_engine_client.cc:51] Retrying to get dbus proxy. Try 2/4
W0814 09:44:29.419700  3378 update_engine_client.cc:60] Error getting dbus proxy for com.coreos.update1: GError(3): Could not get owner of name 'com.coreos.update1': no such name
```

If we update our OSP with the [Requirements](https://github.com/flatcar/flatcar-linux-update-operator#requirements) mentioned by Flatcar it works.

So there should be an update of the following lines for [osp-flatcar-cloud-init.yaml](https://github.com/kubermatic/operating-system-manager/blob/main/deploy/osps/default/osp-flatcar-cloud-init.yaml#L222-L238) and [osp-flatcar.yaml](https://github.com/kubermatic/operating-system-manager/blob/main/deploy/osps/default/osp-flatcar.yaml#L519-L535)

**Comment by ahmedwaleedmalik** [comment]
@steled transferred this issue to KubeOne repository.

**Comment by steled** [comment]
> Hey, thanks for the update. Are you facing this issue on the control plane or worker nodes for KubeOne?

We are using Flatcar only for our worker nodes.

**Comment by ahmedwaleedmalik** [comment]
We discussed this and the missing piece was enabling `unattended-upgrades` addon.
