### ISSUE TITLE
Containerd configuration is not updated after initial cluster creation

### ISSUE THREAD

**Issue by moelsayed** [kubermatic/kubeone#2915]
### What happened?
- Provisioned a cluster with custom containerd configuration.
- After provisioning, I updated the containerd configuration.
- I ran `kubeone apply`
- Configuration updates are not reflected on the nodes

### Expected behavior
- Configuration updates are reflected on the nodes when the configuration is updated.

### How to reproduce the issue?
Follow the same steps as above. 

### What KubeOne version are you using?
1.7.0

<details>

```console
$ kubeone version
# paste output here
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by xmudrii** [comment]
You need to use `--force-upgrade` option/flag to apply the configuration changes once the cluster is provisioned. Please give it a try and let us know if it worked.

**Comment by moelsayed** [comment]
Correct. Works as expected. Please excuse my n00bness :joy:. Closing this.
