### ISSUE TITLE
Joining new CP node on existing cluster fails due too updated kubeadm patch - error 100

### ISSUE THREAD

**Issue by PoudNL** [kubermatic/kubeone#3015]
### What happened?
We have a cluster with 3 CP nodes with Ubuntu 20.04 installed and Kubernetes 1.24.17. We deleted/removed one of the 3 nodes from the cluster (and from Etcd) to replace this node for a new (fresh) VM with a newer OS (Ubuntu 22.04) but with the same Kubernetes version 1.24.17.

We deployed a fresh Ubuntu 22.04 VM and ran kubeone 1.6.4 against the cluster.

When running the command ```kubeone apply -m kubeone.yaml -t tf.json``` against the running existing cluster, Kubeone supplied us with the expected result to join the new node to the existing cluster:
```
DEBU[16:21:09 CET] Hostname is detected: "containers-prod-cp-1"  node=10.90.206.21
INFO[16:21:09 CET] Determine operating system...
DEBU[16:21:09 CET] Operating system detected: "ubuntu"           node=10.90.206.22
DEBU[16:21:09 CET] Operating system detected: "ubuntu"           node=10.90.206.23
DEBU[16:21:09 CET] Operating system detected: "ubuntu"           node=10.90.206.21
INFO[16:21:09 CET] Running host probes...
INFO[16:21:10 CET] Electing cluster leader...
INFO[16:21:10 CET] Elected leader "containers-prod-cp-1"...
INFO[16:21:10 CET] Building Kubernetes clientset...
INFO[16:21:10 CET] Running cluster probes...
Host: "containers-prod-cp-1"
        Host initialized: yes
        containerd healthy: yes (1.6.27)
        docker healthy: yes (20.10.14)
        Kubelet healthy: yes (1.24.17)

        containerd is installed: yes
        containerd is running: yes
        containerd is active: yes
        containerd is restarting: no

        docker is installed: yes
        docker is running: yes
        docker is active: yes
        docker is restarting: no

        kubelet is installed: yes
        kubelet is running: yes
        kubelet is active: yes
        kubelet is restarting: no

Host: "containers-prod-cp-2"
        Host initialized: yes
        containerd healthy: yes (1.6.27)
        docker healthy: yes (20.10.14)
        Kubelet healthy: yes (1.24.17)

        containerd is installed: yes
        containerd is running: yes
        containerd is active: yes
        containerd is restarting: no

        docker is installed: yes
        docker is running: yes
        docker is active: yes
        docker is restarting: no

        kubelet is installed: yes
        kubelet is running: yes
        kubelet is active: yes
        kubelet is restarting: no

Host: "containers-prod-cp-3"
        Host initialized: no
        containerd healthy: no (unknown)
        Kubelet healthy: no (unknown)

        containerd is installed: no
        containerd is running: no
        containerd is active: no
        containerd is restarting: no

        kubelet is installed: no
        kubelet is running: no
        kubelet is active: no
        kubelet is restarting: no

The following actions will be taken:
Run with --verbose flag for more information.
        + join control plane node "containers-prod-cp-3" (10.90.206.23) using 1.24.17
        + apply embedded and custom addons defined in "./addons"
```
But when we confirm the actions, Kubeone started to run on all three CP nodes and fails on the already existing CP nodes during apt:
```
[10.90.206.21] + sudo systemctl restart containerd
[10.90.206.21] + sudo DEBIAN_FRONTEND=noninteractive apt-get install --option Dpkg::Options::=--force-confold --no-install-recommends -y 'kubelet=1.24.17-*' 'kubeadm=1.24.17-*' 'kubectl=1.24.17-*' 'kubernetes-cni=1.2.0-*' 'cri-tools=1.26.0-*'
[10.90.206.21] Reading package lists...
[10.90.206.21] Building dependency tree...
[10.90.206.21] Reading state information...
[10.90.206.21] The following packages were automatically installed and are no longer required:
[10.90.206.21]   linux-headers-5.4.0-105 linux-headers-5.4.0-105-generic
[10.90.206.21]   linux-image-5.4.0-105-generic linux-modules-5.4.0-105-generic
[10.90.206.21] Use 'sudo apt autoremove' to remove them.
[10.90.206.21] The following held packages will be changed:
[10.90.206.21]   cri-tools kubeadm kubectl kubelet kubernetes-cni
[10.90.206.21] The following packages will be upgraded:
[10.90.206.21]   cri-tools kubeadm kubectl kubelet kubernetes-cni
[10.90.206.21] E: Held packages were changed and -y was used without --allow-change-held-packages.
[10.90.206.21] 5 upgraded, 0 newly installed, 0 to remove and 129 not upgraded.
ERRO[16:22:15 CET] ssh: installing kubeadm
ssh: popen
Process exited with status 100  node=10.90.206.21
```
Currently on the existing nodes version 1.24.17-00 of kubelet/kubeadm/kubectl are installed, but the repository supplies a newer version 1.24.17-1.1. Therefor apt would like to update, but because of the ```apt-mark hold``` that is not allowed. Returning status code 100.

Kubeone won't continue and ends up in an infinite loop.
### Expected behavior
Because the existing nodes are already on 1.24.17, I expect Kubeone not to change, update or restart any services or binaries on the existing CP nodes. The only action is to prep/install the new node and join that one to the existing cluster.

### How to reproduce the issue?
Create a 2 or more CP nodes cluster with Kubeone 1.6.4 and make sure that packages 1.24.17-00 are installed, not newer!
Then install an extra Ubuntu VM and try to join that one to the existing cluster.

Now you will notice that Kubeone tries to install a newer version of kubeadm to the existing nodes. Kubeone runs the following apt command: 
```sudo DEBIAN_FRONTEND=noninteractive apt-get install --option Dpkg::Options::=--force-confold --no-install-recommends -y 'kubelet=1.24.17-*' 'kubeadm=1.24.17-*' 'kubectl=1.24.17-*' 'kubernetes-cni=1.2.0-*' 'cri-tools=1.26.0-*'``` 
Because it uses the wildcard for the last part of the package version (post release fix), which is newer than the already installed one on the existing nodes.

### What KubeOne version are you using?
Kubeone 1.6.4

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "6",
    "gitVersion": "1.6.4",
    "gitCommit": "6f9d634b0c723448f5d20486b1f42f3f092badd6",
    "gitTreeState": "",
    "buildDate": "2023-11-10T10:41:41Z",
    "goVersion": "go1.19.10",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "56",
    "gitVersion": "v1.56.4",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

### Provide your KubeOneCluster manifest here (if applicable)
```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: 1.24.17
addons:
  enable: true
  addons:
  path: ./addons
features:
  staticAuditLog:
    enable: true
    config:
      policyFilePath: audit-policy.yaml
  openidConnect: ***FILTERED***
containerRuntime:
  containerd: {}
cloudProvider:
  vsphere: {}
  external: true
  cloudConfig: ***FILTERED***
  csiConfig: ***FILTERED***
```

### What cloud provider are you running on?
VMware vSphere

### What operating system are you running in your cluster?
Ubuntu 20.04, migrating to 22.04

**Comment by PoudNL** [comment]
Eventually I manually updated the packages on the existing nodes to the newest version. This resolved the issue for me. But I still don't understand why Kubeone would try to update the packages on existing nodes that are already on the correct Kubernetes version.

**Comment by kron4eg** [comment]
There is a `kubeone apply --force-upgrade` flag to help resolve such unexpected events like appearing patch of the patch level package.
