### ISSUE TITLE
Cluster recovery lacks control-plane labeling

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#3017]
### What happened?

We have two reports when Manual cluster recover from the backup resulted to the errorous state where CP nodes were not marked as such.

more info: https://github.com/kubermatic/kubeone/discussions/3011

### Expected behavior
Ensure proper control-plane labels on the CP nodes.

### What KubeOne version are you using?

<details>

```console
$ kubeone version
# paste output here
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by xmudrii** [comment]
For 1.8.0, update documentation for manual cluster repair/recovery to mention that you need to manually label the control plane nodes. Look into a long-term fix for 1.8.x or 1.9
