### ISSUE TITLE
Test Release KubeOne 1.8 - Test Cluster Provisioning on VMware Cloud Director (VCD)

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3116]
This ticket requires **manual** testing

```[tasklist]
### VMware Cloud Director (Ubuntu)
- [ ] v1.27.11
- [ ] v1.28.7
- [ ] v1.29.2
```

**Comment by ahmedwaleedmalik** [comment]
Tested with the latest k8s patch releases and everything works as expected.

- [v1.27.13](https://github.com/kubernetes/kubernetes/releases/tag/v1.27.13) 
- [v1.28.9](https://github.com/kubernetes/kubernetes/releases/tag/v1.28.9)
- [v1.29.4](https://github.com/kubernetes/kubernetes/releases/tag/v1.29.4)

/close
