### ISSUE TITLE
Add the metrics-server to a cluster

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubeone#314]
**What feature would you like to be added?**
The [metrics-server](https://github.com/kubernetes-incubator/metrics-server) should be deployed into a new clusters.

**What are use cases of the feature?**
Having the metrics-server enabled the usage of `kubectl top [node|pod]` and the [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)

**Comment by metalmatze** [comment]
It would be nice to have this configurable so that I could turn it off, as I want to deploy a cluster-monitoring stack that includes the Prometheus Adapter. metrics-server and prometheus-adapter implement the same ApiService.
