### ISSUE TITLE
Support for Ubuntu 24.04 LTS 

### ISSUE THREAD

**Issue by archups** [kubermatic/kubeone#3161]
### Description of the feature you would like to add / User story

As a end customer, I wish to have support for  OS - Ubuntu 24.04 LTS version  
in order to be able to upgrade our existing KubeOne based cluster's VMs. 

### Solution details

- Provide support for Ubuntu 24.04 LTS as part the supported Operating systems by KubeOne

**Comment by xmudrii** [comment]
KubeOne 1.9 will come with MC and OSM that support Ubuntu 24.04. All example Terraform configs are updated to use Ubuntu 24.04 by default (which means we also test it in the CI). With that, I think this ticket is complete.
/close
