### ISSUE TITLE
Support other architectures than amd64

### ISSUE THREAD

**Issue by thz** [kubermatic/kubeone#322]
In some places in kubeone the architecture is hardcoded to amd64:

- cni-plugins download
- kubeadm,kubelet,kubectl binary-download
- apt feed-uri for docker repository (sources.list)

**Comment by xmudrii** [comment]
This feature request is blocked, as machine-controller doesn't support other architectures than `amd64`.

**Comment by thz** [comment]
Hardcoding architectures should still be avoided and fixed!

**Comment by kron4eg** [comment]
this is fixed in https://github.com/kubermatic/kubeone/pull/783
