### ISSUE TITLE
Adding support for CloudFormation

### ISSUE THREAD

**Issue by guusvw** [kubermatic/kubeone#326]
**What feature would you like to be added?**

Currently it's only possible to pre-provision the nodes via Terraform and let KubeOne use the Terraform output as input for the provisioning step. Adding support for another provisioning tools like CloudFormation would awesome.

**What are use cases of the feature?**

To provision my master nodes on AWS via CloudFormation and let KubeOne & Machine-Controller handle the rest.

**Comment by kron4eg** [comment]
@guusvw how would it looks like? Is it possible to grab output from CloudFormation?
