### ISSUE TITLE
Deploy Container Linux Update Operator

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubeone#329]
**What feature would you like to be added?**
Whenever nodes running CoreOS are deployed, we might as well deploy [CLUO](https://github.com/coreos/container-linux-update-operator) to have the cluster update automatically on new Container Linux versions.

**What are use cases of the feature?**
Use Case: Not care about updating the underlying OS but have the cluster do it on its own.

Here's a cool Grafana screenshot of CLUO running on my current cluster for 70+ days.
https://twitter.com/MetalMatze/status/1109017698900602880

![](https://pbs.twimg.com/media/D2QFMEWXQAARYca.png)

**Comment by kron4eg** [comment]
#449 will supersede this one
