### ISSUE TITLE
Please reply ASAP to retain OpenSSF Best Practices Badge

### ISSUE THREAD

**Issue by david-a-wheeler** [kubermatic/kubeone#3359]
[Kubeone has earned an OpenSSF Best Practices Badge](https://www.bestpractices.dev/en/projects/2934), but if you want to retain it, the badge needs to have an owner. It is about to not have an owner in a few days, so I'll remove its corresponding badge then unless I hear from someone that they want to take up ownership/maintenance of its badge entry.

If you're interested, *please* contact me ASAP via email at dwheeler AT linuxfoundation DOT org. Thank you so much!

**Comment by david-a-wheeler** [comment]
@kron4eg @xmudrii @mohamed-rafraf I'm guessing you're the most likely people, as you are the top 3 committers recently per the [contributors data](https://github.com/kubermatic/kubeone/graphs/contributors).

I'm sorry to give you so little notice, especially during northern hemisphere summer, but I only learned of this situation myself.

**Comment by david-a-wheeler** [comment]
Great! I look forward to it.

**Comment by xmudrii** [comment]
This has been finished. Thanks a lot @david-a-wheeler for helping us handle this!
/close
