### ISSUE TITLE
Support bastion/jump SSH host

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#337]
It's needed in order to initiate SSH connections to the instances inside "private" (without public facing IPs) subnets of a VPC.

depends on: #352

**Comment by kron4eg** [comment]
move to 0.7, to work with new API, instead of backporting changes from old to new

**Comment by xmudrii** [comment]
@kron4eg Can we add a note to the `aws-private` Terraform scripts that such setups are WIP?

**Comment by kron4eg** [comment]
`aws-private` terraform config itself is done and is not WIP, I don't want to confuse anyone with not related WIP tags on it (and remember to remove it later).

**Comment by xmudrii** [comment]
@kron4eg Terraform config is done but it's not possible to use KubeOne with such config out of box. This should be stated.

**Comment by kron4eg** [comment]
Feel free to do it as I’m not really sure what do you mean

**Comment by xmudrii** [comment]
Currently working on E2E tests
/unassign
