### ISSUE TITLE
Make audit log shipping possible

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubeone#3396]
### Description of the feature you would like to add

It's currently possible to configure "static audit logging" in KubeOne, which configures audit logging with the "log backend" in the kube-apiserver. However, the kube-apiserver pod/container is the final station of those audit logs, as there seems no sensible way to get them out of there.

There are several problems with this:
- containers are volatile, thus audit logs could be lost before the max age setting
- if someone gains access to the kube-apiserver, they can likely gain access to the container, thus wiping their own actions from the log file
- best practices and regulations mandate several additional precautions

All of which can be solved at the same time by shipping audit logs to a secure, remote and immutable server/store. However, as outlined above, the audit logs are currently not going anywhere.

Thus at least one of two things should be implemented:
- The ability to define a hostPath volume and a volumeMount for the kube-apiserver pod/container, such that the log can be written to the host (worker node) from where a different pod (with the same hostPath volume) or a local system process can ship the log
- The ability to add a sidecar container to the kube-apiserver pod as well as the ability to define and mount an emptyDir volume in the kube-apiserver container, such that a log shipper can be run in the same pod alongside the kube-apiserver

Seeing as both approaches make use of different types of volumes, maybe a generic way to add volumes and volumeMounts to the kube-apiserver pod/container would make sense. But I'll focus on a MVP here, I think.

### Solution details

The easiest but also least powerful would probably be:
- add a boolean parameter to the KubeOneCluster CRD to enable writing the audit logs to the host, and if enabled:
- mount a predictable path on the host to /var/log/kubernetes/audit.log in the kube-apiserver container

### Alternative approaches

Different possibilites, I won't go into detail for each unless requested.

- make it possible to define a single path on the host (to be used as hostPath) and a mount point in the volume (to be used in the volumeMount)
- make it possible to define a whole block to be added to the volumes in the pod spec and also to define a whole block to be added to the volumeMounts of the container spec
- additionally make it possible to define a single (sidecar) container
- or instead make it possible to add a whole block to the `containers` of the pod spec

**Comment by xmudrii** [comment]
@judge-red Do you know about the `logPath` parameter in the KubeOneCluster API (`.features.staticAuditLog.config.logPath`)? If you do, can you please at least briefly explain why it doesn't work for you?

When you set that parameter, the desired behavior is that it'll write logs on that path on the host (i.e. the control plane nodes). The mount between the control plane container and the host will be created automatically (https://github.com/kubermatic/kubeone/blob/ade51a030bdc3e5506085f2057f47477082ceae5/pkg/templates/kubeadm/v1beta4/kubeadm.go#L282-L291). By default, logs are stored at `/var/log/kubernetes/audit.log`

One important remark, any changes to that configuration requires force upgrading the cluster, i.e. `kubeone apply --force upgrade`

**Comment by xmudrii** [comment]
> So now I think policyFilePath is a path on the system where kubeone apply is executed and logPath is a path on the control plane node.

Yes, that's exactly how it works. :)
