### ISSUE TITLE
Use core as SSH user for CoreOS Container Linux

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubeone#349]
**What happened**:
Used "coreos-stable" as image.

**What is the expected behavior**:
I expect that the output for `tf.json` uses `core` as ssh_user.

**How to reproduce the issue**:
Set `droplet_image = "coreos-stable"` in `terraform.tfvars` before running `terraform apply`.
Then with `terraform output -json > tf.json` you get the output with:

```json
    ...
    "kubeone_hosts": {
        "sensitive": false,
        "type": "map",
        "value": {
            "control_plane": [
                {
                    "cloud_provider": "digitalocean",
                    "cluster_name": "kubeone",
                    "private_address": [
                        "10.10.25.25",
                        "10.10.25.26",
                        "10.10.25.27"
                    ],
                    "public_address": [
                        "142.93.142.142",
                        "142.93.142.143",
                        "142.93.142.144"
                    ],
                    "ssh_agent_socket": "env:SSH_AUTH_SOCK",
                    "ssh_port": "22",
                    "ssh_private_key_file": "",
                    "ssh_user": "root"
                }
            ]
        }
    },
```

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): master
Operating system: Arch Linux
Provider you're deploying cluster on: DigitalOcean
Operating system you're deploying on: CoreOS Container Linux

**Comment by kron4eg** [comment]
Provided terraform configurations — are only examples, you’ve more then welcome copy and modify them for your needs.

**Comment by metalmatze** [comment]
Sure. I have no problem with that. However, you also state that `Choice of Linux distributions between Ubuntu, CentOS and CoreOS` in the README. Therefore I'd say the example should at least support setting the ssh_user. I might work on a patch. :+1:

**Comment by xmudrii** [comment]
I agree that the SSH user should be sourced from Terraform variables rather than predefining it in the `output.tf`.

If you want to create a patch, I would be happy to review it. :) You just need to move `ssh_user` from [`output.tf`](https://github.com/kubermatic/kubeone/blob/master/examples/terraform/aws/output.tf#L33) to `variables.tf` and then just source it from `output.tf`. KubeOne is able to parse the `ssh_user` variable, so no other change is required.
