### ISSUE TITLE
Automate generating the changelog

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#369]
reference: https://keepachangelog.com/en/1.1.0/

* all PRs should contain changelog entry
* in release PR `[Unreleased]` would be changed to upcoming version

**Comment by kron4eg** [comment]
probably we can drop requirement for asking for `release-note` in PR message as it's useless.

**Comment by xmudrii** [comment]
I'd prefer using `release-notes` block rather than external tools, as we're already using upstream tools. This is being actively developed, but I'll follow up about that.

**Comment by kron4eg** [comment]
OK, here is bunch of obvious observations:

* `release-notes` was not used at all while kubeone existed
* creating meaningful changelog entry in the PR with original change is most simplest thing to do and doesn't require any tools

**Comment by xmudrii** [comment]
We have not used the block yet, but that doesn't mean we'll never use it. 🙂

I don't see what's the `release-block` block doing differently. It's here to be used for the changelog and release notes, but we just don't have automation to fetch notes.

**Comment by kron4eg** [comment]
I argue that making manual changes in changelog.md is superior to `release-block` for at least 2 reasons:
* the `[Unreleased]` section in changelog.md of master branch is always up-to-date and allow to see what's coming in normal way. In release process all it takes is to rename `[Unreleased]` to desired version.
* it doesn't require any tools, just add plain text in meaningful section of changelog.md

**Comment by xmudrii** [comment]
Regarding the first point, nobody holds us from doing that right now.

As of the second point, somebody must change it in the PR:
* In case it needs to be changed, they need to push a new commit which slows the pipeline
* We can't change it ourselves without author interacting (push should be possible but see the first point) 
* You don't have automation to verify it's there
* We'll not be able to potentially use tools such as release notes viewer, etc...

**Comment by kron4eg** [comment]
Cargo-culting `release-note` didn't brought us changelog to date, so maybe we need to "just" start wring it and stop waiting for abstract mechanized tools which we didn't even intended to use until now?

**Comment by xmudrii** [comment]
Have we even tried it? No. Let's first try it.

**Comment by kron4eg** [comment]
>nobody holds us from doing that right now

Writing changelog manually and generating is mutually exclusive, as generated would override manual changes.

**Comment by xmudrii** [comment]
We probably never want to have fully automated changelog. We want a tool that generates changelog and then write it manually.

For now, I'd collect all release notes and build the initial changelog. Then let's see what should we do next.

I'll explain my reasoning once I'm back from the vacation.

**Comment by xmudrii** [comment]
For v0.6.0:
* create a changelog file from the release notes

For post-v0.6.0:
* start using automation and retro on it

**Comment by xmudrii** [comment]
Created a PR.

until merged
/lifecycle active
/assign

**Comment by xmudrii** [comment]
The PR is merged and there's the `CHANGELOG.md` file in the repository's root. Unassigning myself for now.

/unassign

**Comment by xmudrii** [comment]
Punting to v0.7.0 because the v0.6.0 part is now done.

**Comment by xmudrii** [comment]
This is still relevant. We should investigate tools to automate this instead of writing the changelog by hand.
/reopen
