### ISSUE TITLE
Integrate cluster-autoscaler as addon

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#391]
based on https://github.com/kubernetes/autoscaler/pull/1866

**Comment by xmudrii** [comment]
The upstream PR is still not merged and may need additional refactoring, so this issue is currently blocked.

**Comment by kron4eg** [comment]
we need a new cluster-autoscaler release (supposedly v1.19), as there is https://github.com/kubernetes/autoscaler/pull/2934 PR that is essential to work for machine-controller
