### ISSUE TITLE
Reset doesn't remove Kubernetes binaries

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#397]
**What happened**:

`kubeone reset` doesn't remove Kubernetes binaries (kubeadm, kubelet..).

**What is the expected behavior**:

Kubernetes binaries are removed from the instances.

**How to reproduce the issue**:

Run `kubeone reset` and verify are `kubeadm` and `kubelet` installed.

**Anything else we need to know?**

This makes it impossible to install the older Kubernetes version, as the `kubelet` binary is newer.

**Comment by kron4eg** [comment]
I'd make that a reset flag, to toggle deletion of packages
