### ISSUE TITLE
Read terraform outputs directly from terraform state file (if it's accessible)

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#421]
State file is not always accessible (since state could be configured to remote), but when it does it already contains outputs and we can ready it directly. 

When state configured to some remote, old `terraform output -json` should be used.

**Comment by eqrx** [comment]
How about we define an additional flag that calls `terraform output -json` and uses the result?

**Comment by eqrx** [comment]
Or even better .... if the argument passed via `-t` is a directory, execute `terraform output -json` in there?

**Comment by kron4eg** [comment]
So, ‘-t .’ would exec?

**Comment by eqrx** [comment]
`terraform output -json` with workdir .
