### ISSUE TITLE
KubeOneCluster object: name: Invalid value: "": no cluster name specified

### ISSUE THREAD

**Issue by Kube-ASY** [kubermatic/kubeone#438]
**What happened**:
I tried to install a new KubeOne cluster with the following config:

```
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
name: demo
versions:
  kubernetes: "1.13.2"
cloudProvider:
  name: "none"
hosts:
- publicAddress: '1.2.3.4'
  privateAddress: '172.18.0.1'
  sshPort: 22 # can be left out if using the default (22)
  sshUsername: ubuntu
machineController:
  deploy: false
  provider: "none"
```

This failed with the following issue:
```
kubeone install config.yaml
Error: failed to load cluster: unable to load a given KubeOneCluster object: unable to validate the given KubeOneCluster object: name: Invalid value: "": no cluster name specified
Usage:
```

**What is the expected behavior**:
Installation proceeds.

**How to reproduce the issue**:
Specify the KubeOneCluster key 'name' in lower case.

**Anything else we need to know?**
When I use a KubeOneCluster key 'Name' in upper case like in the following config then the installation proceeds. 

```
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
Name: demo
versions:
  kubernetes: "1.13.2"
cloudProvider:
  name: "none"
hosts:
- publicAddress: '1.2.3.4'
  privateAddress: '172.18.0.1'
  sshPort: 22 # can be left out if using the default (22)
  sshUsername: ubuntu
machineController:
  deploy: false
  provider: "none"
```

```
kubeone install config.yaml
INFO[13:49:10 CEST] Installing prerequisites…
ERRO[13:49:10 CEST] failed to connect to 1.2.3.4: could not open socket "env:SSH_AUTH_SOCK": dial unix env:SSH_AUTH_SOCK: connect: no such file or directory  node=1.2.3.4
WARN[13:49:10 CEST] Task failed, retrying…
Error: failed to install prerequisites: at least one of the tasks has encountered an error
```

**Information about the environment**:
KubeOne version (`kubeone version`): 0.6.1
Operating system: CentOS Linux release 7.6.1810 (Core)
Provider you're deploying cluster on: Bare-metal
Operating system you're deploying on:CentOS Linux release 7.6.1810 (Core)

**Comment by xmudrii** [comment]
Thanks for reporting the issue! I believe this is due to the JSON tag missing on the field.

/assign
/lifecycle active
