### ISSUE TITLE
`terraform apply` fails to setup hcloud_server.lb 

### ISSUE THREAD

**Issue by kkimdev** [kubermatic/kubeone#457]
**What happened**:
Followed Hetzner install guideline https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-hetzner.md  but it fails to connect to hcloud_server.lb on `terraform apply`
```
hcloud_server.lb: Still creating... (1m20s elapsed)
hcloud_server.lb (remote-exec): Connecting to remote host via SSH...
hcloud_server.lb (remote-exec):   Host: 159.69.113.188
hcloud_server.lb (remote-exec):   User: root
hcloud_server.lb (remote-exec):   Password: false
hcloud_server.lb (remote-exec):   Private key: false
hcloud_server.lb (remote-exec):   SSH Agent: false
hcloud_server.lb (remote-exec):   Checking Host Key: false
hcloud_server.lb: Still creating... (1m30s elapsed)
hcloud_server.lb: Still creating... (1m40s elapsed)
```

**What is the expected behavior**:
`terraform apply` succeeds.

**How to reproduce the issue**:
Follow https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-hetzner.md up to `terraform apply`

**Anything else we need to know?**
I was able to fix this by adding `private_key = "${file("/root/.ssh/id_rsa")}"` line in the connection sections of `main.tf`.  I'm not familiar with Terraform and I don't know what's the conventional way of setting up this, but anyways, it will be great to document I think.

**Information about the environment**:
KubeOne version (`kubeone version`): 0.6
Operating system: Windows 10 WSL Ubuntu
Provider you're deploying cluster on: Hetzner
Operating system you're deploying on:

**Comment by kron4eg** [comment]
Hi, thanks for letting us know.

One of ether should be provided, `private_key` in terraform (and it should be unencrypted) or you encrypted SSH key should be in the ssh-agent. I'm not really sure if it's possible to use ssh-agent in `Windows 10 WSL Ubuntu`, but most likely yes, it should be accessible.

P.S.
`Windows 10 WSL Ubuntu` oh wow, didn't expected that :) 👍  Currently we testing k1 only on linux and macos.

**Comment by kron4eg** [comment]
#460 will supersede this issue.

**Comment by kron4eg** [comment]
update — we have some new docs regarding SSH requirements: https://github.com/kubermatic/kubeone/blob/master/docs/ssh.md

**Comment by FalcoSuessgott** [comment]
FYI: I was running in the same error and was able to fix this with @kkimdev  solutions and I am running on Ubuntu.
