### ISSUE TITLE
kubeone install config.yaml --tfjson tfjson fails with Hetzner

### ISSUE THREAD

**Issue by kkimdev** [kubermatic/kubeone#458]
**What happened**:
Followed https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-hetzner.md but `kubeone install config.yaml --tfjson tf.json` failed with the following error message.

```
kubeone install config.yaml --tfjson tf.json
INFO[16:47:14 DST] Installing prerequisites…
ERRO[16:47:14 DST] failed to connect to 159.69.113.188: could not open socket "env:SSH_AUTH_SOCK": dial unix env:SSH_AUTH_SOCK: connect: no such file or directory  node=159.69.113.188
ERRO[16:47:14 DST] failed to connect to 159.69.54.22: could not open socket "env:SSH_AUTH_SOCK": dial unix env:SSH_AUTH_SOCK: connect: no such file or directory  node=159.69.54.22
ERRO[16:47:14 DST] failed to connect to 159.69.55.222: could not open socket "env:SSH_AUTH_SOCK": dial unix env:SSH_AUTH_SOCK: connect: no such file or directory  node=159.69.55.222
WARN[16:47:14 DST] Task failed, retrying…
Error: failed to install prerequisites: at least one of the tasks has encountered an error
Usage:
  kubeone install <manifest> [flags]

Examples:
kubeone install mycluster.yaml -t terraformoutput.json

Flags:
  -b, --backup string   path to where the PKI backup .tar.gz file should be placed (default: location of cluster config file)
  -h, --help            help for install

Global Flags:
  -d, --debug           debug
  -t, --tfjson string   path to terraform output JSON or - for stdin
  -v, --verbose         verbose

failed to install prerequisites: at least one of the tasks has encountered an error
```

**What is the expected behavior**:
Successfully installs Kubernetes

**How to reproduce the issue**:
Follow https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-hetzner.md 

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 0.6
Operating system: Windows 10 WSL Ubuntu
Provider you're deploying cluster on: Hetzner
Operating system you're deploying on:

**Comment by kron4eg** [comment]
This issue is just about the same as #457, the issue is that there is not ssh-agent (or it doesn't know about key, e.g. `ssh-add` wasn't used to cache private key in the agent) nor private key directly provided.

**Comment by kron4eg** [comment]
#460 will supersede this issue.

**Comment by kron4eg** [comment]
update — we have some new docs regarding SSH requirements: https://github.com/kubermatic/kubeone/blob/master/docs/ssh.md

**Comment by pitos-gawsoft** [comment]
More info: https://docs.kubermatic.com/kubeone/v1.2/prerequisites/ssh/

eval `ssh-agent`
ssh-add ~/.ssh/my_cool_custom_private_key
