### ISSUE TITLE
Create AUR package for KubeOne

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#470]
To make it easy to obtain and keep KubeOne updated for Arch Linux users, we should create AUR package for KubeOne.

**Comment by eqrx** [comment]
Created a repository for that [here](https://github.com/kubermatic/aur-kubeone). Finishing my [PR](https://github.com/kubermatic/kubeone/pull/466) first since Archlinux has Terraform 0.12 in its repos

**Comment by eqrx** [comment]
Which form of documentation do we want to provide in the package? I could put the markdown files into it but I think this would be rather inconvenient. Cobra can generate man pages but we would need to implement a sub command for that afaik.

**Comment by eqrx** [comment]
Same for bash completion

**Comment by eqrx** [comment]
https://aur.archlinux.org/packages/kubeone/

Done
