### ISSUE TITLE
Provisioning a cluster fails

### ISSUE THREAD

**Issue by fwartner** [kubermatic/kubeone#475]
**What happened**:
```
kubeone install config.yaml --tfjson tf.json
Error: failed to load cluster: unable to load a given KubeOneCluster object: unable to source information about cluster from a given terraform output: failed to parse Terraform config: json: cannot unmarshal object into Go struct field .control_plane of type []terraform.controlPlane
Usage:
  kubeone install <manifest> [flags]

Examples:
kubeone install mycluster.yaml -t terraformoutput.json

Flags:
  -b, --backup string   path to where the PKI backup .tar.gz file should be placed (default: location of cluster config file)
  -h, --help            help for install

Global Flags:
  -d, --debug           debug
  -t, --tfjson string   path to terraform output JSON or - for stdin
  -v, --verbose         verbose

failed to load cluster: unable to load a given KubeOneCluster object: unable to source information about cluster from a given terraform output: failed to parse Terraform config: json: cannot unmarshal object into Go struct field .control_plane of type []terraform.controlPlane
```

**What is the expected behavior**:
Running the install process.

**How to reproduce the issue**:
Install the latest binaries for Terraform and kubeone, proceed with the needed steps according to the docs

**Anything else we need to know?**
```
Terraform v0.12.0
+ provider.hcloud v1.10.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

**Information about the environment**:
KubeOne version (`kubeone version`): dev (Installed via `go get`
Operating system: MacOS 10.14.5
Provider you're deploying cluster on: Hetzner Cloud
Operating system you're deploying on: Ubuntu 18.04

**Comment by xmudrii** [comment]
@fwartner Terraform v0.12.0 is currently not supported. Trying to source output from Terraform v0.12.0 fails because there are some changes in how Terraform handles the output. We're currently working on fixing the issue and you can follow issue #463 and PR #466 for more details.

**Comment by fwartner** [comment]
Luckily I have [tfenv](https://github.com/tfutils/tfenv) installed on my machine so I can run this right away without having to wait! :)

Anyways... Quick shoutout: Awesome work!

**Comment by eqrx** [comment]
Hey @fwartner, we now have Terraform 0.12 support for the 0.9 release that will come out around the end of the week.

Cheers Alex :)

**Comment by fwartner** [comment]
Awesome! ❤️

Mit freundlichen Grüßen,
Florian Wartner
Am 17. Juni 2019, 18:31 +0200 schrieb Alexander Sowitzki <notifications@github.com>:
