### ISSUE TITLE
Add additional sub commands for packagers

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubeone#480]
**What feature would you like to be added?**
Cobra supports automatic generation of [bash](https://github.com/spf13/cobra/blob/master/bash_completions.md) and zsh completions and [man](https://github.com/spf13/cobra/blob/master/doc/man_docs.md) pages. To use this features, additional command needs to be created.

**What are use cases of the feature?**
While not critical from the use of Kubeone, these features add to the usability and overall quality of it. Bash completions. Man pages are providing a universal method for UNIX users to view the documentation quickly while completions help user to avoid unnecessary typing and lookups when the functions of commands is already known.

**Comment by xmudrii** [comment]
+1 from my side especially for autocompletions.
