### ISSUE TITLE
GCE terraform example is not remove VPC network on destroy

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubeone#485]
**What happened**:
When destroying a setup created by the terraform example, the created VPC network is left behind undeleted.

**What is the expected behavior**:
Everything automatically created (including the VPC network) should be removed automatically as well.

**How to reproduce the issue**:
Use the GCE terraform example to create the infrastructure and destroy it afterwards.

**Anything else we need to know?**
No.

**Information about the environment**:
KubeOne version (`kubeone version`): 0.8.0
Operating system: Linux
Provider you're deploying cluster on: GCE
Operating system you're deploying on: Linux

**Comment by xmudrii** [comment]
We're still not sure is it up to KubeOne GCP example scripts or up to the Terraform/GCP provider. This could be confirmed by having a simple Terraform script to create a VPC and delete it then. This way we can verify is it up to Terraform or example scripts.

**Comment by kron4eg** [comment]
By default, created VPC also has "default route". There is even [special param](https://www.terraform.io/docs/providers/google/r/compute_network.html#delete_default_routes_on_create) in `google_compute_network` resource to delete that default route immediately upon creation. Looks like this "default route" doesn't allow terraform to get rid of VPC.

**Comment by kron4eg** [comment]
Update:

Just tried with latest terraform and GCE provider: issue is fixed. Probably it was some bug in provider.
