### ISSUE TITLE
Allow providing secrets and cloudConfig in a form of a file

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#492]
**What feature would you like to be added?**

We should consider adding a way to provide secrets (like API tokens and credentials) and CloudConfig in a form of a file that would be provided on the install time.

Example:
```
kubeone install config.yaml -t tf.json --secrets secrets.yaml
```

**What are use cases of the feature?**

* Users can choose to deploy other credentials to the cluster than those that are already in the environment
* Users can put cloudConfig which contains many secrets and credentials in another file and source it on the install time

**Comment by kron4eg** [comment]
idea 1)

Add additional API field that will be mutually exclusive with existing one.

```
cloudProvider:
  cloudConfig: ""
  cloudConfigFile: "./my_cloud_config"
```

cloudConfigFile will be pointing to the static file. It order to avoid confusion between cloudConfig string literal and file, they should be validated for mutual exclusion.

**Comment by kron4eg** [comment]
idea 2)

the values from secrets file, if it's presented, should be interpolatable to cloudConfig/cloudConfigFile to actually avoid having to specify secrets 2 times.

**Comment by kron4eg** [comment]
idea 3)

if secrets file is given, nothing from ENV credentials should be used

**Comment by xmudrii** [comment]
I'm not really sure about the idea 3 because I think we shouldn't enforce a user to put everything into a file if they don't want.

**Comment by toschneck** [comment]
requested also from a customer: https://github.com/kubermatic/customer-projects/issues/47

@xmudrii / @kron4eg we should implement it in the same way as https://github.com/kubermatic/kubermatic/issues/2336. Then we have a generic way how to manage secrets for clusters. Let me know if you need more input

**Comment by xmudrii** [comment]
/assign
/lifecycle active

I proposed a solution in #611
