### ISSUE TITLE
`make test` is not linting

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubeone#497]
**What feature would you like to be added?**
`make test` runs only test cases but does not lint the source code files.

**What are use cases of the feature?**
It would be nice to have a way to perform the testing and linting locally in one command

**Comment by kron4eg** [comment]
does `make lint test` do the trick?

**Comment by eqrx** [comment]
Mh yes, but isn't `lint` a requisite of `test`? While I could run the two targets individually, aren't they logically tasks for the same target (I want to have the code checked for errors)?

**Comment by xmudrii** [comment]
@eqrx Personally I prefer when those two targets are separate. When I run `make test` this is what I expect and if I want lint I can chain commands. For example, for E2E tests, we chain commands to run testing, linting, and building before running the E2E test. This is also important for proper error handling. For example, if you don't have `gometalinter` installed and configured, `make test` would never pass, and maybe you just want to run Go tests. Separate commands are also something you'll frequently see on other projects as well.

**Comment by eqrx** [comment]
Oh I see. Thanks for the explanation. :)
