### ISSUE TITLE
Ensure AWS credentials are handled properly

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#501]
In #623, we have added an option to source credentials from a credentials file. This works well for other providers, but for AWS can be further improved.

For AWS, there is a default file called `~/.aws/credentials`, where users can store profiles and credentials for each profile. Eventually, we should support sourcing from that file, instead of requiring users to put credentials in another file or the environment.

Besides that, AWS instances can communicate with the API without the token. If `machine-controller` is running on AWS instance, `machine-controller` should be able to obtain the permission using IAM. Currently, this is not possible because KubeOne requires credentials to be present in the form of the environment variables or credentials file.

**Comment by kron4eg** [comment]
I'd argue that we should remove code related to this. It's too magic and too implicit. People wouldn't even realize that their creds are now shared with cluster. It's not usability, it's security threat.

**Comment by kron4eg** [comment]
Besides, terraform requires ENV vars anyway.

**Comment by xmudrii** [comment]
Terraform doesn't require ENV and works with the credentials file out of the box. I'm pretty sure this has been requested earlier and if we remove, it's going to be requested again. A lot of users are using the credentials file and I'm not sure they are willing to switch to the environment variables. Regarding security threats, with the credentials file, we can easier solve that because we can allow specifying the profile, where profile would contain credentials to be deployed on the cluster.

**Comment by kron4eg** [comment]
>and works with the credentials file out of the box

true https://www.terraform.io/docs/providers/aws/index.html#shared-credentials-file

P.S.
Now I have to delete my local ~/.aws/credential and never auth again from my laptop

**Comment by kron4eg** [comment]
>we can easier solve that because we can allow specifying the profile, where profile would contain credentials to be deployed on the cluster.

In other words — a flag for choosing an AWS profile from local `~/.aws/credentials`. If that flag is not provided we should avoid reading `~/.aws/credentials`, meaning that this choice of "let kubeone use `~/.aws/credentials`" should be explicit to the user.

**Comment by kron4eg** [comment]
Sorry I didn't realized this earlier, somehow missed your
>we can easier solve that because we can allow specifying the profile, where profile would contain credentials to be deployed on the cluster.

**Comment by xmudrii** [comment]
It is up to be discussed how we want to handle AWS credentials in the future.
