### ISSUE TITLE
Add cluster repair functionality

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#530]
**What feature would you like to be added?**

We should add an option to repair the cluster if something bad happens and it stops working.

**Comment by ainmosni** [comment]
Is there any ETA on this, it would help our setup quite a bit if there was. :)

**Comment by xmudrii** [comment]
@ainmosni We are trying to get the most important parts done for v0.11. There is still no ETA when the v0.11 release will be published, but you can follow this and linked issues for more details.
