### ISSUE TITLE
Provide ansible role for Kubeone

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubeone#562]
**What feature would you like to be added?**
Add an ansible role that provides access to the features KubeOne is offering.

**What are use cases of the feature?**
People using ansible have a nicer access to KubeOne

**Comment by eqrx** [comment]
I do not see a way how to implement this in a useful matter. If we assign roles to nodes we would need to aggregate all these roles back into a configuration that is being generated for kubeone. Seems hard to implement and maintain while providing little use.

**Comment by eqrx** [comment]
Blocked by https://github.com/kubermatic/kubeone/pull/575

**Comment by sschmittsva** [comment]
FYI https://github.com/rolehippie/kubeone
