### ISSUE TITLE
vSphere: Ability to use resource pool

### ISSUE THREAD

**Issue by heikocane** [kubermatic/kubeone#594]
**What feature would you like to be added?**
When deploying to vSphere I would like to define the target resource pool so all the created virtual machines/resources are within this pool. So the VMs can be isolated from the other virtual machines.

**Comment by kron4eg** [comment]
@heikocane it's not currently possible, but I've created such feature request issue in machine-controller repository (because machine-controller handles worker machines creation of us).

xref https://github.com/kubermatic/machine-controller/issues/596

**Comment by mooperd** [comment]
+1

**Comment by xmudrii** [comment]
/reopen
We need to test are resource pools working as expected and update the Terraform example script.
