### ISSUE TITLE
Update Canal to the latest version

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#599]
**What feature would you like to be added?**

We haven't updated Canal (Calico + Flannel) for a long time and we should try to get it updated.

**What are use cases of the feature?**

The new version brings new features, such as integration with WireGuard, making Canal a CNI plugin that supports encryption.

**Comment by xmudrii** [comment]
/priority important-longterm
/lifecycle blocked

This is blocked until we don't find a strategy for updating CNI plugins

**Comment by kron4eg** [comment]
reference: https://docs.projectcalico.org/v3.8/getting-started/kubernetes/installation/flannel
