### ISSUE TITLE
kubeone install on own infrastrucre

### ISSUE THREAD

**Issue by websensei** [kubermatic/kubeone#618]
**What happened**:
`kubeone install config.yaml -t tf.json `

gives the following error

`Error: failed to load cluster: unable to load a given KubeOneCluster object: unable to set dynamic defaults for a given KubeOneCluster object: unable to fetch cloud provider credentials: no provider matched
failed to load cluster: unable to load a given KubeOneCluster object: unable to set dynamic defaults for a given KubeOneCluster object: unable to fetch cloud provider credentials: no provider matched`

**What is the expected behavior**:
trying to install it on my own infrastructure (bare-metal provider) with the following tf.json

**config.yaml**:

apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
name: demo-cluster
machineController.deploy: false
versions:
  kubernetes: 1.14.1
cloudProvider:
  name: none

*terraform output**

Outputs:

kubeone_api = {
  "endpoint" = "xxx.xxx.xxx.xxx"
}
kubeone_hosts = {
  "control_plane" = {
    "cloud_provider" = "none"
    "cluster_name" = "kubeone"
    "public_address" = [
      "yyy.yyy.yyy.yyy",
      "zzz.zzz.zzz.zzz",
    ]
    "ssh_agent_socket" = "env:SSH_AUTH_SOCK"
    "ssh_port" = 22
    "ssh_private_key_file" = "~/.ssh/deployment"
    "ssh_user" = "root"
  }
}

**tf.json**

{
  "kubeone_api": {
    "sensitive": false,
    "type": [
      "object",
      {
        "endpoint": "string"
      }
    ],
    "value": {
      "endpoint": "xxx.xxx.xxx.xxx"
    }
  },
  "kubeone_hosts": {
    "sensitive": false,
    "type": [
      "object",
      {
        "control_plane": [
          "object",
          {
            "cloud_provider": "string",
            "cluster_name": "string",
            "public_address": [
              "tuple",
              [
                "string",
                "string"
              ]
            ],
            "ssh_agent_socket": "string",
            "ssh_port": "number",
            "ssh_private_key_file": "string",
            "ssh_user": "string"
          }
        ]
      }
    ],
    "value": {
      "control_plane": {
        "cloud_provider": "none",
        "cluster_name": "kubeone",
        "public_address": [
          "yyy.yyy.yyy.yyy",
          "zzz.zzz.zzz.zzz"
        ],
        "ssh_agent_socket": "env:SSH_AUTH_SOCK",
        "ssh_port": 22,
        "ssh_private_key_file": "~/.ssh/deployment",
        "ssh_user": "root"
      }
    }
  }
}

**Information about the environment**:
KubeOne version (`kubeone version`):  "0.10.0-alpha.0",
Terraform version: v0.12.6
Operating system: Ubuntu 18.04
Provider you're deploying cluster on: Cherryservers
Operating system you're deploying on: 18.04

**Comment by kron4eg** [comment]
should be

```yaml
machineController:
  deploy: false
```

instead of 
```yaml
machineController.deploy: false
```

**Comment by websensei** [comment]
cheers!
