### ISSUE TITLE
Support Debian

### ISSUE THREAD

**Issue by varac** [kubermatic/kubeone#640]
**What feature would you like to be added?**

Please support Debian stable (version 10, aka "buster").

**What are use cases of the feature?**

Debian is very popular on servers. It would be nice if I could stay with debian and not move to Ubuntu on my servers just for kubeone. Thanks!

**Comment by xmudrii** [comment]
As far as I know, KubeOne should work on Debian too, but we haven't tested it at all. If you're using our Terraform examples, you only need to change the operating system image to Debian one and KubeOne should work out of the box.

However, [machine-controller](https://github.com/kubermatic/machine-controller), the component that creates and manages worker nodes, isn't supporting Debian, so you would have to use a [supported OS](https://github.com/kubermatic/machine-controller/blob/master/docs/operating-system.md) or manage workers manually.

**Comment by xmudrii** [comment]
KubeOne should be able to use Debian out of the box, so I'm going to close this issue.
/close
