### ISSUE TITLE
Add config option for ssh user for bastion host

### ISSUE THREAD

**Issue by thz** [kubermatic/kubeone#644]
Currently the support for bastion hosts (ssh jumphost) only allows specification of a hostname and a port number. In case the username on your bastion does not match exactly the username used on the worker nodes, you simply cannot use a bastion host.

It should be possible to specify a username for bastion-host authentication.

**Comment by kron4eg** [comment]
Fixed in https://github.com/kubermatic/kubeone/pull/651
