### ISSUE TITLE
`kubeone reset` does not clear proxy-env

### ISSUE THREAD

**Issue by thz** [kubermatic/kubeone#648]
`kubeone reset` does not reset the /etc/kubeone/proxy-env file.

**Comment by kron4eg** [comment]
`kubeone reset` was never intended to bring machine to pristine state as we are not ansible. If we look at `kubeone reset` as a way to prepare your cluster for consequent `kubeone install` (for whatever reason), then such behavior is perfectly good.

**Comment by thz** [comment]
I saw a certain risk that a consequent `kubeone install` might possibly _not_ set proxy details (because that time not configured) and a previous proxy-env file still lying around. In that case it might happen to still have an effect (because it was added somewhere to be sourced or used as an EnvironmentFile in a systemd unit).

I am aware that, we are currently:
* rewriting the file (to empty content) when no proxy is configured
* there is no preserved reference to the file anywhere

But things change and people make mistakes. So I was comparing effort with gain and saw a deletion of that created file as trivial compared to the hypothetical issues from it. It is also the cleaner approach.

**Comment by xmudrii** [comment]
I'll reopen the issue and move it to the v0.11 milestone. The problem is that the purpose of `kubeone reset` is not really clear and we should either redefine or document it. Because of that, I'm going to reopen this issue, so we can track this problem.

/reopen
