### ISSUE TITLE
Add hook support

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubeone#652]
**What feature would you like to be added?**
Allow a directory (eg. `hooks.d`) to be added on the operators host. It contains scripts that are run at different stages of the Kubeone execution.

**What are use cases of the feature?**
Infrastructure setups at customers sometimes (often) require workarounds for quirks, that can't be accounted for in a generic way. This feature enables us to use KubeOne without modifying it.

**Comment by xmudrii** [comment]
@eqrx I have some questions regarding this issue. First, should those hooks be run client-side or server-side? For example, do we want to upload scripts from `hooks.d` on all instances and run them using SSH, or we want to run those scripts on the host? If we run scripts on the instances, should we run scripts on all instances or only on a subset of instances? Can we run scripts in parallel? Finally, in what stages we should support hooks? For example, do we want to support them after installing packages, before running `kubeadm`? Can you provide some examples of how you would use hooks?

**Comment by kron4eg** [comment]
In addition here is couple of terraform "hooks":
* https://www.terraform.io/docs/provisioners/file.html
* https://www.terraform.io/docs/provisioners/local-exec.html
* https://www.terraform.io/docs/provisioners/remote-exec.html
* https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations

Will those be sufficient to cover your needs?
