### ISSUE TITLE
Conformance certify KubeOne for Kubernetes 1.16

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#658]
Kubernetes 1.16 is going out on Wednesday, Sept 18th, so we should run conformance tests and submit results for certification.

Action items:

* [ ] Run conformance tests for Kubernetes 1.16
* [ ] Submit conformance results once 1.16 is out
* [x] Create E2E tests job for 1.16 conformance tests
* [x] Ensure the testing image has conformance tests for 1.16

/priority critical-urgent
because this is release-blocking

**Comment by xmudrii** [comment]
This is blocked until we don't release v0.10.0.

**Comment by kron4eg** [comment]
done https://github.com/cncf/k8s-conformance/pull/745
