### ISSUE TITLE
Add ability to remove non-working etcd member from the cluster

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#700]
**User Story**

Related to the cluster repair functionality (#530).

Before being able to join another node to the etcd cluster, the etcd node that is not working must be removed from the cluster. 

**Acceptance criteria**

There is functionality that takes or finds a non-working etcd member and removes it. 

**Implementation**

There are at least two possible approaches:

* We can exec into the etcd pod and run the appropriate `etcdctl` commands to discover a non-working member and then remove it from the cluster.
  * The problem with this approach is that exec returns terminal output as the output. We would have to parse it, but parsing might be unreliable and hard to accomplish.
* Create SSH tunnel and use it to connect to the `etcd` API.
  * With this way we can use the API endpoints to communicate with `etcd`, discover the non-working node, and then remove it. This gives us more flexibility and it's easier to parse the output.

**Comment by kron4eg** [comment]
https://github.com/etcd-io/etcd/blob/master/Documentation/v2/members_api.md
