### ISSUE TITLE
Add ability to replace control plane node with a new node

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#701]
**User Story**

If something happens to a control plane node, there should be a functionality that allows the operator to replace it with a new one.

**Acceptance criteria**

There is replace control plane node command/functionality.

**Implementation**

The workflow for this command would be:

* The operator creates a new node using their preferred approach, for example, Terraform
* The operator updates the KubeOne configuration file to drop a node that is to be replaced and add a new node (this is not required for operators using the Terraform integration)
* KubeOne ensures the cluster is healthy
* KubeOne removes the old node from the Kubernetes and etcd clusters
* KubeOne installs Kubernetes on the new node and joins it a cluster

To find out what node should be removed from the cluster, we can compare the KubeOne configuration to the `kubeadm` ConfigMap in the `kube-system` namespace.

**Comment by kron4eg** [comment]
It was documented how to proceed in such case in https://github.com/kubermatic/kubeone/pull/794
