### ISSUE TITLE
failed to validate ssh connection options

### ISSUE THREAD

**Issue by yalrowys1234** [kubermatic/kubeone#733]
Dear i have issue when i run command kubeone install config.yaml --tfjson tf.json i got this error:
 failed to connect to : failed to validate ssh connection options: failed to read keyfile "~/.ssh/id_rsa": open ~/.ssh/id_rsa: no such file or directory 

how can i fix it

this issue happend in aws ubuntu

i finished terraform part

**Comment by kron4eg** [comment]
@yalrowys1234 please read this https://github.com/kubermatic/kubeone/blob/master/docs/ssh.md
we have there explained everything regarding SSH and kubeone.

**Comment by cmoone** [comment]
@kron4eg I've properly set up ssh-agent and I'm still getting this error:

$ssh-add ~/.ssh/id_rsa.pem
Enter passphrase for ~/.ssh/id_rsa.pem:
Identity added: ~.ssh/id_rsa.pem
$kubeone install config.yaml --tfjson .
INFO[10:16:32 EST] Installing prerequisites…
ERRO[10:16:32 EST] failed to connect to 10.0.1.48: failed to validate ssh connection options: failed to read keyfile "~/.ssh/id_rsa.pem": open ~/.ssh/id_rsa.pem: no such file or directory  node=10.0.1.48
ERRO[10:16:32 EST] failed to connect to 10.0.2.139: failed to validate ssh connection options: failed to read keyfile "~/.ssh/id_rsa.pem": open ~/.ssh/id_rsa.pem: no such file or directory  node=10.0.2.139
ERRO[10:16:32 EST] failed to connect to 10.0.4.75: failed to validate ssh connection options: failed to read keyfile "~/.ssh/id_rsa.pem": open ~/.ssh/id_rsa.pem: no such file or directory  node=10.0.4.75
WARN[10:16:32 EST] Task failed…
Error: failed to install prerequisites: at least one of the tasks has encountered an error
failed to install prerequisites: at least one of the tasks has encountered an error

**Comment by kron4eg** [comment]
Since this is resolved, I'll close it.
