### ISSUE TITLE
Use strict config unmarshaling

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#759]
**What feature would you like to be added?**
Kubeone config should be unmarshaled from the file using strict mode: unexpected fields should cause an error and be reported to the user.

**What are use cases of the feature?**
Sometimes people mistype, this will help to detect problem very early and provide immediate feedback.

**Comment by kron4eg** [comment]
reference: https://pkg.go.dev/sigs.k8s.io/yaml?tab=doc#UnmarshalStrict

**Comment by kron4eg** [comment]
Actually it's already implemented: https://github.com/kubermatic/kubeone/blob/bec424b09d2d0cb5d97347469c947ab66c5c1d91/pkg/cmd/config.go#L202

**Comment by xmudrii** [comment]
This is only for `kubeone config print` and not for `kubeone install` or `kubeone upgrade`.
/reopen
