### ISSUE TITLE
Set external IP address for Kubeconfig

### ISSUE THREAD

**Issue by mooperd** [kubermatic/kubeone#761]
We will be exposing the K8s API via a virtual IP address / port forwarding. Is there some way of setting this virtual IP address when the certificate is being generated for the kubeconfig?

**Comment by kron4eg** [comment]
There is section in manifest:

```
apiEndpoint:
  host: '<VIRTUAL_IP or FQDN>'
```

so this `apiEndpoint.host` should be your virtual IP (or FQDN). If you are using terraform then kubeone_api output can be used. Information from this output will be sourced to the same `apiEndpoint.host`.

```
output "kubeone_api" {
  description = "kube-apiserver LB endpoint"

  value = {
    endpoint = "<VIRTUAL_IP or FQDN>"
  }
}
```

**Comment by kron4eg** [comment]
on cluster initialization `apiEndpoint.host` value will be used as one of SANs in certificated generated.

**Comment by shibumi** [comment]
@kron4eg Is it possible to set this variable after cluster initialization? I try to setup https://github.com/immanuelfodor/kube-karp for my cluster initialized via kubeone.

**Comment by kron4eg** [comment]
@shibumi It's possible to do it manually, but it's very error probe and probably will kill your cluster so I definitely don't recommend doing "kubeapi endpoint switch" on a live cluster, at least if it's somehow dear to you 😂

**Comment by kron4eg** [comment]
But the kube-karp can still be used for loadbalancing your normal in-cluster workloads.

**Comment by shibumi** [comment]
@kron4eg for my in-cluster workloads I  already use metallb. My main problem is that everytime when I try to deploy prometheus operator via Helm the control node stops responding. Then the prometheus-operator helm deployment will time out.. and then it will start working again. I am not sure if this is loadbalancer related or not. 

I tried installing kube-karp + chaning the certificate SANs explained here: https://blog.scottlowe.org/2019/07/30/adding-a-name-to-kubernetes-api-server-certificate/

But looks like this doesn't work either. Now I have the problem that I have a cluster with running workloads, but an awful kube API endpoint ;(

I know, there is a big fat warning on the kubeone documentation, but I thought it's possible to add a loadbalancer for the kubeAPI endpoint after the cluster installation.
