### ISSUE TITLE
Dynamic kubelet config support 

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#768]
**What feature would you like to be added?**

**What are use cases of the feature?**

**Comment by youssefazrak** [comment]
@kron4eg is this still in the pipeline?

**Comment by xmudrii** [comment]
@youssefazrak @kron4eg There are some discussions on deprecating this feature (https://github.com/kubernetes/enhancements/issues/281#issuecomment-692241654), so I don't think we should proceed until it's not clear is it going to be deprecated.

**Comment by youssefazrak** [comment]
@xmudrii cheers, thanks for the link. In this case, I will proceed and close it.
