### ISSUE TITLE
Add kube-proxy metrics support

### ISSUE THREAD

**Issue by DOboznyi** [kubermatic/kubeone#776]
**What feature would you like to be added?**
Open kube-proxy metrics on port 10249. [Configmap](https://github.com/helm/charts/tree/master/stable/prometheus-operator#kubeproxy) in stable helm chart of prometheus-operator.
**What are use cases of the feature?**
For collecting kube-proxy metrics using prometheus operator.

**Comment by youssefazrak** [comment]
@DOboznyi There is no near plan to introduce this feature. 
You can simply edit the configmap and restart the kube-proxy.
I will proceed and close this one.
