### ISSUE TITLE
v0.11.0-beta.3 kubeone install times out due to bastion host being on a subnet with VPC route to NAT vs IGW

### ISSUE THREAD

**Issue by cmoone** [kubermatic/kubeone#798]
**What happened**:
What happened: In a brand new VPC, with one default/main Public Subnet and one default/main Private subnet, each with no tags. When I run terraform apply, and after all infrastructure is provisioned including newly tagged subnets and routes, I run 'kubeone install config.yaml --tfjson .', and see the following timeouts:

Cortlands-MacBook-Pro:aws cmoone$ kubeone install config.yaml --tfjson .
INFO[14:41:46 EST] Installing prerequisites…
ERRO[14:41:56 EST] failed to connect to 10.0.124.129: could not establish connection to 18.253.127.179:22: dial tcp 18.253.127.179:22: i/o timeout  node=10.0.124.129
ERRO[14:42:06 EST] failed to connect to 10.0.123.185: could not establish connection to 18.253.127.179:22: dial tcp 18.253.127.179:22: i/o timeout  node=10.0.123.185
ERRO[14:42:16 EST] failed to connect to 10.0.122.26: could not establish connection to 18.253.127.179:22: dial tcp 18.253.127.179:22: i/o timeout  node=10.0.122.26
WARN[14:42:16 EST] Task failed…
Error: failed to install prerequisites: at least one of the tasks has encountered an error
failed to install prerequisites: at least one of the tasks has encountered an error

**What is the expected behavior**:  Kubeone will configure the cluster and kick off the creation of workers. 

**How to reproduce the issue**: Using v0.11.0-beta.3, attempt to run 'kubeone install config.yaml --tfjson .' on a control plane after running `terraform apply`. Examine the route on the Bastion host subnet. 

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): v0.11.0-beta.3
Operating system: MacOS
Provider you're deploying cluster on: AWS
Operating system you're deploying on: Ubuntu

**Comment by kron4eg** [comment]
This was fixed long ago by using private addresses if accessible.
