### ISSUE TITLE
[vSphere] Update machine-controller version to include datastore cluster support

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubeone#805]
This issue is to bump machine-controller version used in kubeone to at least [v1.10.2](https://github.com/kubermatic/machine-controller/tree/v1.10.2) in order to have datastore cluster support for vSphere provider.

**Comment by xmudrii** [comment]
/reopen
Will keep this issue open until we don't cherry-pick the PR to the `release/v0.11` branch.
