### ISSUE TITLE
[vSphere] Workspace folders

### ISSUE THREAD

**Issue by waiyanwh** [kubermatic/kubeone#807]
**vSpherer cloud-config [workspace] error**:

**Kubelet service in controlplane nodes can't start coz of one config missing**:

**Information about the environment**:
KubeOne version (`kubeone version`):  0.10.0
Operating system: ubuntu
Provider you're deploying cluster on: vSphere
Operating system you're deploying on: ubuntu

**Comment by kron4eg** [comment]
@waiyanwh what was the error?

**Comment by waiyanwh** [comment]
The error was , if I don't define folder in Workspace tab of config.yaml, the kubelet service of worker nodes are exited with exit code 255.

**Comment by xmudrii** [comment]
This is an expected error because the Kubernetes in-tree cloud controller for vSphere requires the workspace folder to be set. You can check out https://github.com/kubermatic/kubeone/issues/740#issuecomment-559868216 for more details regarding this issue.

**Comment by waiyanwh** [comment]
Thanks.
