### ISSUE TITLE
Thin Provisioning of worker nodes nodes with vsphere machine deployment

### ISSUE THREAD

**Issue by mooperd** [kubermatic/kubeone#812]
Hi,

Is it possible to set nodes to be thin provisioned from vsphere machinedeployments? At the moment they are thick which is quite a waste of resource.

Cheers,

Andrew

**Comment by kron4eg** [comment]
Hello!

If you are referring to control-plane nodes — then it's up to your local terraform config. If case if you're talking about worker nodes, then I'm afraid it's not possible (at least without someone's contribution). Here's API definition that will be used for vSphere: https://github.com/kubermatic/machine-controller/blob/faae85e142a037d5df9fdf0ae1a0823941e2044e/pkg/cloudprovider/provider/vsphere/provider.go#L60-L76

**Comment by mooperd** [comment]
Yes - it is the control plane nodes that I would like to thin provision. 

Sadly the code is not commented and is already quite complex - would be quite difficult for anyone else to add anything unless they are already experienced in the codebase.

Could you add this as a feature request?

**Comment by kron4eg** [comment]
For control-plane nodes it totally depends on your terraform config. You can find some info in https://github.com/kubermatic/kubeone/blob/7b151d139651eb2dd5a1c3ce90384ca7d4b039ff/examples/terraform/vsphere/main.tf#L66 and more docs on this topic here: https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html

**Comment by mooperd** [comment]
Sorry! I mean machinedeployment nodes!

**Comment by kron4eg** [comment]
@mooperd this issue should be discussed in https://github.com/kubermatic/machine-controller as machine-controller is responsible for worker nodes. But at the moment it's not supported.
