### ISSUE TITLE
kubeone provisioning to vSphere hangs on Joining control plane node

### ISSUE THREAD

**Issue by 2vcps** [kubermatic/kubeone#813]
**What happened**:
Following the vSphere quickstart.

$kubeone install config.yaml -t tf.json
output hangs on:
WARN[09:37:05 PST] Task failed…
WARN[09:37:10 PST] Retrying task…
INFO[09:37:10 PST] Initializing Kubernetes on leader…
INFO[09:37:10 PST] Running kubeadm…                              node=x.x.x.209
INFO[09:37:10 PST] Joining controlplane node…
INFO[09:37:10 PST] Waiting 30s to ensure main control plane components are up…  node=x.x.x.210
INFO[09:37:40 PST] Joining control plane node                    node=x.x.x.210
WARN[09:42:40 PST] Task failed…
WARN[09:42:45 PST] Retrying task…
INFO[09:42:45 PST] Joining controlplane node…
INFO[09:42:45 PST] Waiting 30s to ensure main control plane components are up…  node=x.x.x.210
INFO[09:43:15 PST] Joining control plane node                    node=x.x.x.210

logs of that node:
Mar  3 17:41:55 demo-cp-2 kubelet[6403]: F0303 17:41:55.913196    6403 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Mar  3 17:41:55 demo-cp-2 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Mar  3 17:41:55 demo-cp-2 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar  3 17:42:06 demo-cp-2 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Mar  3 17:42:06 demo-cp-2 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 49.
Mar  3 17:42:06 demo-cp-2 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Mar  3 17:42:06 demo-cp-2 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Mar  3 17:42:06 demo-cp-2 kubelet[6434]: F0303 17:42:06.147426    6434 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Mar  3 17:42:06 demo-cp-2 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Mar  3 17:42:06 demo-cp-2 systemd[1]: kubelet.service: Failed with result 'exit-code'.
^C

I check and the directory /var/lib/kubelet is never created.

**What is the expected behavior**:
Cluster finishes installing

**How to reproduce the issue**:
Can't do anything but get this error.

**Anything else we need to know?**
I think I have fixed this in the past, I can't find how.

**Information about the environment**:
KubeOne version (`kubeone version`): 
"kubeone": {
    "major": "0",
    "minor": "11",
    "gitVersion": "0.11.0-beta.3",
    "gitCommit": "3746055da2dfa0a747691927dffa9a66db54fd18",
    "gitTreeState": "",
    "buildDate": "2019-12-20T13:10:14Z",
    "goVersion": "go1.13.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "8",
    "gitVersion": "v1.8.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}

Operating system: 
Ubuntu 18.04
Provider you're deploying cluster on:
vSphere with Terraform

Operating system you're deploying on:
Ubuntu 18.04

**Comment by 2vcps** [comment]
After about 15 minutes I get this error:
WARN[09:53:56 PST] Task failed…
Error: unable to join other masters a cluster: + export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin:/usr/local/bin:/opt/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin:/usr/local/bin:/opt/bin
+ [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm join --config=./kubeone/cfg/master_1.yaml
error execution phase preflight: couldn't validate the identity of the API Server: abort connecting to API servers after timeout of 5m0s
To see the stack trace of this error execute with --v=5 or higher: failed to exec command: set -xeu pipefail

export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"


if [[ -f /etc/kubernetes/admin.conf ]]; then exit 0; fi

sudo kubeadm join  \
	--config=./kubeone/cfg/master_1.yaml
: Process exited with status 1
unable to join other masters a cluster: + export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin:/usr/local/bin:/opt/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin:/usr/local/bin:/opt/bin
+ [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm join --config=./kubeone/cfg/master_1.yaml
error execution phase preflight: couldn't validate the identity of the API Server: abort connecting to API servers after timeout of 5m0s
To see the stack trace of this error execute with --v=5 or higher: failed to exec command: set -xeu pipefail

export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"


if [[ -f /etc/kubernetes/admin.conf ]]; then exit 0; fi

sudo kubeadm join  \
	--config=./kubeone/cfg/master_1.yaml
: Process exited with status 1

**Comment by 2vcps** [comment]
More info:
ubuntu@demo-cp-2:~$ sudo kubeadm join --config=./kubeone/cfg/master_1.yaml --v=5
I0303 18:03:51.977482   10950 join.go:363] [preflight] found NodeName empty; using OS hostname as NodeName
I0303 18:03:51.977790   10950 joinconfiguration.go:75] loading configuration from "./kubeone/cfg/master_1.yaml"
I0303 18:03:51.979592   10950 initconfiguration.go:102] detected and using CRI socket: /var/run/dockershim.sock
[preflight] Running pre-flight checks
I0303 18:03:51.979956   10950 preflight.go:90] [preflight] Running general checks
I0303 18:03:51.980155   10950 checks.go:250] validating the existence and emptiness of directory /etc/kubernetes/manifests
I0303 18:03:51.980342   10950 checks.go:287] validating the existence of file /etc/kubernetes/kubelet.conf
I0303 18:03:51.980471   10950 checks.go:287] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0303 18:03:51.980611   10950 checks.go:103] validating the container runtime
I0303 18:03:52.087630   10950 checks.go:129] validating if the service is enabled and active
I0303 18:03:52.201193   10950 checks.go:336] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0303 18:03:52.201456   10950 checks.go:336] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0303 18:03:52.201640   10950 checks.go:650] validating whether swap is enabled or not
I0303 18:03:52.201812   10950 checks.go:377] validating the presence of executable ip
I0303 18:03:52.201960   10950 checks.go:377] validating the presence of executable iptables
I0303 18:03:52.202062   10950 checks.go:377] validating the presence of executable mount
I0303 18:03:52.202170   10950 checks.go:377] validating the presence of executable nsenter
I0303 18:03:52.202278   10950 checks.go:377] validating the presence of executable ebtables
I0303 18:03:52.202375   10950 checks.go:377] validating the presence of executable ethtool
I0303 18:03:52.202473   10950 checks.go:377] validating the presence of executable socat
I0303 18:03:52.202567   10950 checks.go:377] validating the presence of executable tc
I0303 18:03:52.202661   10950 checks.go:377] validating the presence of executable touch
I0303 18:03:52.202761   10950 checks.go:521] running all checks
I0303 18:03:52.308195   10950 checks.go:407] checking whether the given node name is reachable using net.LookupHost
I0303 18:03:52.309197   10950 checks.go:619] validating kubelet version
I0303 18:03:52.379237   10950 checks.go:129] validating if the service is enabled and active
I0303 18:03:52.392943   10950 checks.go:202] validating availability of port 10250
I0303 18:03:52.393412   10950 checks.go:433] validating if the connectivity type is via proxy or direct
I0303 18:03:52.393563   10950 join.go:433] [preflight] Discovering cluster-info
I0303 18:03:52.393736   10950 token.go:188] [discovery] Trying to connect to API Server "10.21.142.212:6443"
I0303 18:03:52.394389   10950 token.go:73] [discovery] Created cluster-info discovery client, requesting info from "https://10.21.142.212:6443"
I0303 18:03:52.402346   10950 token.go:78] [discovery] Failed to request cluster info: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"]
I0303 18:03:52.402372   10950 token.go:191] [discovery] Failed to connect to API Server "10.21.142.212:6443": configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"
I0303 18:03:57.402641   10950 token.go:188] [discovery] Trying to connect to API Server "10.21.142.212:6443"
I0303 18:03:57.403494   10950 token.go:73] [discovery] Created cluster-info discovery client, requesting info from "https://10.21.142.212:6443"
I0303 18:03:57.405147   10950 token.go:78] [discovery] Failed to request cluster info: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"]
I0303 18:03:57.405308   10950 token.go:191] [discovery] Failed to connect to API Server "10.21.142.212:6443": configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"
I0303 18:04:02.405738   10950 token.go:188] [discovery] Trying to connect to API Server "10.21.142.212:6443"
I0303 18:04:02.406376   10950 token.go:73] [discovery] Created cluster-info discovery client, requesting info from "https://10.21.142.212:6443"
I0303 18:04:02.407742   10950 token.go:78] [discovery] Failed to request cluster info: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"]
I0303 18:04:02.407766   10950 token.go:191] [discovery] Failed to connect to API Server "10.21.142.212:6443": configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"
I0303 18:04:07.407942   10950 token.go:188] [discovery] Trying to connect to API Server "10.21.142.212:6443"
I0303 18:04:07.408580   10950 token.go:73] [discovery] Created cluster-info discovery client, requesting info from "https://10.21.142.212:6443"
I0303 18:04:07.410019   10950 token.go:78] [discovery] Failed to request cluster info: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"]
I0303 18:04:07.410043   10950 token.go:191] [discovery] Failed to connect to API Server "10.21.142.212:6443": configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"
I0303 18:04:12.410327   10950 token.go:188] [discovery] Trying to connect to API Server "10.21.142.212:6443"
I0303 18:04:12.410953   10950 token.go:73] [discovery] Created cluster-info discovery client, requesting info from "https://10.21.142.212:6443"
I0303 18:04:12.412720   10950 token.go:78] [discovery] Failed to request cluster info: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"]
I0303 18:04:12.412737   10950 token.go:191] [discovery] Failed to connect to API Server "10.21.142.212:6443": configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"
I0303 18:04:17.413026   10950 token.go:188] [discovery] Trying to connect to API Server "10.21.142.212:6443"
I0303 18:04:17.413752   10950 token.go:73] [discovery] Created cluster-info discovery client, requesting info from "https://10.21.142.212:6443"
I0303 18:04:17.414854   10950 token.go:78] [discovery] Failed to request cluster info: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"]
I0303 18:04:17.414885   10950 token.go:191] [discovery] Failed to connect to API Server "10.21.142.212:6443": configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"
I0303 18:04:22.415166   10950 token.go:188] [discovery] Trying to connect to API Server "10.21.142.212:6443"
I0303 18:04:22.415867   10950 token.go:73] [discovery] Created cluster-info discovery client, requesting info from "https://10.21.142.212:6443"
I0303 18:04:22.417471   10950 token.go:78] [discovery] Failed to request cluster info: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"]
I0303 18:04:22.417489   10950 token.go:191] [discovery] Failed to connect to API Server "10.21.142.212:6443": configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"

**Comment by kron4eg** [comment]
Hey @2vcps, thanks for the report.

Could you please share the config.yaml (with possible secrets removed).

P.S.
As a test, please try to reset your cluster, it seems like you have some leftovers on VMs.

**Comment by kron4eg** [comment]
I think `VirtualCenter` should contain an IP, not hostname

**Comment by 2vcps** [comment]
it fails either way. But I can try again.

**Comment by toschneck** [comment]
@2vcps could you provide some logs of the systemd kubelet service of the first master node. This should display maybe the error.

**Comment by 2vcps** [comment]
I can post them all but here is an excerpt that looks interesting if it helps:
```
Mar 23 14:44:48 demo-cp-1 kubelet[7117]: W0323 14:44:48.951345    7117 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Mar 23 14:44:52 demo-cp-1 kubelet[7117]: E0323 14:44:52.369546    7117 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Mar 23 14:44:52 demo-cp-1 kubelet[7117]: E0323 14:44:52.859330    7117 controller.go:135] failed to ensure node lease exists, will retry in 7s, error: leases.coordination.k8s.io "demo-cp-1" is forbidden: User "system:node:demo-cp-1.newstack.local" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requesting node
Mar 23 14:44:53 demo-cp-1 kubelet[7117]: W0323 14:44:53.951696    7117 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Mar 23 14:44:55 demo-cp-1 kubelet[7117]: W0323 14:44:55.974714    7117 setters.go:162] replacing cloudprovider-reported hostname of demo-cp-1 with overridden hostname of demo-cp-1.newstack.local
```

**Comment by toschneck** [comment]
ok I don't see there an error ...  Maybe the cloud controller manager can't talk to your vcenter instance. Next thing to debug would be to take a look at the logs of the kube controller manager docker container what get started from the kubelet. 
Maybe  the `insecure-flag = "1"` is the problem (vcenter often don't have a valid SSL certificate)

**Comment by xmudrii** [comment]
Seems like this issue is not active for some time, so I'll close it. If the issue is still present, please reopen this issue or create a new one.

/close
