### ISSUE TITLE
KubeOne join for worker nodes

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubeone#816]
**What feature would you like to be added?**

If a KubeOne user don’t use machine-controller (e.g. bare-metal, edge deployment, Ansible) instead of executing several commands on a worker a command like `kubeone join`  would make the installation easier. 
`kubeone join`will installs all dependencies and and execute `kubeadm join` command. Only one cmd is required to join a worker node.

**Comment by moelsayed** [comment]
As we discussed offline. We will not implement a dedicated `join` command, instead we will use a `StaticWorkers` API field.
