### ISSUE TITLE
Base permissions needed for Machine Deployment user on vsphere

### ISSUE THREAD

**Issue by mooperd** [kubermatic/kubeone#829]
Hi,

I am trying to work out what is the minimum vSphere permissions needed for the machinecontroller. At the moment I have the following perms in the role.

```
VirtualMachine.Inventory.Create
VirtualMachine.Inventory.CreateFromExisting
VirtualMachine.Inventory.Move
VirtualMachine.Config.AddNewDisk
VirtualMachine.Interact.PowerOn
VirtualMachine.Interact.PowerOff
VirtualMachine.Interact.ToolsInstall
VirtualMachine.Provisioning.Customize
Resource.AssignVMToPool
Datastore.AllocateSpace
Network.Assign
VirtualMachine.Interact.PowerOn
VirtualMachine.Interact.PowerOff
VirtualMachine.Inventory.CreateFromExisting
VirtualMachine.Provisioning.CloneTemplate
VirtualMachine.Provisioning.Clone
```

but I am getting an error:
```
WARN[12:51:27 UTC] error was: failed to deploy Machines: failed to ensure MachineDeployment: failed to create *v1alpha1.MachineDeployment: admission webhook "machine-controller.kubermatic.io-machinedeployments" denied the request: defaulting or validation failed: validation failed: failed to get cluster: Supermicro-Cluster: cluster 'Supermicro-Cluster' not found 
```

Could someone please explain the scope that the machinecontroller needs to do its job? ideally it should only need visibility on a folder and should not be trying to access root level vSphere objects like clusters.

Cheers,

Andrew

**Comment by shaase-ctrl** [comment]
We will copy the relevant content from https://docs.kubermatic.com/kubermatic/v2.17/architecture/requirements/support_policy/provider_support_matrix/vsphere/vsphere/ and integrate it with KubeOne Documentation.

**Comment by moadqassem** [comment]
Well, based on the description it is not necessarily a permission issues. based on the error, it seems that you provided a cluster name in the machine deployment which doesn't exist. Mainly we use the cluster name for validation and some metrics filtering.

**Comment by WeirdMachine** [comment]
https://github.com/kubermatic/docs/pull/695
