### ISSUE TITLE
Error installing Kubernetes cluster

### ISSUE THREAD

**Issue by Mohsin-GitHub** [kubermatic/kubeone#849]
Hi Team,

I got below error when running kubeone install
**commad**: kubeone install config.yaml -t .

Error: failed to load cluster: unable to load a given KubeOneCluster object: unable to validate the given KubeOneCluster object: hosts: Invalid value: true: only 1 leader is allowed

Any suggestions

**Comment by kron4eg** [comment]
@Mohsin-GitHub hey, yeah, this was a bug in 0.11 (we are prepareing new 0.11.x release), meanwhile — it's fixed in master.
