### ISSUE TITLE
A subcommand to manage addons

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#865]
## What feature would you like to be added?

As KubeOne got support for addons (#782) , we might need to add "addon package manager" subcommand to make it easier to:
* list publicly available (A.K.A. discovery) addons
* download them

`kubeone addons` subcommand should have at least 2 commands:
* `kubeone addons list` — that will fetch from the addons index (TODO: where this will be?) a list of available addons
* `kubeone addons get` — that will download the requested addon and place it into the addons directory (configured in KubeOne config).

### The addons index
One possible place can be `github.com/kubermatic/kubeone/{KUBEONE_VERSION}/addons/index.json`, as kubeone can detect own version and construct appropriate URL to the index JSON.

## What are use cases of the feature?
Greatly improve UX for the end user of KubeOne, and provide a facility to use/reuse different system software.

**Comment by shaase-ctrl** [comment]
Not that many users seem to use this feature.

**Comment by kron4eg** [comment]
Since we heavily changed the way addons work, probably we should close this one as obsolete.

**Comment by xmudrii** [comment]
@kron4eg A subcommand to manage addons could still be very useful. Right now, we don't have any way of listing addons or showing what's inside an addon, besides going to GitHub (which is not really user-friendly).

**Comment by kron4eg** [comment]
But it will be different subcommand from what I've anticipated initially, and it has to have new issue with new adapted requirements.

**Comment by kron4eg** [comment]
Replaced by #1622
