### ISSUE TITLE
Add ability to merge downloaded kubeconfig with an existing kubeconfig file

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#868]
**What feature would you like to be added?**

The kubeconfig file is always downloaded to the directory from which KubeOne was invoked. Usually, the user would like to have it in some other place, like `~/.kube/config`, so they can quickly access the cluster.

To make the user experience better, we should:
* Add ability to choose where to download the kubeconfig file (e.g. by using the `--kubeconfig` flag)
* If the chosen file already exists, we should merge those two files

This behavior is very common across many tools, so I think we should consider it as well.

**Comment by akash-gautam** [comment]
I would like to work on this.
One question I have is when we merge the config generated by kubeone to an existing config file should we update the current context in the config to the cluster created by kubeone or leave it as it is?

**Comment by kron4eg** [comment]
It's possible to merge different kubeconfigs using kubectl, please see more here: https://ahmet.im/blog/mastering-kubeconfig/#tip-3-merging-kubeconfig-files

I don't think we should reimplement the standard feature. If there would be no opposition, I propose to close this issue as "wontfix".
