### ISSUE TITLE
Dynamic SSH key management

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubeone#901]
**What feature would you like to be added?**
In respect of the use case that an kubeone cluster get operated by a operation team, kubeone needs option to modify (add, updated,remove) the allowed ssh public keys on every level:
- master nodes
- worker nodes

An update of the ssh-key should not trigger a redeployment (for debugging cases) or cause an downtime.
Similar approach like in Kubermatic https://github.com/kubermatic/kubermatic/tree/master/api/cmd/user-ssh-keys-agent where keys can be modified during runtime would be perfect.

**What are use cases of the feature?**
In the current setup of kubeone the SSH keys are more or less static
- master nodes (keys can't easily managed (update/remove), only by custom terraform code)
- Adding SSH-Keys to Machinecontroller creates new Machines what is problematic for troubleshooting of a crashed node

This feature would help customer for maintaining their seed cluster and our own environments in an easier way.

**Comment by kron4eg** [comment]
@toschneck "ssh-keys-agent-sync-whatever" is a hypothetical daemonset that copy stuff on the host. What is has to do with kubeone?

**Comment by scheeles** [comment]
One solution could be to use https://github.com/gravitational/teleport for manage dynamic SSH user or any PAM module https://www.ssh.com/manuals/server-admin/61/userauth-kbi-pam.html

**Comment by scheeles** [comment]
Another option would be to use Vault to manage SSH access https://medium.com/@Amet13/generating-ssh-one-time-passwords-with-vault-7aa7fab0032

**Comment by toschneck** [comment]
As discussed in slack, kubeone should focus on an option to integrate some common ssh key-management (what is already given). So it would be great if we can create best practice docu how to use it. @kron4eg could we change the type to `kind/documentation` or `kind/question`?

**Comment by kron4eg** [comment]
@toschneck changed
