### ISSUE TITLE
Kubeone install command throw error related to kubeadm

### ISSUE THREAD

**Issue by ahmadelkhateb** [kubermatic/kubeone#914]
**What happened**:
I followed the tutorial of building AWS k8s cluster using terraform and kubeone and everything went will until i ran the `kubeone install config.yaml -t tf.json`  command

**What is the expected behavior**:
It is supposed to build the cluster successfully 
however it throws error says that :

> Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39

Here is the full error 

> INFO[17:28:03 EET] Running kubeadm…                              node=172.31.178.59
WARN[17:28:04 EET] Task failed…                                 
Error: failed to init kubernetes on leader: + export 
+ [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm init --config=./kubeone/cfg/master_0.yaml
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR CRI]: container runtime is not running: output: Client:
 Debug Mode: false
Server:
ERROR: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
errors pretty printing info
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher: failed to exec command: set -xeu pipefail
export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"
if [[ -f /etc/kubernetes/admin.conf ]]; then
	sudo kubeadm  token create wk26rc.il38fz8fvd4usg6y --ttl 1h0m0s
	exit 0;
fi
sudo kubeadm  init --config=./kubeone/cfg/master_0.yaml
: Process exited with status 1

**FYI**
I have searched for the problem and found that it is related to Docker Api Verison how ever i tried to downgrade docker and it still not working 

**Information about the environment**:
KubeOne version (`0.11.1`): 
Operating system: ubuntu
Provider you're deploying cluster on: AWS
Operating system you're deploying on: ubuntu

**Comment by xmudrii** [comment]
This issue has been fixed in the v0.11.2 release. Please use that one instead of v0.11.1.

/close
