### ISSUE TITLE
OpenStack - Failed to deploy worker Machines

### ISSUE THREAD

**Issue by giezi** [kubermatic/kubeone#916]
Hi there,

I try to deploy a Kubernetes cluster according the OpenStack quick start guide (https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-openstack.md).
Everything goes well before and it fails at the following step:

<img width="1367" alt="Screenshot 2020-05-28 at 15 51 20" src="https://user-images.githubusercontent.com/1326203/83151001-45b64f80-a0fc-11ea-9a3f-e00fba5d5113.png">

`INFO[15:45:51 CEST] Downloading kubeconfig…
INFO[15:45:51 CEST] Building Kubernetes clientset…
INFO[15:45:51 CEST] Ensure node local DNS cache…
INFO[15:45:51 CEST] Activating additional features…
INFO[15:45:54 CEST] Applying canal CNI plugin…
INFO[15:46:01 CEST] Creating credentials secret…
INFO[15:46:02 CEST] Installing machine-controller…
INFO[15:46:06 CEST] Installing machine-controller webhooks…
INFO[15:46:06 CEST] Waiting for machine-controller to come up…
INFO[15:49:27 CEST] Creating worker machines…
WARN[15:49:57 CEST] Task failed…
WARN[15:49:57 CEST] error was: failed to deploy Machines: failed to ensure MachineDeployment: failed to create *v1alpha1.MachineDeployment: Internal error occurred: failed calling webhook "machine-controller.kubermatic.io-machinedeployments": Post https://machine-controller-webhook.kube-system.svc:443/machinedeployments?timeout=30s: context deadline exceeded`

Is there a way to get more information about the issue?

Many thanks and best regards
Reto

**Comment by kron4eg** [comment]
@giezi what OS did you used?

**Comment by giezi** [comment]
@kron4eg I use Ubuntu 20.04 LTS.

**Comment by kron4eg** [comment]
@giezi we actually never tested it yet, can you try ubuntu 18.04?

**Comment by giezi** [comment]
Sorry, I was incorrect and used Ubuntu 18.04 LTS.

**Comment by xmudrii** [comment]
It seems like this issue has not been active recently, so I'll go ahead and close it. If the issue is still present, please reopen it or create a new one.

/close
