### ISSUE TITLE
Support for external etcd clusters

### ISSUE THREAD

**Issue by ManuStoessel** [kubermatic/kubeone#926]
**What feature would you like to be added?**

KubeOne should be able to support using an externally managed etcd cluster for the Kubernetes control plane. Kubeadm supports using an external ectd cluster, as is described [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/).

**What are use cases of the feature?**

Splitting the etcd cluster from the rest of the Kubernetes control plane would allow for the following:
- independent scaling of etcd and Kubernetes control plane nodes
- performance tuning of etcd cluster
- being able to run etcd cluster in different environment than the Kubernetes cluster itself
- a slight security advantage of keeping the cluster state in etcd explicitly seperate from running containerized user workloads

**Comment by shibumi** [comment]
@shaase-ctrl  has this feature being added?

**Comment by kron4eg** [comment]
> @shaase-ctrl has this feature being added?

Nope. Not yet, but we still having internal discussion for wether we should support this. External etcds are not the problem (kubeadm support it), but we having a problem to define good balance between UX and security to allow to manage PKI for etcd.

**Comment by shibumi** [comment]
@kron4eg  Thanks for the fast explanation :+1:
