### ISSUE TITLE
VMware install -- 'folder_name' variable not declared

### ISSUE THREAD

**Issue by cjstone** [kubermatic/kubeone#928]
I'm following this documentation, which references a terraform variable named "folder_name". However that variable doesn't seem to be declared anywhere in the code.

https://docs.kubermatic.com/kubeone/master/getting_started/vsphere/

Error on running `terraform plan`:

```Warning: Value for undeclared variable

The root module does not declare a variable named "folder_name" but a value
was found in file "terraform.tfvars". To use this value, add a "variable"
block to the configuration.

**Comment by kron4eg** [comment]
We definitely have folder_name defined: https://github.com/kubermatic/kubeone/blob/master/examples/terraform/vsphere/variables.tf#L78-L81. Please make sure you have updated git clone.

**Comment by xmudrii** [comment]
It seems like this issue has not been active recently, so I'll go ahead and close it. If the issue is still present, please reopen it or create a new one.

/close
