### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by frittenlab** [kubermatic/kubeone#931]
I tried to follow your getting started guide for AWS. I found one small mistake with the following command:

`kubeone install -m config.yaml --tfjson <DIR-WITH-tfstate-FILE>`

`ubuntu@gitlab:~/examples/terraform/aws$ kubeone install -m config.yaml --tfjson .
Error: unknown shorthand flag: 'm' in -m
unknown shorthand flag: 'm' in -m`

The correct command should be:

`kubeone install config.yaml --tfjson .`

Without the -m 

Everything else worked without a problem. I had to restart the process once. The machine controller showed me an error and did not create any worker nodes. On the second attempt everything worked without a problem. I am using kubeone version 0.11.2

**Comment by xmudrii** [comment]
@frittenlab The `--manifest`/`-m` flag is only available for the v1.0.0 alpha releases. Docs on the website and the master branch are referring to the alpha releases. For v0.11 docs, please check docs on the [`release/v0.11` branch](https://github.com/kubermatic/kubeone/tree/release/v0.11/docs).

I'm going to close this issue. If you encounter any other issue, please feel free to reopen this issue or create a new one.

/close
