### ISSUE TITLE
Canal CNI defective in rare cases

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubeone#934]
**What happened**:

When installing a KubeOne cluster, in rare cases the Canal CNI pods are shown to be running but not usable. The entire KubeOne installation fails when deploying the machine-controller in this case. Machine-controller and CoreDNS pods stay in pending state due to the following condition:

`Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "6675d4875be32a0a78d89e208f3fb61d09b72e597e6565ee14121e69336006f8" network for pod "coredns-6955765f44-pggjl": networkPlugin cni failed to set up pod "coredns-6955765f44-pggjl_kube-system" network: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: the server could not find the requested resource (get ClusterInformations.crd.projectcalico.org default), failed to clean up sandbox container "6675d4875be32a0a78d89e208f3fb61d09b72e597e6565ee14121e69336006f8" network for pod "coredns-6955765f44-pggjl": networkPlugin cni failed to teardown pod "coredns-6955765f44-pggjl_kube-system" network: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: the server could not find the requested resource (get ClusterInformations.crd.projectcalico.org default)]`

Canal's calico container logs the following error:

`2020-06-24 11:20:44.067 [ERROR][8] client.go 251: Error creating cluster information config ClusterInformation=&v3.ClusterInformation{TypeMeta:v1.TypeMeta{Kind:"ClusterInformation", APIVersion:"projectcalico.org/v3"}, ObjectMeta:v1.ObjectMeta{Name:"default", GenerateName:"", Namespace:"", SelfLink:"", UID:"4e7c4b94-e00d-437b-959a-e277c807caf7", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0xbfb4eba303d8c464, ext:6639844301, loc:(*time.Location)(0x2d61840)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v3.ClusterInformationSpec{ClusterGUID:"f1988d2388444411b0bd7f42db3471f8", ClusterType:"k8s,canal,kdd", CalicoVersion:"v3.10.0", DatastoreReady:(*bool)(0xc0002b2973)}} error=resource does not exist: ClusterInformation(default) with error: the server could not find the requested resource (post ClusterInformations.crd.projectcalico.org)`

The CRDs in question are available after this. So this looks like a race condition, caused by CRDs not usable yet when the calico container is started. Deleting the canal pods solves the problem.

**What is the expected behavior**:

Maybe separating the CRD deployment and waiting until it is actually available makes the cluster creation more robust.

**How to reproduce the issue**:

Appears occasionally during a `kubeone install`

**Anything else we need to know?**

Might be reinforced by an unresponsive etcd ring due to https://github.com/kubermatic/kubeone/issues/915

**Information about the environment**:
KubeOne version (`kubeone version`): v1.0.0-alpha.6
Operating system: CentOS (master)
Provider you're deploying cluster on: Azure
Operating system you're deploying on: OSX

**Comment by xmudrii** [comment]
I've just had the same situation on AWS running Flatcar.

**Comment by kron4eg** [comment]
> Maybe separating the CRD deployment and waiting until it is actually available makes the cluster creation more robust.

I was convinced we already doing this. But it turned out to be a fantasy :D
