### ISSUE TITLE
unable to load a given kubeOneClusterObject

### ISSUE THREAD

**Issue by FahimaGold** [kubermatic/kubeone#973]
I was trying to install kubeone on ubuntu 16.06, when  I run kubeone install config.yaml --tfjson tf.json or kubeone install, I get the following error:

Failed to initialize state:failed to build sate:failed to load cluster unable to load a given kubeOneClusterObject: unable to to read the given cluster configuration file: open ./kubeone.yaml no such fileor directory
:
KubeOne version 1.15: 
Operating system:  Ubuntu 16.04
Provider you're deploying cluster on:aws
Operating system you're deploying on: linux

**Comment by xmudrii** [comment]
If you are using KubeOne v1.0 alpha or beta release, you need to use the following command:

> kubeone install --manifest config.yaml --tfjson tf.json

Or if you name your manifest `kubeone.yaml`, then you can just run

> kubeone install --tfjson tf.json

**Comment by kron4eg** [comment]
@FahimaGold relatively recently we've switched config from positional argument to flag, please see more ‘kubeone install --help’.

I had impression we've fixed this change in all of our docs, could you please point us to broken doc that present such positional argument?

**Comment by FahimaGold** [comment]
@kron4eg  @xmudrii   I used this doc: https://github.com/kubermatic/kubeone. 
I also find that the documentation needs some improvement, this is the first time I came accross kubeone and I really got lost.
Thanks

**Comment by xmudrii** [comment]
@FahimaGold That part of the README is outdated and I've just created two PRs to update it:
* https://github.com/kubermatic/kubeone/pull/974
* https://github.com/kubermatic/docs/pull/364

You can find detailed and up-to-date guides showing how to get started and how to manage clusters using KubeOne at the [docs website](https://docs.kubermatic.com/kubeone/master/).
