### ISSUE TITLE
KubeOne as kubectl plugin

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubeone#993]
**What feature would you like to be added?**
Provide kubeone as an plugin for kubectl and make it available via https://github.com/kubernetes-sigs/krew-index 

**What are use cases of the feature?**
Easy to install and update kubeone

**Comment by xmudrii** [comment]
@nerdeveloper I tested it locally as well and it works with the zip archive. I recommend trying to retest the PR or pushing a new commit to retrigger tests, and if that doesn't work, pinging the maintainers to take a look.

**Comment by xmudrii** [comment]
@nerdeveloper @kron4eg After discussion with Krew maintainers, we concluded that KubeOne wouldn't be a suitable kubectl plugin. The Krew index accepts plugins that manipulate Kubernetes resources, as that's the purpose of kubectl itself. I recommend checking https://github.com/kubernetes-sigs/krew-index/pull/1701 for more details.

I see three possible approaches:

1) do nothing
2) create a custom [Krew plugin index](https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/) — in my opinion, this doesn't seem worth the effort
3) integrate with package managers (e.g. brew, snap) — for example, we already have the KubeOne package in the Arch Linux repos, but I'm not sure are there any stats on how much is it used

If you think approach 2 or 3 would be useful, please create a ticket and we can discuss it there. I'm going to close this issue for now.
/close

**Comment by shibumi** [comment]
> integrate with package managers (e.g. brew, snap) — for example, we already have the KubeOne package in the Arch Linux repos, but I'm not sure are there any stats on how much is it used

Hello @xmudrii I had a look on our Arch Linux package stats. Right now we have
17061 users exposing these statistics and 12 people have kubeOne installed on their system. If I count myself in (who is not exposing statistics on his systems) we have: 16062 users and 13 KubeOne installations. 

This is a popularity of ~ 0.1%


We do not know the absolute numbers of all Arch Linux installations/setups world wide. The website ostoday (https://ostoday.org/android/how-many-users-does-arch-linux-have.html) estimates a user count of 4,800,000 users.

This number is little bit pessimistic, but let's calculate with this.

If we have 4,800,000 users we can estimate that we have (according to our statistics) 0.1% KubeOne users.
This means, that 48,000 users world wide use KubeOne on Arch Linux.

(Personally, I think the Arch Linux community is much bigger. We are the biggest Linux Reddit community world wide.. etc.
Hence, the absolute numbers of KubeOne users on Arch Linux would be bigger).
